{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSummary"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpushdisplaystyle\/messagesummary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpushdisplaystyle\/messagesummary"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/messageSummary","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A simple banner that displays “You have a new message”."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSummary"}],"title":"AgoraChatPushDisplayStyle.messageSummary","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatPushDisplayStyle@AgoraChatPushDisplayStyleMessageSummary","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle":{"role":"symbol","title":"AgoraChatPushDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"abstract":[{"type":"text","text":"The display style of push message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/messageSummary":{"role":"symbol","title":"AgoraChatPushDisplayStyle.messageSummary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSummary"}],"abstract":[{"type":"text","text":"A simple banner that displays “You have a new message”."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/messageSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/messagesummary"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatPushDisplayStyleMessageSummary"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/title","value":"AgoraChatPushDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1messageSummary\/title","value":"AgoraChatPushDisplayStyleMessageSummary"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1messageSummary\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}