{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatThreadManagerDelegate","text":"AgoraChatThreadManagerDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatthreadmanager\/remove(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatthreadmanager\/remove(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatThreadManager\/remove(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Remove delegate"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"role":"symbol","title":"remove(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatThreadManagerDelegate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatThreadManager(im)removeDelegate:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatThreadManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatThreadManager/remove(_:)":{"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"role":"symbol","title":"remove(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatThreadManagerDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove delegate"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatThreadManager\/remove(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatthreadmanager\/remove(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatThreadManager":{"role":"symbol","title":"IAgoraChatThreadManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatThreadManager"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatThreadManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatThreadManager"}],"url":"\/documentation\/agorachat\/iagorachatthreadmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate":{"role":"symbol","title":"AgoraChatThreadManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"abstract":[{"type":"text","text":"The message thread event callback protocol."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraChatThreadManagerDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraChatThreadManagerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatThreadManager~1remove(_:)\/title","value":"removeDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatThreadManager~1remove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatThreadManager\/title","value":"IAgoraChatThreadManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatThreadManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatThreadManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate\/title","value":"AgoraChatThreadManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}