{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"User A and B both will receive this callback after User B unfriended user A."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidremove(byuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidremove(byuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidRemove(byUser:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when a user is removed as a contact by another user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"friendshipDidRemove(byUser:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatContactManagerDelegate(im)friendshipDidRemoveByUser:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"friendshipDidRemoveByUser:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendshipDidRemove(byUser:)":{"role":"symbol","title":"friendshipDidRemove(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user is removed as a contact by another user."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidRemove(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendshipDidRemoveByUser:"}],"url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidremove(byuser:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate":{"role":"symbol","title":"AgoraChatContactManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"abstract":[{"type":"text","text":"The contact related callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"friendshipDidRemoveByUser:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidRemoveByUser:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"friendshipDidRemoveByUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidRemove(byUser:)\/title","value":"friendshipDidRemoveByUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidRemove(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidRemoveByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate\/title","value":"AgoraChatContactManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}