{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatThreadManager","preciseIdentifier":"c:objc(pl)IAgoraChatThreadManager","text":"IAgoraChatThreadManager"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatclient\/threadmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatclient\/threadmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient\/threadManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Thread Management"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IAgoraChatThreadManager","preciseIdentifier":"c:objc(pl)IAgoraChatThreadManager"},{"kind":"text","text":"?"}],"title":"threadManager","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatClient(py)threadManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"threadManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClient/threadManager":{"role":"symbol","title":"threadManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IAgoraChatThreadManager","preciseIdentifier":"c:objc(pl)IAgoraChatThreadManager"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Thread Management"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient\/threadManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threadManager"}],"url":"\/documentation\/agorachat\/agorachatclient\/threadmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatThreadManager":{"role":"symbol","title":"IAgoraChatThreadManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatThreadManager"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatThreadManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatThreadManager"}],"url":"\/documentation\/agorachat\/iagorachatthreadmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClient":{"role":"symbol","title":"AgoraChatClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClient"}],"abstract":[{"type":"text","text":"The AgoraChatClient, which is the entry point of the Chat SDK. You can log in, log out, and access other functionalities such as group and chatroom with this class."},{"type":"text","text":" "},{"type":"text","text":"[AgoraChatClient sharedClient].groupManager;"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatClient"}],"url":"\/documentation\/agorachat\/agorachatclient"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"threadManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"threadManager"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<IAgoraChatThreadManager>","preciseIdentifier":"c:Qoobjc(pl)IAgoraChatThreadManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"threadManager"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient~1threadManager\/title","value":"threadManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient~1threadManager\/fragments","value":[{"kind":"identifier","text":"threadManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatThreadManager\/title","value":"IAgoraChatThreadManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatThreadManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatThreadManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient\/title","value":"AgoraChatClient"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient\/fragments","value":[{"kind":"identifier","text":"AgoraChatClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}