{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTranslateResults"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult","preciseIdentifier":"c:objc(cs)AgoraChatTranslationResult","text":"AgoraChatTranslationResult"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachattranslatemanager\/loadtranslateresults(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachattranslatemanager\/loadtranslateresults(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/loadTranslateResults(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the latest message translation information for the specified number of messages"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadTranslateResults:"}],"role":"symbol","title":"loadTranslateResults(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTranslateResults"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AgoraChatTranslationResult","preciseIdentifier":"c:objc(cs)AgoraChatTranslationResult"},{"kind":"text","text":"]!"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatTranslateManager(im)loadTranslateResults:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/loadTranslateResults(_:)":{"navigatorTitle":[{"kind":"identifier","text":"loadTranslateResults:"}],"role":"symbol","title":"loadTranslateResults(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTranslateResults"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AgoraChatTranslationResult","preciseIdentifier":"c:objc(cs)AgoraChatTranslationResult"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Gets the latest message translation information for the specified number of messages"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/loadTranslateResults(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/loadtranslateresults(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager":{"role":"symbol","title":"IAgoraChatTranslateManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatTranslateManager"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}],"url":"\/documentation\/agorachat\/iagorachattranslatemanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatTranslationResult":{"role":"symbol","title":"AgoraChatTranslationResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatTranslationResult"}],"abstract":[{"type":"text","text":"The message translate info"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatTranslationResult"}],"url":"\/documentation\/agorachat\/agorachattranslationresult"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadTranslateResults:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTranslateResults:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatTranslationResult *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loadTranslateResults:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"count"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1loadTranslateResults(_:)\/title","value":"loadTranslateResults:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1loadTranslateResults(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTranslateResults:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager\/title","value":"IAgoraChatTranslateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult\/title","value":"AgoraChatTranslationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult\/fragments","value":[{"kind":"identifier","text":"AgoraChatTranslationResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}