{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadKick"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadkick"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadkick"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadKick","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User A updates the event in the sub-area of device A1, and other devices logged in to this account will receive this event"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadKick"}],"title":"AgoraChatMultiDevicesEvent.chatThreadKick","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMultiDevicesEvent@AgoraChatMultiDevicesEventChatThreadKick","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadKick":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadKick","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadKick"}],"abstract":[{"type":"text","text":"User A updates the event in the sub-area of device A1, and other devices logged in to this account will receive this event"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadKick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadkick"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesEventChatThreadKick"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadKick\/title","value":"AgoraChatMultiDevicesEventChatThreadKick"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadKick\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}