{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupApplyDecline"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupapplydecline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupapplydecline"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyDecline","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If user A receives another user’s request to join the chat group on DeviceA1, this event is triggered on DeviceA2."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupApplyDecline"}],"title":"AgoraChatMultiDevicesEvent.groupApplyDecline","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMultiDevicesEvent@AgoraChatMultiDevicesEventGroupApplyDecline","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupApplyDecline":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupApplyDecline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupApplyDecline"}],"abstract":[{"type":"text","text":"If user A receives another user’s request to join the chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyDecline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupapplydecline"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesEventGroupApplyDecline"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApplyDecline\/title","value":"AgoraChatMultiDevicesEventGroupApplyDecline"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApplyDecline\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}