{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle","text":"AgoraChatPushDisplayStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpushoptions\/displaystyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpushoptions\/displaystyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The display style of the notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle"}],"title":"displayStyle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatPushOptions(py)displayStyle","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"displayStyle"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/displayStyle":{"role":"symbol","title":"displayStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle"}],"abstract":[{"type":"text","text":"The display style of the notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayStyle"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/displaystyle"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions":{"role":"symbol","title":"AgoraChatPushOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushOptions"}],"abstract":[{"type":"text","text":"The options for Apple Push Notification service (APNs)."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushOptions"}],"url":"\/documentation\/agorachat\/agorachatpushoptions"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle":{"role":"symbol","title":"AgoraChatPushDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"abstract":[{"type":"text","text":"The display style of push message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"displayStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"displayStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle","text":"AgoraChatPushDisplayStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayStyle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1displayStyle\/title","value":"displayStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1displayStyle\/fragments","value":[{"kind":"identifier","text":"displayStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions\/title","value":"AgoraChatPushOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/title","value":"AgoraChatPushDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}