{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentNotification"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatnotificationstate\/willpresentnotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatnotificationstate\/willpresentnotification"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState\/willPresentNotification","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentNotification"}],"title":"AgoraChatNotificationState.willPresentNotification","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatNotificationState@AgoraChatWillPresentNotification","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatWillPresentNotification"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatNotificationState/willPresentNotification":{"role":"symbol","title":"AgoraChatNotificationState.willPresentNotification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentNotification"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState\/willPresentNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatWillPresentNotification"}],"url":"\/documentation\/agorachat\/agorachatnotificationstate\/willpresentnotification"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatNotificationState":{"role":"symbol","title":"AgoraChatNotificationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatNotificationState"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatNotificationState"}],"url":"\/documentation\/agorachat\/agorachatnotificationstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatWillPresentNotification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatWillPresentNotification"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatWillPresentNotification"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState~1willPresentNotification\/title","value":"AgoraChatWillPresentNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState~1willPresentNotification\/fragments","value":[{"kind":"identifier","text":"AgoraChatWillPresentNotification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState\/title","value":"AgoraChatNotificationState"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState\/fragments","value":[{"kind":"identifier","text":"AgoraChatNotificationState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}