{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllChatroomsFromServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCompletionBlock"},{"kind":"text","text":": ((["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated, please use  {@link getChatroomsFromServerWithPage}  instead."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatroommanager\/getallchatroomsfromserver(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatroommanager\/getallchatroomsfromserver(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatroomManager\/getAllChatroomsFromServer(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets all the chatrooms from server."}],"kind":"symbol","metadata":{"modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"getAllChatroomsFromServerWithCompletion:"}],"role":"symbol","title":"getAllChatroomsFromServer(completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllChatroomsFromServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatroomManager(im)getAllChatroomsFromServerWithCompletion:","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatroomManager"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use -getChatroomsFromServerWithPage instead"}]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatroomManager":{"role":"symbol","title":"IAgoraChatroomManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatroomManager"}],"abstract":[{"type":"text","text":"A class that manages the chatrooms."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatroomManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatroomManager"}],"url":"\/documentation\/agorachat\/iagorachatroommanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatroomManager/getAllChatroomsFromServer(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getAllChatroomsFromServerWithCompletion:"}],"deprecated":true,"role":"symbol","title":"getAllChatroomsFromServer(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllChatroomsFromServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")!)"}],"abstract":[{"type":"text","text":"Gets all the chatrooms from server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatroomManager\/getAllChatroomsFromServer(completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatroommanager\/getallchatroomsfromserver(completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAllChatroomsFromServerWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllChatroomsFromServerWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAllChatroomsFromServerWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray *, AgoraChatError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSArray#*$objc(cs)AgoraChatError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aCompletionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatroomManager\/title","value":"IAgoraChatroomManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatroomManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatroomManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatroomManager~1getAllChatroomsFromServer(completion:)\/title","value":"getAllChatroomsFromServerWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatroomManager~1getAllChatroomsFromServer(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllChatroomsFromServerWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}