{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CN"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/areacode\/cn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/areacode\/cn"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/CN","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CN"}],"title":"AreaCode.CN","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AreaCode@AreaCodeCN","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AreaCodeCN"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode":{"role":"symbol","title":"AreaCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCode"}],"url":"\/documentation\/agorachat\/areacode"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/CN":{"role":"symbol","title":"AreaCode.CN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CN"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/CN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeCN"}],"url":"\/documentation\/agorachat\/areacode\/cn"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AreaCodeCN"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AreaCodeCN"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AreaCodeCN"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/title","value":"AreaCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/fragments","value":[{"kind":"identifier","text":"AreaCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1CN\/title","value":"AreaCodeCN"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1CN\/fragments","value":[{"kind":"identifier","text":"AreaCodeCN"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}