{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLOB"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/areacode\/glob"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/areacode\/glob"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/GLOB","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLOB"}],"title":"AreaCode.GLOB","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AreaCode@AreaCodeGLOB","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AreaCodeGLOB"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode":{"role":"symbol","title":"AreaCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCode"}],"url":"\/documentation\/agorachat\/areacode"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/GLOB":{"role":"symbol","title":"AreaCode.GLOB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLOB"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/GLOB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeGLOB"}],"url":"\/documentation\/agorachat\/areacode\/glob"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AreaCodeGLOB"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AreaCodeGLOB"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AreaCodeGLOB"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/title","value":"AreaCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/fragments","value":[{"kind":"identifier","text":"AreaCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1GLOB\/title","value":"AreaCodeGLOB"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1GLOB\/fragments","value":[{"kind":"identifier","text":"AreaCodeGLOB"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}