{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatPresenceManagerDelegate","text":"AgoraChatPresenceManagerDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatpresencemanager\/remove(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatpresencemanager\/remove(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/remove(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes a delegate."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"role":"symbol","title":"remove(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatPresenceManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatPresenceManagerDelegate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatPresenceManager(im)removeDelegate:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/remove(_:)":{"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"role":"symbol","title":"remove(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatPresenceManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatPresenceManagerDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes a delegate."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/remove(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/remove(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresenceManagerDelegate":{"role":"symbol","title":"AgoraChatPresenceManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresenceManagerDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol that defines presence callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresenceManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatpresencemanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager":{"role":"symbol","title":"IAgoraChatPresenceManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPresenceManager"}],"abstract":[{"type":"text","text":"The presence management protocol that defines how to manage presence states."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}],"url":"\/documentation\/agorachat\/iagorachatpresencemanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraChatPresenceManagerDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraChatPresenceManagerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1remove(_:)\/title","value":"removeDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1remove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceManagerDelegate\/title","value":"AgoraChatPresenceManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresenceManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager\/title","value":"IAgoraChatPresenceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}