{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLocalNotificationDelegate","text":"AgoraChatLocalNotificationDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you enable this service, the new message is reported in the notification bar so that users can read them in time."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationmanager\/launch(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationmanager\/launch(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/launch(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables the chat message notification service."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatLocalNotificationDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLocalNotificationDelegate"},{"kind":"text","text":")"}],"title":"launch(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChatLocalNotificationManager(im)launchWithDelegate:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"launchWithDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager":{"role":"symbol","title":"AgoraChatLocalNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"abstract":[{"type":"text","text":"A class that manages the chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager/launch(with:)":{"role":"symbol","title":"launch(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatLocalNotificationDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLocalNotificationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables the chat message notification service."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/launch(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"launchWithDelegate:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager\/launch(with:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate":{"role":"symbol","title":"AgoraChatLocalNotificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"launchWithDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"launchWithDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"launchWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraChatLocalNotificationDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraChatLocalNotificationDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager\/title","value":"AgoraChatLocalNotificationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1launch(with:)\/title","value":"launchWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1launch(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"launchWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/title","value":"AgoraChatLocalNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}