{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"center"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationmanager\/usernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationmanager\/usernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:didReceive:withCompletionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When the system receives a push notification, the callback method is triggered when the notification bar is clicked."},{"type":"text","text":" "},{"type":"text","text":"User should call this method in the implementation of UNUserNotificationCenterDelegate if they have override UNUserNotificationCenterDelegate in-app."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChatLocalNotificationManager(im)userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"role":"symbol","title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When the system receives a push notification, the callback method is triggered when the notification bar is clicked."},{"type":"text","text":" "},{"type":"text","text":"User should call this method in the implementation of UNUserNotificationCenterDelegate if they have override UNUserNotificationCenterDelegate in-app."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:didReceive:withCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager\/usernotificationcenter(_:didreceive:withcompletionhandler:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager":{"role":"symbol","title":"AgoraChatLocalNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"abstract":[{"type":"text","text":"A class that manages the chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userNotificationCenter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"center"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveNotificationResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"response"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager\/title","value":"AgoraChatLocalNotificationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}