{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatconnectionstate\/disconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatconnectionstate\/disconnected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConnectionState\/disconnected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The SDK is connected to the chat server."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"title":"AgoraChatConnectionState.disconnected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatConnectionState@AgoraChatConnectionDisconnected","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatConnectionDisconnected"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConnectionState"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConnectionState/disconnected":{"role":"symbol","title":"AgoraChatConnectionState.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"abstract":[{"type":"text","text":"The SDK is connected to the chat server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConnectionState\/disconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConnectionDisconnected"}],"url":"\/documentation\/agorachat\/agorachatconnectionstate\/disconnected"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConnectionState":{"role":"symbol","title":"AgoraChatConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConnectionState"}],"abstract":[{"type":"text","text":"The connection state."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConnectionState"}],"url":"\/documentation\/agorachat\/agorachatconnectionstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatConnectionDisconnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatConnectionDisconnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatConnectionDisconnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConnectionState~1disconnected\/title","value":"AgoraChatConnectionDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConnectionState~1disconnected\/fragments","value":[{"kind":"identifier","text":"AgoraChatConnectionDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConnectionState\/title","value":"AgoraChatConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConnectionState\/fragments","value":[{"kind":"identifier","text":"AgoraChatConnectionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}