{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatistics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics","preciseIdentifier":"c:objc(cs)AgoraChatMessageStatistics","text":"AgoraChatMessageStatistics"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatistics(byid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatistics(byid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatistics(byId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the message traffic statistics by message ID."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getMessageStatisticsById:"}],"role":"symbol","title":"getMessageStatistics(byId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatistics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatistics","preciseIdentifier":"c:objc(cs)AgoraChatMessageStatistics"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatStatisticsManager(im)getMessageStatisticsById:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager":{"role":"symbol","title":"IAgoraChatStatisticsManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"abstract":[{"type":"text","text":"The protocol that defines statistical operations of message traffic."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"url":"\/documentation\/agorachat\/iagorachatstatisticsmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatistics":{"role":"symbol","title":"AgoraChatMessageStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatistics"}],"abstract":[{"type":"text","text":"The message traffic statistics."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatistics"}],"url":"\/documentation\/agorachat\/agorachatmessagestatistics"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager/getMessageStatistics(byId:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessageStatisticsById:"}],"role":"symbol","title":"getMessageStatistics(byId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatistics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatistics","preciseIdentifier":"c:objc(cs)AgoraChatMessageStatistics"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the message traffic statistics by message ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatistics(byId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatistics(byid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMessageStatisticsById:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageStatisticsById:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics","preciseIdentifier":"c:objc(cs)AgoraChatMessageStatistics","text":"AgoraChatMessageStatistics"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getMessageStatisticsById:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager\/title","value":"IAgoraChatStatisticsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatistics\/title","value":"AgoraChatMessageStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatistics\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatistics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatistics(byId:)\/title","value":"getMessageStatisticsById:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatistics(byId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageStatisticsById:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}