{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatisticsSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withStart"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":" "},{"kind":"internalParam","text":"endTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsDirection","text":"AgoraChatMessageStatisticsDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsType","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsType","text":"AgoraChatMessageStatisticsType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The traffic is measured in bytes."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatisticssize(withstart:end:direction:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatisticssize(withstart:end:direction:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatisticsSize(withStart:end:direction:type:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the total traffic amount of messages that meet the statistical conditions."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:end:direction:type:"}],"role":"symbol","title":"getMessageStatisticsSize(withStart:end:direction:type:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatisticsSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsDirection","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsType","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatStatisticsManager(im)getMessageStatisticsSizeWithStart:end:direction:type:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager/getMessageStatisticsSize(withStart:end:direction:type:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:end:direction:type:"}],"role":"symbol","title":"getMessageStatisticsSize(withStart:end:direction:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatisticsSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsDirection","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsType","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Gets the total traffic amount of messages that meet the statistical conditions."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatisticsSize(withStart:end:direction:type:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatisticssize(withstart:end:direction:type:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager":{"role":"symbol","title":"IAgoraChatStatisticsManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"abstract":[{"type":"text","text":"The protocol that defines statistical operations of message traffic."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"url":"\/documentation\/agorachat\/iagorachatstatisticsmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsType":{"role":"symbol","title":"AgoraChatMessageStatisticsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsType"}],"abstract":[{"type":"text","text":"The message body types for querying."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsType"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticstype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"abstract":[{"type":"text","text":"The message direction types for querying."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMessageStatisticsSizeWithStart:end:direction:type:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:end:direction:type:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"startTimestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"end:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"endTimestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsDirection","text":"AgoraChatMessageStatisticsDirection"},{"kind":"text","text":")"},{"kind":"internalParam","text":"direction"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsType","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsType","text":"AgoraChatMessageStatisticsType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatisticsSize(withStart:end:direction:type:)\/title","value":"getMessageStatisticsSizeWithStart:end:direction:type:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatisticsSize(withStart:end:direction:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:end:direction:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager\/title","value":"IAgoraChatStatisticsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsType\/title","value":"AgoraChatMessageStatisticsType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsType\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection\/title","value":"AgoraChatMessageStatisticsDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}