{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emDidRecivePushSilentMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messageDic"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emdidrecivepushsilentmessage(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emdidrecivepushsilentmessage(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emDidRecivePushSilentMessage(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method is called when the application  received easemob push silent message"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"emDidRecivePushSilentMessage:"}],"role":"symbol","title":"emDidRecivePushSilentMessage(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emDidRecivePushSilentMessage"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatLocalNotificationDelegate(im)emDidRecivePushSilentMessage:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emDidRecivePushSilentMessage(_:)":{"navigatorTitle":[{"kind":"identifier","text":"emDidRecivePushSilentMessage:"}],"role":"symbol","title":"emDidRecivePushSilentMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emDidRecivePushSilentMessage"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"This method is called when the application  received easemob push silent message"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emDidRecivePushSilentMessage(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emdidrecivepushsilentmessage(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate":{"role":"symbol","title":"AgoraChatLocalNotificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"emDidRecivePushSilentMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emDidRecivePushSilentMessage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"emDidRecivePushSilentMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageDic"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emDidRecivePushSilentMessage(_:)\/title","value":"emDidRecivePushSilentMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emDidRecivePushSilentMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emDidRecivePushSilentMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/title","value":"AgoraChatLocalNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}