{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emGetNotificationMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState","preciseIdentifier":"c:@E@AgoraChatNotificationState","text":"AgoraChatNotificationState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emgetnotificationmessage(_:state:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emgetnotificationmessage(_:state:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emGetNotificationMessage(_:state:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Getting push messages can be implemented only with this delegate method to uniformly get notification messages"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"emGetNotificationMessage:state:"}],"role":"symbol","title":"emGetNotificationMessage(_:state:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emGetNotificationMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatNotificationState","preciseIdentifier":"c:@E@AgoraChatNotificationState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatLocalNotificationDelegate(im)emGetNotificationMessage:state:","modules":[{"name":"AgoraChat"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emGetNotificationMessage(_:state:)":{"role":"symbol","title":"emGetNotificationMessage(_:state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emGetNotificationMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatNotificationState","preciseIdentifier":"c:@E@AgoraChatNotificationState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Getting push messages can be implemented only with this delegate method to uniformly get notification messages"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emGetNotificationMessage(_:state:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emGetNotificationMessage:state:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emgetnotificationmessage(_:state:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatNotificationState":{"role":"symbol","title":"AgoraChatNotificationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatNotificationState"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatNotificationState"}],"url":"\/documentation\/agorachat\/agorachatnotificationstate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate":{"role":"symbol","title":"AgoraChatLocalNotificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"emGetNotificationMessage:state:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emGetNotificationMessage:state:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"emGetNotificationMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"notification"},{"kind":"text","text":" "},{"kind":"identifier","text":"state:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState","preciseIdentifier":"c:@E@AgoraChatNotificationState","text":"AgoraChatNotificationState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"state"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emGetNotificationMessage(_:state:)\/title","value":"emGetNotificationMessage:state:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emGetNotificationMessage(_:state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emGetNotificationMessage:state:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState\/title","value":"AgoraChatNotificationState"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState\/fragments","value":[{"kind":"identifier","text":"AgoraChatNotificationState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/title","value":"AgoraChatLocalNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}