{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emuserNotificationCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"center"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emusernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emusernotificationcenter(_:didreceive:withcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:didReceive:withCompletionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method will be called when user open application notification."},{"type":"text","text":" "},{"type":"text","text":"CompletionHandler must be called back"}],"kind":"symbol","metadata":{"modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"role":"symbol","title":"emuserNotificationCenter(_:didReceive:withCompletionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emuserNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatLocalNotificationDelegate(im)emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emuserNotificationCenter(_:didReceive:withCompletionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"role":"symbol","title":"emuserNotificationCenter(_:didReceive:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emuserNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method will be called when user open application notification."},{"type":"text","text":" "},{"type":"text","text":"CompletionHandler must be called back"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:didReceive:withCompletionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emusernotificationcenter(_:didreceive:withcompletionhandler:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate":{"role":"symbol","title":"AgoraChatLocalNotificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"emuserNotificationCenter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"center"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveNotificationResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"response"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/title","value":"AgoraChatLocalNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}