{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatclientdelegate\/userdidforbidbyserver()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatclientdelegate\/userdidforbidbyserver()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userDidForbidByServer()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The delegate method will be invoked when the User account is forbidden."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"title":"userDidForbidByServer()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatClientDelegate(im)userDidForbidByServer","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"userDidForbidByServer"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate":{"role":"symbol","title":"AgoraChatClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClientDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatClientDelegate"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/userDidForbidByServer()":{"role":"symbol","title":"userDidForbidByServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"The delegate method will be invoked when the User account is forbidden."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userDidForbidByServer()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidForbidByServer"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate\/userdidforbidbyserver()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userDidForbidByServer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidForbidByServer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate\/title","value":"AgoraChatClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userDidForbidByServer()\/title","value":"userDidForbidByServer"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userDidForbidByServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidForbidByServer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}