{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom","text":"AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAllMemberMuted"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomallmembermutechanged(_:isallmembermuted:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomallmembermutechanged(_:isallmembermuted:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether group members are all muted."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAllMemberMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatroomManagerDelegate(im)chatroomAllMemberMuteChanged:isAllMemberMuted:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"chatroomAllMemberMuteChanged:isAllMemberMuted:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate":{"role":"symbol","title":"AgoraChatroomManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom":{"role":"symbol","title":"AgoraChatroom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"}],"abstract":[{"type":"text","text":"The chat room object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroom"}],"url":"\/documentation\/agorachat\/agorachatroom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)":{"role":"symbol","title":"chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAllMemberMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Whether group members are all muted."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAllMemberMuteChanged:isAllMemberMuted:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomallmembermutechanged(_:isallmembermuted:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"chatroomAllMemberMuteChanged:isAllMemberMuted:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged:isAllMemberMuted:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom","text":"AgoraChatroom"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAllMemberMuted:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aMuted"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/title","value":"AgoraChatroomManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/title","value":"AgoraChatroom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/fragments","value":[{"kind":"identifier","text":"AgoraChatroom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAllMemberMuteChanged(_:isAllMemberMuted:)\/title","value":"chatroomAllMemberMuteChanged:isAllMemberMuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAllMemberMuteChanged(_:isAllMemberMuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged:isAllMemberMuted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}