{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom","text":"AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedAdmin"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomadminlistdidupdate(_:removedadmin:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomadminlistdidupdate(_:removedadmin:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:removedAdmin:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A user is removed from the admin list."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"chatroomAdminListDidUpdate(_:removedAdmin:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatroomManagerDelegate(im)chatroomAdminListDidUpdate:removedAdmin:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"chatroomAdminListDidUpdate:removedAdmin:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate":{"role":"symbol","title":"AgoraChatroomManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAdminListDidUpdate(_:removedAdmin:)":{"role":"symbol","title":"chatroomAdminListDidUpdate(_:removedAdmin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A user is removed from the admin list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:removedAdmin:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAdminListDidUpdate:removedAdmin:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomadminlistdidupdate(_:removedadmin:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom":{"role":"symbol","title":"AgoraChatroom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"}],"abstract":[{"type":"text","text":"The chat room object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroom"}],"url":"\/documentation\/agorachat\/agorachatroom"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"chatroomAdminListDidUpdate:removedAdmin:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAdminListDidUpdate:removedAdmin:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"chatroomAdminListDidUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom","text":"AgoraChatroom"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":" "},{"kind":"identifier","text":"removedAdmin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aAdmin"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/title","value":"AgoraChatroomManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAdminListDidUpdate(_:removedAdmin:)\/title","value":"chatroomAdminListDidUpdate:removedAdmin:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAdminListDidUpdate(_:removedAdmin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAdminListDidUpdate:removedAdmin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/title","value":"AgoraChatroom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/fragments","value":[{"kind":"identifier","text":"AgoraChatroom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}