{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom","text":"AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated, please use  {@link userDidJoinChatroom:user:}  instead."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate\/didreceiveuserjoinedchatroom(_:username:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate\/didreceiveuserjoinedchatroom(_:username:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserJoinedChatroom(_:username:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when a user joins a chat room"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didReceiveUserJoinedChatroom:username:"}],"role":"symbol","title":"didReceiveUserJoinedChatroom(_:username:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatroomManagerDelegate(im)didReceiveUserJoinedChatroom:username:","modules":[{"name":"AgoraChat"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use -userDidJoinChatroom:user: instead"}]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate":{"role":"symbol","title":"AgoraChatroomManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/didReceiveUserJoinedChatroom(_:username:)":{"deprecated":true,"role":"symbol","title":"didReceiveUserJoinedChatroom(_:username:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user joins a chat room"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserJoinedChatroom(_:username:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveUserJoinedChatroom:username:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/didreceiveuserjoinedchatroom(_:username:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom":{"role":"symbol","title":"AgoraChatroom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"}],"abstract":[{"type":"text","text":"The chat room object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroom"}],"url":"\/documentation\/agorachat\/agorachatroom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didReceiveUserJoinedChatroom:username:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom:username:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom","text":"AgoraChatroom"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aChatroom"},{"kind":"text","text":" "},{"kind":"identifier","text":"username:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/title","value":"AgoraChatroomManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveUserJoinedChatroom(_:username:)\/title","value":"didReceiveUserJoinedChatroom:username:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveUserJoinedChatroom(_:username:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom:username:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/title","value":"AgoraChatroom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/fragments","value":[{"kind":"identifier","text":"AgoraChatroom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}