{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupBlock"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBlock","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If user A removes other users from a chat group on DeviceA1, this event is triggered on DeviceA2."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupBlock"}],"title":"AgoraChatMultiDevicesEvent.groupBlock","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMultiDevicesEvent@AgoraChatMultiDevicesEventGroupBlock","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupBlock":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupBlock","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupBlock"}],"abstract":[{"type":"text","text":"If user A removes other users from a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupblock"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesEventGroupBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupBlock\/title","value":"AgoraChatMultiDevicesEventGroupBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupBlock\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}