{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAllow"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupallow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupallow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllow","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If user A is added to the blocklist on DeviceA1, this event is triggered on DeviceA2."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAllow"}],"title":"AgoraChatMultiDevicesEvent.groupAllow","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMultiDevicesEvent@AgoraChatMultiDevicesEventGroupAllow","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAllow":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAllow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAllow"}],"abstract":[{"type":"text","text":"If user A is added to the blocklist on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupallow"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesEventGroupAllow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAllow\/title","value":"AgoraChatMultiDevicesEventGroupAllow"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAllow\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}