{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupKick"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupkick"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent\/groupkick"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupKick","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If user A declines another user’s group invitation on DeviceA1, this event is triggered on DeviceA2."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupKick"}],"title":"AgoraChatMultiDevicesEvent.groupKick","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMultiDevicesEvent@AgoraChatMultiDevicesEventGroupKick","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupKick":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupKick","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupKick"}],"abstract":[{"type":"text","text":"If user A declines another user’s group invitation on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupKick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupkick"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesEventGroupKick"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupKick\/title","value":"AgoraChatMultiDevicesEventGroupKick"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupKick\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}