{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aApplication"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatclient\/applicationwillenterforeground(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatclient\/applicationwillenterforeground(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient\/applicationWillEnterForeground(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reconnect to the server when your app returns to foreground mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"title":"applicationWillEnterForeground(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChatClient(im)applicationWillEnterForeground:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClient/applicationWillEnterForeground(_:)":{"role":"symbol","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reconnect to the server when your app returns to foreground mode."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient\/applicationWillEnterForeground(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"url":"\/documentation\/agorachat\/agorachatclient\/applicationwillenterforeground(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClient":{"role":"symbol","title":"AgoraChatClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClient"}],"abstract":[{"type":"text","text":"The AgoraChatClient, which is the entry point of the Chat SDK. You can log in, log out, and access other functionalities such as group and chatroom with this class."},{"type":"text","text":" "},{"type":"text","text":"[AgoraChatClient sharedClient].groupManager;"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatClient"}],"url":"\/documentation\/agorachat\/agorachatclient"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"applicationWillEnterForeground:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aApplication"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient~1applicationWillEnterForeground(_:)\/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient~1applicationWillEnterForeground(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillEnterForeground:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient\/title","value":"AgoraChatClient"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient\/fragments","value":[{"kind":"identifier","text":"AgoraChatClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}