{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeLog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLogDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLogDelegate","text":"AgoraChatLogDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatclient\/removelog(delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatclient\/removelog(delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient\/removeLog(delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Remove the log callback delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeLog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatLogDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLogDelegate"},{"kind":"text","text":")"}],"title":"removeLog(delegate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChatClient(im)removeLogDelegate:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"removeLogDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClient/removeLog(delegate:)":{"role":"symbol","title":"removeLog(delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeLog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatLogDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLogDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove the log callback delegate."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient\/removeLog(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeLogDelegate:"}],"url":"\/documentation\/agorachat\/agorachatclient\/removelog(delegate:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClient":{"role":"symbol","title":"AgoraChatClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClient"}],"abstract":[{"type":"text","text":"The AgoraChatClient, which is the entry point of the Chat SDK. You can log in, log out, and access other functionalities such as group and chatroom with this class."},{"type":"text","text":" "},{"type":"text","text":"[AgoraChatClient sharedClient].groupManager;"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatClient"}],"url":"\/documentation\/agorachat\/agorachatclient"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLogDelegate":{"role":"symbol","title":"AgoraChatLogDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLogDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol of log callback."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLogDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLogDelegate"}],"url":"\/documentation\/agorachat\/agorachatlogdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeLogDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeLogDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeLogDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraChatLogDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraChatLogDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient~1removeLog(delegate:)\/title","value":"removeLogDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient~1removeLog(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeLogDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient\/title","value":"AgoraChatClient"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClient\/fragments","value":[{"kind":"identifier","text":"AgoraChatClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLogDelegate\/title","value":"AgoraChatLogDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLogDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatLogDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}