{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDownloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus","text":"AgoraChatDownloadStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnaildownloadstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnaildownloadstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDownloadStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The download status of the thumbnail."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDownloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"title":"thumbnailDownloadStatus","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatImageMessageBody(py)thumbnailDownloadStatus","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"thumbnailDownloadStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody":{"role":"symbol","title":"AgoraChatImageMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatImageMessageBody"}],"abstract":[{"type":"text","text":"The image message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatDownloadStatus":{"role":"symbol","title":"AgoraChatDownloadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The status types for downloading the file message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatdownloadstatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailDownloadStatus":{"role":"symbol","title":"thumbnailDownloadStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDownloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The download status of the thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnaildownloadstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"thumbnailDownloadStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"thumbnailDownloadStatus"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus","text":"AgoraChatDownloadStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDownloadStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody\/title","value":"AgoraChatImageMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/title","value":"AgoraChatDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailDownloadStatus\/title","value":"thumbnailDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailDownloadStatus\/fragments","value":[{"kind":"identifier","text":"thumbnailDownloadStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}