{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarURL"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatuserinfotype\/avatarurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatuserinfotype\/avatarurl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType\/avatarURL","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user nickname."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarURL"}],"title":"AgoraChatUserInfoType.avatarURL","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatUserInfoType@AgoraChatUserInfoTypeAvatarURL","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoTypeAvatarURL"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatUserInfoType/avatarURL":{"role":"symbol","title":"AgoraChatUserInfoType.avatarURL","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarURL"}],"abstract":[{"type":"text","text":"The user nickname."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType\/avatarURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoTypeAvatarURL"}],"url":"\/documentation\/agorachat\/agorachatuserinfotype\/avatarurl"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatUserInfoType":{"role":"symbol","title":"AgoraChatUserInfoType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatUserInfoType"}],"abstract":[{"type":"text","text":"The user information type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoType"}],"url":"\/documentation\/agorachat\/agorachatuserinfotype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatUserInfoTypeAvatarURL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoTypeAvatarURL"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatUserInfoTypeAvatarURL"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType~1avatarURL\/title","value":"AgoraChatUserInfoTypeAvatarURL"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType~1avatarURL\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoTypeAvatarURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType\/title","value":"AgoraChatUserInfoType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}