{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatuserinfotype\/phone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatuserinfotype\/phone"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType\/phone","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user avatar address."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"}],"title":"AgoraChatUserInfoType.phone","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatUserInfoType@AgoraChatUserInfoTypePhone","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoTypePhone"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatUserInfoType":{"role":"symbol","title":"AgoraChatUserInfoType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatUserInfoType"}],"abstract":[{"type":"text","text":"The user information type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoType"}],"url":"\/documentation\/agorachat\/agorachatuserinfotype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatUserInfoType/phone":{"role":"symbol","title":"AgoraChatUserInfoType.phone","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"}],"abstract":[{"type":"text","text":"The user avatar address."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType\/phone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoTypePhone"}],"url":"\/documentation\/agorachat\/agorachatuserinfotype\/phone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatUserInfoTypePhone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoTypePhone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatUserInfoTypePhone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType\/title","value":"AgoraChatUserInfoType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType~1phone\/title","value":"AgoraChatUserInfoTypePhone"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType~1phone\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoTypePhone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}