{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileUploadFailed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/fileuploadfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/fileuploadfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/fileUploadFailed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The file is invalid."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileUploadFailed"}],"title":"AgoraChatErrorCode.fileUploadFailed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatErrorCode@AgoraChatErrorFileUploadFailed","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorFileUploadFailed"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode/fileUploadFailed":{"role":"symbol","title":"AgoraChatErrorCode.fileUploadFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileUploadFailed"}],"abstract":[{"type":"text","text":"The file is invalid."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/fileUploadFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorFileUploadFailed"}],"url":"\/documentation\/agorachat\/agorachaterrorcode\/fileuploadfailed"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode":{"role":"symbol","title":"AgoraChatErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorCode"}],"url":"\/documentation\/agorachat\/agorachaterrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatErrorFileUploadFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorFileUploadFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatErrorFileUploadFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1fileUploadFailed\/title","value":"AgoraChatErrorFileUploadFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1fileUploadFailed\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorFileUploadFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/title","value":"AgoraChatErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}