{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialSuccess"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/partialsuccess"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/partialsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/partialSuccess","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Report push action failed"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialSuccess"}],"title":"AgoraChatErrorCode.partialSuccess","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatErrorCode@AgoraChatErrorPartialSuccess","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorPartialSuccess"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode/partialSuccess":{"role":"symbol","title":"AgoraChatErrorCode.partialSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialSuccess"}],"abstract":[{"type":"text","text":"Report push action failed"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/partialSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorPartialSuccess"}],"url":"\/documentation\/agorachat\/agorachaterrorcode\/partialsuccess"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode":{"role":"symbol","title":"AgoraChatErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorCode"}],"url":"\/documentation\/agorachat\/agorachaterrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatErrorPartialSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorPartialSuccess"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatErrorPartialSuccess"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1partialSuccess\/title","value":"AgoraChatErrorPartialSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1partialSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorPartialSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/title","value":"AgoraChatErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}