{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCountExceed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/usercountexceed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/usercountexceed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/userCountExceed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The chatroom does not exist."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCountExceed"}],"title":"AgoraChatErrorCode.userCountExceed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatErrorCode@AgoraChatErrorUserCountExceed","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorUserCountExceed"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode":{"role":"symbol","title":"AgoraChatErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorCode"}],"url":"\/documentation\/agorachat\/agorachaterrorcode"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode/userCountExceed":{"role":"symbol","title":"AgoraChatErrorCode.userCountExceed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCountExceed"}],"abstract":[{"type":"text","text":"The chatroom does not exist."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/userCountExceed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorUserCountExceed"}],"url":"\/documentation\/agorachat\/agorachaterrorcode\/usercountexceed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatErrorUserCountExceed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorUserCountExceed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatErrorUserCountExceed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/title","value":"AgoraChatErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1userCountExceed\/title","value":"AgoraChatErrorUserCountExceed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1userCountExceed\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorUserCountExceed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}