{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"andCursor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCusror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatcursorresult\/init(list:andcursor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatcursorresult\/init(list:andcursor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCursorResult\/init(list:andCursor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the result instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"andCursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(list:andCursor:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)AgoraChatCursorResult(cm)cursorResultWithList:andCursor:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"cursorResultWithList:andCursor:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCursorResult"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatCursorResult/init(list:andCursor:)":{"role":"symbol","title":"init(list:andCursor:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"andCursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Gets the result instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCursorResult\/init(list:andCursor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cursorResultWithList:andCursor:"}],"url":"\/documentation\/agorachat\/agorachatcursorresult\/init(list:andcursor:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatCursorResult":{"role":"symbol","title":"AgoraChatCursorResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatCursorResult"}],"abstract":[{"type":"text","text":"The EmCursorResult interface, which displays query results such as conversations and group chats."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCursorResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatCursorResult"}],"url":"\/documentation\/agorachat\/agorachatcursorresult"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"cursorResultWithList:andCursor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cursorResultWithList:andCursor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"cursorResultWithList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aList"},{"kind":"text","text":" "},{"kind":"identifier","text":"andCursor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aCusror"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCursorResult~1init(list:andCursor:)\/title","value":"cursorResultWithList:andCursor:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCursorResult~1init(list:andCursor:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cursorResultWithList:andCursor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCursorResult\/title","value":"AgoraChatCursorResult"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCursorResult\/fragments","value":[{"kind":"identifier","text":"AgoraChatCursorResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}