{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparamtype\/remindtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparamtype\/remindtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType\/remindType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"}],"title":"AgoraChatSilentModeParamType.remindType","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatSilentModeParamType@AgoraChatSilentModeParamTypeRemindType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParamTypeRemindType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParamType/remindType":{"role":"symbol","title":"AgoraChatSilentModeParamType.remindType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType\/remindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParamTypeRemindType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparamtype\/remindtype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParamType":{"role":"symbol","title":"AgoraChatSilentModeParamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParamType"}],"abstract":[{"type":"text","text":"Parameter type to no-disturbing mode."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParamType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparamtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatSilentModeParamTypeRemindType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParamTypeRemindType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatSilentModeParamTypeRemindType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType~1remindType\/title","value":"AgoraChatSilentModeParamTypeRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType~1remindType\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParamTypeRemindType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType\/title","value":"AgoraChatSilentModeParamType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParamType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}