{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicOpenJoin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupstyle\/publicopenjoin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupstyle\/publicopenjoin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicOpenJoin","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"!  A public group, where the group owner can invite users to user. Users can send a join request and join the group if the owner approves it."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicOpenJoin"}],"title":"AgoraChatGroupStyle.publicOpenJoin","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatGroupStyle@AgoraChatGroupStylePublicOpenJoin","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle":{"role":"symbol","title":"AgoraChatGroupStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupStyle"}],"abstract":[{"type":"text","text":"The group type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStyle"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/publicOpenJoin":{"role":"symbol","title":"AgoraChatGroupStyle.publicOpenJoin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicOpenJoin"}],"abstract":[{"type":"text","text":"!  A public group, where the group owner can invite users to user. Users can send a join request and join the group if the owner approves it."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicOpenJoin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle\/publicopenjoin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupStylePublicOpenJoin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle\/title","value":"AgoraChatGroupStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicOpenJoin\/title","value":"AgoraChatGroupStylePublicOpenJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicOpenJoin\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}