{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicJoinNeedApproval"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupstyle\/publicjoinneedapproval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupstyle\/publicjoinneedapproval"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicJoinNeedApproval","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"!  A private group, where all the group members including the group owner, group manager, and other group members can invite users to join."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicJoinNeedApproval"}],"title":"AgoraChatGroupStyle.publicJoinNeedApproval","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatGroupStyle@AgoraChatGroupStylePublicJoinNeedApproval","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/publicJoinNeedApproval":{"role":"symbol","title":"AgoraChatGroupStyle.publicJoinNeedApproval","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicJoinNeedApproval"}],"abstract":[{"type":"text","text":"!  A private group, where all the group members including the group owner, group manager, and other group members can invite users to join."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicJoinNeedApproval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle\/publicjoinneedapproval"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle":{"role":"symbol","title":"AgoraChatGroupStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupStyle"}],"abstract":[{"type":"text","text":"The group type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStyle"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupStylePublicJoinNeedApproval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicJoinNeedApproval\/title","value":"AgoraChatGroupStylePublicJoinNeedApproval"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicJoinNeedApproval\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle\/title","value":"AgoraChatGroupStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}