{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus","text":"AgoraChatDownloadStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatfilemessagebody\/downloadstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatfilemessagebody\/downloadstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody\/downloadStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The downloading status of the attachment."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"title":"downloadStatus","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatFileMessageBody(py)downloadStatus","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"downloadStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatDownloadStatus":{"role":"symbol","title":"AgoraChatDownloadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The status types for downloading the file message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatdownloadstatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatFileMessageBody":{"role":"symbol","title":"AgoraChatFileMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatFileMessageBody"}],"abstract":[{"type":"text","text":"The file message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatFileMessageBody"}],"url":"\/documentation\/agorachat\/agorachatfilemessagebody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatFileMessageBody/downloadStatus":{"role":"symbol","title":"downloadStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The downloading status of the attachment."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody\/downloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadStatus"}],"url":"\/documentation\/agorachat\/agorachatfilemessagebody\/downloadstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"downloadStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"downloadStatus"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus","text":"AgoraChatDownloadStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/title","value":"AgoraChatDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody\/title","value":"AgoraChatFileMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatFileMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody~1downloadStatus\/title","value":"downloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody~1downloadStatus\/fragments","value":[{"kind":"identifier","text":"downloadStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}