{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageAckHasChanged"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessageackhaschanged()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessageackhaschanged()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageAckHasChanged()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the current group read messages count changed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageAckHasChanged"},{"kind":"text","text":"()"}],"title":"groupMessageAckHasChanged()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatManagerDelegate(im)groupMessageAckHasChanged","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"groupMessageAckHasChanged"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/groupMessageAckHasChanged()":{"role":"symbol","title":"groupMessageAckHasChanged()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageAckHasChanged"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Occurs when the current group read messages count changed."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageAckHasChanged()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupMessageAckHasChanged"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessageackhaschanged()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate":{"role":"symbol","title":"AgoraChatManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"abstract":[{"type":"text","text":"The chat related callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupMessageAckHasChanged"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMessageAckHasChanged"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupMessageAckHasChanged"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageAckHasChanged()\/title","value":"groupMessageAckHasChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageAckHasChanged()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMessageAckHasChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate\/title","value":"AgoraChatManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}