{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageDidRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupAcks"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aGroupAcks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupMessageAck","preciseIdentifier":"c:objc(cs)AgoraChatGroupMessageAck","text":"AgoraChatGroupMessageAck"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessagedidread(_:groupacks:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessagedidread(_:groupacks:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageDidRead(_:groupAcks:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the SDK receives read receipts for group messages."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"groupMessageDidRead:groupAcks:"}],"role":"symbol","title":"groupMessageDidRead(_:groupAcks:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageDidRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupAcks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatGroupMessageAck","preciseIdentifier":"c:objc(cs)AgoraChatGroupMessageAck"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatManagerDelegate(im)groupMessageDidRead:groupAcks:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/groupMessageDidRead(_:groupAcks:)":{"navigatorTitle":[{"kind":"identifier","text":"groupMessageDidRead:groupAcks:"}],"role":"symbol","title":"groupMessageDidRead(_:groupAcks:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageDidRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupAcks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatGroupMessageAck","preciseIdentifier":"c:objc(cs)AgoraChatGroupMessageAck"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the SDK receives read receipts for group messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageDidRead(_:groupAcks:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessagedidread(_:groupacks:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage":{"role":"symbol","title":"AgoraChatMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"abstract":[{"type":"text","text":"The chat message class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessage"}],"url":"\/documentation\/agorachat\/agorachatmessage"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupMessageAck":{"role":"symbol","title":"AgoraChatGroupMessageAck","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupMessageAck"}],"abstract":[{"type":"text","text":"The group message receipt."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupMessageAck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupMessageAck"}],"url":"\/documentation\/agorachat\/agorachatgroupmessageack"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate":{"role":"symbol","title":"AgoraChatManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"abstract":[{"type":"text","text":"The chat related callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupMessageDidRead:groupAcks:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMessageDidRead:groupAcks:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupMessageDidRead:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAcks:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatGroupMessageAck *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aGroupAcks"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageDidRead(_:groupAcks:)\/title","value":"groupMessageDidRead:groupAcks:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageDidRead(_:groupAcks:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMessageDidRead:groupAcks:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/title","value":"AgoraChatMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupMessageAck\/title","value":"AgoraChatGroupMessageAck"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupMessageAck\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupMessageAck"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate\/title","value":"AgoraChatManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}