{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatTranslationResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachattranslationresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachattranslationresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message translate info"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatTranslationResult"}],"title":"AgoraChatTranslationResult","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatTranslationResult","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatTranslationResult"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/msgId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/showTranslation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/translateTimes","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/translations"]}],"references":{"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatTranslationResult/showTranslation":{"role":"symbol","title":"showTranslation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showTranslation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Weather to show the translations"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/showTranslation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showTranslation"}],"url":"\/documentation\/agorachat\/agorachattranslationresult\/showtranslation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatTranslationResult/translations":{"role":"symbol","title":"translations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"translations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The translation result content"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/translations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translations"}],"url":"\/documentation\/agorachat\/agorachattranslationresult\/translations"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatTranslationResult/msgId":{"role":"symbol","title":"msgId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"msgId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The Translation’s messageId"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/msgId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"msgId"}],"url":"\/documentation\/agorachat\/agorachattranslationresult\/msgid"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatTranslationResult/translateTimes":{"role":"symbol","title":"translateTimes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"translateTimes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"How many tims the message have been translated"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/translateTimes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translateTimes"}],"url":"\/documentation\/agorachat\/agorachattranslationresult\/translatetimes"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatTranslationResult":{"role":"symbol","title":"AgoraChatTranslationResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatTranslationResult"}],"abstract":[{"type":"text","text":"The message translate info"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatTranslationResult"}],"url":"\/documentation\/agorachat\/agorachattranslationresult"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatTranslationResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatTranslationResult"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatTranslationResult"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/msgId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/showTranslation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/translateTimes","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatTranslationResult\/translations"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatTranslationResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1showTranslation\/title","value":"showTranslation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1showTranslation\/fragments","value":[{"kind":"identifier","text":"showTranslation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1translations\/title","value":"translations"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1translations\/fragments","value":[{"kind":"identifier","text":"translations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1msgId\/title","value":"msgId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1msgId\/fragments","value":[{"kind":"identifier","text":"msgId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1translateTimes\/title","value":"translateTimes"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult~1translateTimes\/fragments","value":[{"kind":"identifier","text":"translateTimes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult\/title","value":"AgoraChatTranslationResult"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatTranslationResult\/fragments","value":[{"kind":"identifier","text":"AgoraChatTranslationResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}