{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageReaction"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagereaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagereaction"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message reaction object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageReaction"}],"title":"AgoraChatMessageReaction","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatMessageReaction","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageReaction"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/count","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/isAddedBySelf","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/reaction","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/userList"]}],"references":{"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageReaction/count":{"role":"symbol","title":"count","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The count of the users who added this Reaction."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/count","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"count"}],"url":"\/documentation\/agorachat\/agorachatmessagereaction\/count"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageReaction/isAddedBySelf":{"role":"symbol","title":"isAddedBySelf","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAddedBySelf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the current user added this Reaction."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/isAddedBySelf","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAddedBySelf"}],"url":"\/documentation\/agorachat\/agorachatmessagereaction\/isaddedbyself"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageReaction/userList":{"role":"symbol","title":"userList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The list of users that added this Reaction."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/userList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userList"}],"url":"\/documentation\/agorachat\/agorachatmessagereaction\/userlist"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageReaction/reaction":{"role":"symbol","title":"reaction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The Reaction content."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/reaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reaction"}],"url":"\/documentation\/agorachat\/agorachatmessagereaction\/reaction"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageReaction":{"role":"symbol","title":"AgoraChatMessageReaction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageReaction"}],"abstract":[{"type":"text","text":"The message reaction object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageReaction"}],"url":"\/documentation\/agorachat\/agorachatmessagereaction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageReaction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageReaction"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMessageReaction"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/count","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/isAddedBySelf","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/reaction","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction\/userList"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageReaction"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1count\/title","value":"count"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1count\/fragments","value":[{"kind":"identifier","text":"count"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1isAddedBySelf\/title","value":"isAddedBySelf"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1isAddedBySelf\/fragments","value":[{"kind":"identifier","text":"isAddedBySelf"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1userList\/title","value":"userList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1userList\/fragments","value":[{"kind":"identifier","text":"userList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1reaction\/title","value":"reaction"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction~1reaction\/fragments","value":[{"kind":"identifier","text":"reaction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction\/title","value":"AgoraChatMessageReaction"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageReaction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}