{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatVideoMessageBody"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatvideomessagebody"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatvideomessagebody"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video message body."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatVideoMessageBody"}],"title":"AgoraChatVideoMessageBody","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatVideoMessageBody","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatVideoMessageBody"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/duration","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailDownloadStatus","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailLocalPath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailRemotePath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailSecretKey","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailSize"]}],"references":{"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody/thumbnailSize":{"role":"symbol","title":"thumbnailSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of the video thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailSize"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody\/thumbnailsize"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody/thumbnailDownloadStatus":{"role":"symbol","title":"thumbnailDownloadStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDownloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The download status of the thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody\/thumbnaildownloadstatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody/thumbnailLocalPath":{"role":"symbol","title":"thumbnailLocalPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailLocalPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The local path of thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailLocalPath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailLocalPath"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody\/thumbnaillocalpath"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody/thumbnailRemotePath":{"role":"symbol","title":"thumbnailRemotePath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailRemotePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The URL of the thumbnail on the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailRemotePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailRemotePath"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody\/thumbnailremotepath"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody/thumbnailSecretKey":{"role":"symbol","title":"thumbnailSecretKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSecretKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The secret key of the thumbnail, which is required for verification when downloading the thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailSecretKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailSecretKey"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody\/thumbnailsecretkey"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody":{"role":"symbol","title":"AgoraChatVideoMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatVideoMessageBody"}],"abstract":[{"type":"text","text":"The video message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatVideoMessageBody"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatVideoMessageBody/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The video duration, in seconds."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/agorachat\/agorachatvideomessagebody\/duration"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatFileMessageBody":{"role":"symbol","title":"AgoraChatFileMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatFileMessageBody"}],"abstract":[{"type":"text","text":"The file message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatFileMessageBody"}],"url":"\/documentation\/agorachat\/agorachatfilemessagebody"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatVideoMessageBody"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatVideoMessageBody"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatVideoMessageBody"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/duration","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailDownloadStatus","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailLocalPath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailRemotePath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailSecretKey","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatVideoMessageBody\/thumbnailSize"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatVideoMessageBody"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatFileMessageBody","text":"AgoraChatFileMessageBody"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailSize\/title","value":"thumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailSize\/fragments","value":[{"kind":"identifier","text":"thumbnailSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailDownloadStatus\/title","value":"thumbnailDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailDownloadStatus\/fragments","value":[{"kind":"identifier","text":"thumbnailDownloadStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailLocalPath\/title","value":"thumbnailLocalPath"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailLocalPath\/fragments","value":[{"kind":"identifier","text":"thumbnailLocalPath"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailRemotePath\/title","value":"thumbnailRemotePath"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailRemotePath\/fragments","value":[{"kind":"identifier","text":"thumbnailRemotePath"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailSecretKey\/title","value":"thumbnailSecretKey"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1thumbnailSecretKey\/fragments","value":[{"kind":"identifier","text":"thumbnailSecretKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody\/title","value":"AgoraChatVideoMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatVideoMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatVideoMessageBody~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody\/title","value":"AgoraChatFileMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatFileMessageBody"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}