{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A class that manages the chat message notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"title":"AgoraChatLocalNotificationManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatLocalNotificationManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/launch(with:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:willPresent:withCompletionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/shared()"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager/shared()":{"role":"symbol","title":"shared()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Create an instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/shared()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedManager"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager\/shared()"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager/launch(with:)":{"role":"symbol","title":"launch(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatLocalNotificationDelegate","preciseIdentifier":"c:objc(pl)AgoraChatLocalNotificationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables the chat message notification service."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/launch(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"launchWithDelegate:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager\/launch(with:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"role":"symbol","title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"User should call this method in the implementation of  UNUserNotificationCenterDelegate if they have override UNUserNotificationCenterDelegate  in-app."},{"type":"text","text":" "},{"type":"text","text":"If you don’t want the SDK to execute the callback, don’t pass the completionHandler"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:willPresent:withCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager\/usernotificationcenter(_:willpresent:withcompletionhandler:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"role":"symbol","title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When the system receives a push notification, the callback method is triggered when the notification bar is clicked."},{"type":"text","text":" "},{"type":"text","text":"User should call this method in the implementation of UNUserNotificationCenterDelegate if they have override UNUserNotificationCenterDelegate in-app."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:didReceive:withCompletionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager\/usernotificationcenter(_:didreceive:withcompletionhandler:)"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationManager":{"role":"symbol","title":"AgoraChatLocalNotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"abstract":[{"type":"text","text":"A class that manages the chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationmanager"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatLocalNotificationManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/launch(with:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/userNotificationCenter(_:willPresent:withCompletionHandler:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationManager\/shared()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1shared()\/title","value":"sharedManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1shared()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1launch(with:)\/title","value":"launchWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1launch(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"launchWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/title","value":"userNotificationCenter:willPresentNotification:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1userNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:willPresentNotification:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager~1userNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager\/title","value":"AgoraChatLocalNotificationManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationManager\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}