{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpushoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpushoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options for Apple Push Notification service (APNs)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushOptions"}],"title":"AgoraChatPushOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatPushOptions","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayStyle","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/isNoDisturbEnable","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/noDisturbingEndH","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/noDisturbingStartH","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeEnabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeEnd","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeStart"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/silentModeEnd":{"deprecated":true,"role":"symbol","title":"silentModeEnd","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentModeEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The no-disturbing mode end time (in hour)."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use AgoraChatSilentModeResult property silentModeEndTime instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeEnd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silentModeEnd"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/silentmodeend"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/displayStyle":{"role":"symbol","title":"displayStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle"}],"abstract":[{"type":"text","text":"The display style of the notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayStyle"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/displaystyle"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/noDisturbingStartH":{"deprecated":true,"role":"symbol","title":"noDisturbingStartH","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDisturbingStartH"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"No disturbing mode start time (in hour)"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/noDisturbingStartH","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"noDisturbingStartH"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/nodisturbingstarth"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/noDisturbingEndH":{"deprecated":true,"role":"symbol","title":"noDisturbingEndH","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDisturbingEndH"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"No disturbing mode end time (in hour)"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/noDisturbingEndH","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"noDisturbingEndH"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/nodisturbingendh"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/isNoDisturbEnable":{"deprecated":true,"role":"symbol","title":"isNoDisturbEnable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNoDisturbEnable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether enable messages do not disturb"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/isNoDisturbEnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isNoDisturbEnable"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/isnodisturbenable"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/displayName":{"role":"symbol","title":"displayName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user’s nickname to be displayed in the notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayName"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/displayname"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/silentModeEnabled":{"deprecated":true,"role":"symbol","title":"silentModeEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentModeEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable the Do Not Disturb mode. expireTimestamp"},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use AgoraChatSilentModeResult property expireTimestamp and silentModeTime determine whether to enable"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silentModeEnabled"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/silentmodeenabled"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions":{"role":"symbol","title":"AgoraChatPushOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushOptions"}],"abstract":[{"type":"text","text":"The options for Apple Push Notification service (APNs)."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushOptions"}],"url":"\/documentation\/agorachat\/agorachatpushoptions"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushOptions/silentModeStart":{"deprecated":true,"role":"symbol","title":"silentModeStart","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentModeStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The no-disturbing mode start time (in hour)."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use AgoraChatSilentModeResult property silentModeStartTime instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeStart","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silentModeStart"}],"url":"\/documentation\/agorachat\/agorachatpushoptions\/silentmodestart"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatPushOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatPushOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/displayStyle","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/isNoDisturbEnable","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/noDisturbingEndH","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/noDisturbingStartH","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeEnabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeEnd","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushOptions\/silentModeStart"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1silentModeEnd\/title","value":"silentModeEnd"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1silentModeEnd\/fragments","value":[{"kind":"identifier","text":"silentModeEnd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1displayStyle\/title","value":"displayStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1displayStyle\/fragments","value":[{"kind":"identifier","text":"displayStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1noDisturbingStartH\/title","value":"noDisturbingStartH"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1noDisturbingStartH\/fragments","value":[{"kind":"identifier","text":"noDisturbingStartH"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1noDisturbingEndH\/title","value":"noDisturbingEndH"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1noDisturbingEndH\/fragments","value":[{"kind":"identifier","text":"noDisturbingEndH"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1isNoDisturbEnable\/title","value":"isNoDisturbEnable"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1isNoDisturbEnable\/fragments","value":[{"kind":"identifier","text":"isNoDisturbEnable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1displayName\/title","value":"displayName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1displayName\/fragments","value":[{"kind":"identifier","text":"displayName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1silentModeEnabled\/title","value":"silentModeEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1silentModeEnabled\/fragments","value":[{"kind":"identifier","text":"silentModeEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions\/title","value":"AgoraChatPushOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1silentModeStart\/title","value":"silentModeStart"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushOptions~1silentModeStart\/fragments","value":[{"kind":"identifier","text":"silentModeStart"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}