{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocalnotificationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The callbacks of chat message notification."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"title":"AgoraChatLocalNotificationDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatLocalNotificationDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emDidRecivePushSilentMessage(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emGetNotificationMessage(_:state:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:openSettingsFor:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:willPresent:withCompletionHandler:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emGetNotificationMessage(_:state:)":{"role":"symbol","title":"emGetNotificationMessage(_:state:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emGetNotificationMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatNotificationState","preciseIdentifier":"c:@E@AgoraChatNotificationState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Getting push messages can be implemented only with this delegate method to uniformly get notification messages"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emGetNotificationMessage(_:state:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emGetNotificationMessage:state:"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emgetnotificationmessage(_:state:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate":{"role":"symbol","title":"AgoraChatLocalNotificationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chat message notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}],"url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emDidRecivePushSilentMessage(_:)":{"navigatorTitle":[{"kind":"identifier","text":"emDidRecivePushSilentMessage:"}],"role":"symbol","title":"emDidRecivePushSilentMessage(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emDidRecivePushSilentMessage"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"This method is called when the application  received easemob push silent message"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emDidRecivePushSilentMessage(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emdidrecivepushsilentmessage(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emuserNotificationCenter(_:didReceive:withCompletionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}],"role":"symbol","title":"emuserNotificationCenter(_:didReceive:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emuserNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationResponse","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method will be called when user open application notification."},{"type":"text","text":" "},{"type":"text","text":"CompletionHandler must be called back"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:didReceive:withCompletionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emusernotificationcenter(_:didreceive:withcompletionhandler:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emuserNotificationCenter(_:willPresent:withCompletionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"emuserNotificationCenter:willPresentNotification:withCompletionHandler:"}],"role":"symbol","title":"emuserNotificationCenter(_:willPresent:withCompletionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emuserNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationPresentationOptions","preciseIdentifier":"c:@E@UNNotificationPresentationOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method will be called  when  application receives  notification in the foreground."},{"type":"text","text":" "},{"type":"text","text":"By completionHandle (UNNotificationPresentationOptions options) callback display style, must be the callback."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:willPresent:withCompletionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emusernotificationcenter(_:willpresent:withcompletionhandler:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocalNotificationDelegate/emuserNotificationCenter(_:openSettingsFor:)":{"navigatorTitle":[{"kind":"identifier","text":"emuserNotificationCenter:openSettingsForNotification:"}],"role":"symbol","title":"emuserNotificationCenter(_:openSettingsFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"emuserNotificationCenter"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNUserNotificationCenter","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"openSettingsFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotification","preciseIdentifier":"c:objc(cs)UNNotification"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method will be called on the delegate when the application is launched in response to the user’s request to view in-app notification settings"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:openSettingsFor:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatlocalnotificationdelegate\/emusernotificationcenter(_:opensettingsfor:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatLocalNotificationDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emDidRecivePushSilentMessage(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emGetNotificationMessage(_:state:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:openSettingsFor:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocalNotificationDelegate\/emuserNotificationCenter(_:willPresent:withCompletionHandler:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emGetNotificationMessage(_:state:)\/title","value":"emGetNotificationMessage:state:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emGetNotificationMessage(_:state:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emGetNotificationMessage:state:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/title","value":"AgoraChatLocalNotificationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocalNotificationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emDidRecivePushSilentMessage(_:)\/title","value":"emDidRecivePushSilentMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emDidRecivePushSilentMessage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emDidRecivePushSilentMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:didReceive:withCompletionHandler:)\/title","value":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:didReceive:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emuserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:willPresent:withCompletionHandler:)\/title","value":"emuserNotificationCenter:willPresentNotification:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:willPresent:withCompletionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emuserNotificationCenter:willPresentNotification:withCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:openSettingsFor:)\/title","value":"emuserNotificationCenter:openSettingsForNotification:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocalNotificationDelegate~1emuserNotificationCenter(_:openSettingsFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"emuserNotificationCenter:openSettingsForNotification:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}