{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachattype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachattype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chat types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatType"}],"title":"AgoraChatType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/chat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/chatRoom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/groupChat"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType/chat":{"role":"symbol","title":"AgoraChatType.chat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/chat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatTypeChat"}],"url":"\/documentation\/agorachat\/agorachattype\/chat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType":{"role":"symbol","title":"AgoraChatType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatType"}],"abstract":[{"type":"text","text":"Chat types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatType"}],"url":"\/documentation\/agorachat\/agorachattype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType/chatRoom":{"role":"symbol","title":"AgoraChatType.chatRoom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatRoom"}],"abstract":[{"type":"text","text":"Group chat."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/chatRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatTypeChatRoom"}],"url":"\/documentation\/agorachat\/agorachattype\/chatroom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachattype\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachattype\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType/groupChat":{"role":"symbol","title":"AgoraChatType.groupChat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChat"}],"abstract":[{"type":"text","text":"One-to-one chat."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/groupChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatTypeGroupChat"}],"url":"\/documentation\/agorachat\/agorachattype\/groupchat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachattype\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/chat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/chatRoom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType\/groupChat"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType~1chat\/title","value":"AgoraChatTypeChat"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType~1chat\/fragments","value":[{"kind":"identifier","text":"AgoraChatTypeChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType\/title","value":"AgoraChatType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType\/fragments","value":[{"kind":"identifier","text":"AgoraChatType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType~1chatRoom\/title","value":"AgoraChatTypeChatRoom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType~1chatRoom\/fragments","value":[{"kind":"identifier","text":"AgoraChatTypeChatRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType~1groupChat\/title","value":"AgoraChatTypeGroupChat"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType~1groupChat\/fragments","value":[{"kind":"identifier","text":"AgoraChatTypeGroupChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}