{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The chat message class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"title":"AgoraChatMessage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatMessage","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationID:body:ext:)-5gibt","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationID:from:to:body:ext:)-64ay7","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationId:body:ext:)-55n8h","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationId:from:to:body:ext:)-1gawt"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/body","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/chatThread","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/chatType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/conversationId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/direction","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/ext","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/from","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/groupAckCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isChatThreadMessage","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isDeliverAcked","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isListened","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isNeedGroupAck","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isRead","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isReadAcked","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/localTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/messageId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/onlineState","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/priority","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/reactionList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/status","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/swiftBody","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/timestamp","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/to"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/getReaction(_:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/conversationId":{"role":"symbol","title":"conversationId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The conversation ID, which is the unique identifier of the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/conversationId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"url":"\/documentation\/agorachat\/agorachatmessage\/conversationid"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/from":{"role":"symbol","title":"from","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The user sending the message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/from","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"from"}],"url":"\/documentation\/agorachat\/agorachatmessage\/from"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/groupAckCount":{"role":"symbol","title":"groupAckCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAckCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The number of read receipts received for group messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/groupAckCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupAckCount"}],"url":"\/documentation\/agorachat\/agorachatmessage\/groupackcount"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/ext":{"role":"symbol","title":"ext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The custom message extension."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/ext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ext"}],"url":"\/documentation\/agorachat\/agorachatmessage\/ext"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/getReaction(_:)":{"role":"symbol","title":"getReaction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReaction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the Reaction content by the Reaction ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/getReaction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getReaction:"}],"url":"\/documentation\/agorachat\/agorachatmessage\/getreaction(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage":{"role":"symbol","title":"AgoraChatMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"abstract":[{"type":"text","text":"The chat message class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessage"}],"url":"\/documentation\/agorachat\/agorachatmessage"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/isNeedGroupAck":{"role":"symbol","title":"isNeedGroupAck","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNeedGroupAck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether read receipts are required for group messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isNeedGroupAck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isNeedGroupAck"}],"url":"\/documentation\/agorachat\/agorachatmessage\/isneedgroupack"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/init(conversationID:body:ext:)-5gibt":{"role":"symbol","title":"init(conversationID:body:ext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatMessageBody"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes a message instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationID:body:ext:)-5gibt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConversationID:body:ext:"}],"url":"\/documentation\/agorachat\/agorachatmessage\/init(conversationid:body:ext:)-5gibt"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/init(conversationId:from:to:body:ext:)-1gawt":{"role":"symbol","title":"init(conversationId:from:to:body:ext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBaseBody","preciseIdentifier":"s:9AgoraChat0aB15MessageBaseBodyO"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[{"type":"text","text":"The constructor of ChatMessage"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationId:from:to:body:ext:)-1gawt","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmessage\/init(conversationid:from:to:body:ext:)-1gawt"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/status":{"role":"symbol","title":"status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatus","preciseIdentifier":"c:@E@AgoraChatMessageStatus"}],"abstract":[{"type":"text","text":"The message delivery status. See {@link AgoraChatMessageStatus}."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"status"}],"url":"\/documentation\/agorachat\/agorachatmessage\/status"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/timestamp":{"role":"symbol","title":"timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The Unix timestamp for the chat server receiving the message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/timestamp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"url":"\/documentation\/agorachat\/agorachatmessage\/timestamp"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/isChatThreadMessage":{"role":"symbol","title":"isChatThreadMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatThreadMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether this message is sent within a thread:"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isChatThreadMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChatThreadMessage"}],"url":"\/documentation\/agorachat\/agorachatmessage\/ischatthreadmessage"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/init(conversationID:from:to:body:ext:)-64ay7":{"role":"symbol","title":"init(conversationID:from:to:body:ext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatMessageBody"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes a message instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationID:from:to:body:ext:)-64ay7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConversationID:from:to:body:ext:"}],"url":"\/documentation\/agorachat\/agorachatmessage\/init(conversationid:from:to:body:ext:)-64ay7"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/init(conversationId:body:ext:)-55n8h":{"role":"symbol","title":"init(conversationId:body:ext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBaseBody","preciseIdentifier":"s:9AgoraChat0aB15MessageBaseBodyO"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[{"type":"text","text":"The constructor of ChatMessage.This method must be called after login success.Will use current user as the from of message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationId:body:ext:)-55n8h","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmessage\/init(conversationid:body:ext:)-55n8h"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/onlineState":{"role":"symbol","title":"onlineState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the message is an online message:"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/onlineState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onlineState"}],"url":"\/documentation\/agorachat\/agorachatmessage\/onlinestate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/isRead":{"role":"symbol","title":"isRead","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the message is read."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isRead","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRead"}],"url":"\/documentation\/agorachat\/agorachatmessage\/isread"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/isReadAcked":{"role":"symbol","title":"isReadAcked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReadAcked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the message read receipt is sent (from the message recipient) or received (by the message sender)."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isReadAcked","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isReadAcked"}],"url":"\/documentation\/agorachat\/agorachatmessage\/isreadacked"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/chatThread":{"role":"symbol","title":"chatThread","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThread"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatThread","preciseIdentifier":"c:objc(cs)AgoraChatThread"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets an overview of the thread in the message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/chatThread","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatThread"}],"url":"\/documentation\/agorachat\/agorachatmessage\/chatthread"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/body":{"role":"symbol","title":"body","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatMessageBody"}],"abstract":[{"type":"text","text":"The message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/body","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"body"}],"url":"\/documentation\/agorachat\/agorachatmessage\/body"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/isDeliverAcked":{"role":"symbol","title":"isDeliverAcked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeliverAcked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the delivery receipt is sent or received:"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isDeliverAcked","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDeliverAcked"}],"url":"\/documentation\/agorachat\/agorachatmessage\/isdeliveracked"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/to":{"role":"symbol","title":"to","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The user receiving the message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/to","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"to"}],"url":"\/documentation\/agorachat\/agorachatmessage\/to"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/isListened":{"role":"symbol","title":"isListened","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isListened"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the voice message is played."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isListened","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isListened"}],"url":"\/documentation\/agorachat\/agorachatmessage\/islistened"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/swiftBody":{"role":"symbol","title":"swiftBody","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftBody"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBaseBody","preciseIdentifier":"s:9AgoraChat0aB15MessageBaseBodyO"}],"abstract":[{"type":"text","text":"The message body with swift syntax"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/swiftBody","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmessage\/swiftbody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/chatType":{"role":"symbol","title":"chatType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatType","preciseIdentifier":"c:@E@AgoraChatType"}],"abstract":[{"type":"text","text":"The chat type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/chatType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatType"}],"url":"\/documentation\/agorachat\/agorachatmessage\/chattype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/priority":{"role":"symbol","title":"priority","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatRoomMessagePriority","preciseIdentifier":"c:@E@AgoraChatRoomMessagePriority"}],"abstract":[{"type":"text","text":"Sets the priority of a chat room message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/priority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"priority"}],"url":"\/documentation\/agorachat\/agorachatmessage\/priority"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/reactionList":{"role":"symbol","title":"reactionList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactionList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The Reaction list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/reactionList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reactionList"}],"url":"\/documentation\/agorachat\/agorachatmessage\/reactionlist"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/messageId":{"role":"symbol","title":"messageId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The message ID, which is the unique identifier of the message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/messageId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageId"}],"url":"\/documentation\/agorachat\/agorachatmessage\/messageid"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/localTime":{"role":"symbol","title":"localTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The Unix timestamp for the local client sending or receiving the message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/localTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localTime"}],"url":"\/documentation\/agorachat\/agorachatmessage\/localtime"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage/direction":{"role":"symbol","title":"direction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageDirection","preciseIdentifier":"c:@E@AgoraChatMessageDirection"}],"abstract":[{"type":"text","text":"The message delivery direction."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/direction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"direction"}],"url":"\/documentation\/agorachat\/agorachatmessage\/direction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMessage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/body","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/chatThread","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/chatType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/conversationId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/direction","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/ext","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/from","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/groupAckCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isChatThreadMessage","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isDeliverAcked","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isListened","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isNeedGroupAck","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isRead","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/isReadAcked","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/localTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/messageId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/onlineState","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/priority","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/reactionList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/status","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/timestamp","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/to"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/getReaction(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationID:body:ext:)-5gibt","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage\/init(conversationID:from:to:body:ext:)-64ay7"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1conversationId\/title","value":"conversationId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1conversationId\/fragments","value":[{"kind":"identifier","text":"conversationId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1from\/title","value":"from"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1from\/fragments","value":[{"kind":"identifier","text":"from"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1groupAckCount\/title","value":"groupAckCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1groupAckCount\/fragments","value":[{"kind":"identifier","text":"groupAckCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1ext\/title","value":"ext"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1ext\/fragments","value":[{"kind":"identifier","text":"ext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1getReaction(_:)\/title","value":"getReaction:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1getReaction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReaction:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/title","value":"AgoraChatMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isNeedGroupAck\/title","value":"isNeedGroupAck"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isNeedGroupAck\/fragments","value":[{"kind":"identifier","text":"isNeedGroupAck"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1init(conversationID:body:ext:)-5gibt\/title","value":"initWithConversationID:body:ext:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1init(conversationID:body:ext:)-5gibt\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConversationID:body:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1timestamp\/fragments","value":[{"kind":"identifier","text":"timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isChatThreadMessage\/title","value":"isChatThreadMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isChatThreadMessage\/fragments","value":[{"kind":"identifier","text":"isChatThreadMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1init(conversationID:from:to:body:ext:)-64ay7\/title","value":"initWithConversationID:from:to:body:ext:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1init(conversationID:from:to:body:ext:)-64ay7\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConversationID:from:to:body:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1onlineState\/title","value":"onlineState"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1onlineState\/fragments","value":[{"kind":"identifier","text":"onlineState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isRead\/title","value":"isRead"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isRead\/fragments","value":[{"kind":"identifier","text":"isRead"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isReadAcked\/title","value":"isReadAcked"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isReadAcked\/fragments","value":[{"kind":"identifier","text":"isReadAcked"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1chatThread\/title","value":"chatThread"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1chatThread\/fragments","value":[{"kind":"identifier","text":"chatThread"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1body\/title","value":"body"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1body\/fragments","value":[{"kind":"identifier","text":"body"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isDeliverAcked\/title","value":"isDeliverAcked"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isDeliverAcked\/fragments","value":[{"kind":"identifier","text":"isDeliverAcked"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1to\/title","value":"to"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1to\/fragments","value":[{"kind":"identifier","text":"to"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isListened\/title","value":"isListened"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1isListened\/fragments","value":[{"kind":"identifier","text":"isListened"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1chatType\/title","value":"chatType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1chatType\/fragments","value":[{"kind":"identifier","text":"chatType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1priority\/title","value":"priority"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1priority\/fragments","value":[{"kind":"identifier","text":"priority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1reactionList\/title","value":"reactionList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1reactionList\/fragments","value":[{"kind":"identifier","text":"reactionList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1messageId\/title","value":"messageId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1messageId\/fragments","value":[{"kind":"identifier","text":"messageId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1localTime\/title","value":"localTime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1localTime\/fragments","value":[{"kind":"identifier","text":"localTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1direction\/title","value":"direction"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage~1direction\/fragments","value":[{"kind":"identifier","text":"direction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}