{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupPermissionType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgrouppermissiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgrouppermissiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The group permission type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupPermissionType"}],"title":"AgoraChatGroupPermissionType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatGroupPermissionType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/admin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/member","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/none","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/owner"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType":{"role":"symbol","title":"AgoraChatGroupPermissionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupPermissionType"}],"abstract":[{"type":"text","text":"The group permission type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}],"url":"\/documentation\/agorachat\/agorachatgrouppermissiontype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/member":{"role":"symbol","title":"AgoraChatGroupPermissionType.member","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"member"}],"abstract":[{"type":"text","text":"The unknown type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/member","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeMember"}],"url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/member"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/owner":{"role":"symbol","title":"AgoraChatGroupPermissionType.owner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"owner"}],"abstract":[{"type":"text","text":"The group admin."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/owner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeOwner"}],"url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/owner"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/none":{"role":"symbol","title":"AgoraChatGroupPermissionType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeNone"}],"url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/none"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/admin":{"role":"symbol","title":"AgoraChatGroupPermissionType.admin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admin"}],"abstract":[{"type":"text","text":"The group member."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/admin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeAdmin"}],"url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/admin"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatgrouppermissiontype\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupPermissionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/admin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/member","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/none","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType\/owner"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupPermissionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType\/title","value":"AgoraChatGroupPermissionType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1member\/title","value":"AgoraChatGroupPermissionTypeMember"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1member\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeMember"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1owner\/title","value":"AgoraChatGroupPermissionTypeOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1owner\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeOwner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1none\/title","value":"AgoraChatGroupPermissionTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1none\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1admin\/title","value":"AgoraChatGroupPermissionTypeAdmin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType~1admin\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionTypeAdmin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}