{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupmanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The group manager delegates."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}],"title":"AgoraChatGroupManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatGroupManagerDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/didJoin(_:inviter:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/didLeave(_:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:addedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:removedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAllMemberMuteChanged(_:isAllMemberMuted:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAnnouncementDidUpdate(_:announcement:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupFileListDidUpdate(_:addedSharedFile:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupFileListDidUpdate(_:removedSharedFile:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidAccept(_:invitee:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidReceive(_:inviter:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupListDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupMuteListDidUpdate(_:removedMutedMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupSpecificationDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupStateChanged(_:isDisabled:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupWhiteListDidUpdate(_:addedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupWhiteListDidUpdate(_:removedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidApprove(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/userDidJoin(_:user:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/userDidLeave(_:user:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupInvitationDidAccept(_:invitee:)":{"navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidAccept:invitee:"}],"role":"symbol","title":"groupInvitationDidAccept(_:invitee:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidAccept"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This callback is triggered when the peer user accepts the group invitation sent by the local user. For example, user B accepts the invitation of user A, user A receives this callback."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidAccept(_:invitee:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupinvitationdidaccept(_:invitee:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupAdminListDidUpdate(_:removedAdmin:)":{"role":"symbol","title":"groupAdminListDidUpdate(_:removedAdmin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a groupmember is removed from the admin list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:removedAdmin:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupAdminListDidUpdate:removedAdmin:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupadminlistdidupdate(_:removedadmin:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupOwnerDidUpdate(_:newOwner:oldOwner:)":{"navigatorTitle":[{"kind":"identifier","text":"groupOwnerDidUpdate:newOwner:oldOwner:"}],"role":"symbol","title":"groupOwnerDidUpdate(_:newOwner:oldOwner:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupOwnerDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the group owner changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupownerdidupdate(_:newowner:oldowner:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/userDidLeave(_:user:)":{"role":"symbol","title":"userDidLeave(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user leaves the group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/userDidLeave(_:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidLeaveGroup:user:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/userdidleave(_:user:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupAnnouncementDidUpdate(_:announcement:)":{"navigatorTitle":[{"kind":"identifier","text":"groupAnnouncementDidUpdate:announcement:"}],"role":"symbol","title":"groupAnnouncementDidUpdate(_:announcement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAnnouncementDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the group announcement updates."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAnnouncementDidUpdate(_:announcement:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupannouncementdidupdate(_:announcement:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupMuteListDidUpdate(_:removedMutedMembers:)":{"role":"symbol","title":"groupMuteListDidUpdate(_:removedMutedMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the group members are removed from the mute list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupMuteListDidUpdate(_:removedMutedMembers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupMuteListDidUpdate:removedMutedMembers:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupmutelistdidupdate(_:removedmutedmembers:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/joinGroupRequestDidReceive(_:user:reason:)":{"role":"symbol","title":"joinGroupRequestDidReceive(_:user:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinGroupRequestDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the group owner receives a join request."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidReceive(_:user:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidReceive:user:reason:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/joingrouprequestdidreceive(_:user:reason:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/didJoin(_:inviter:message:)":{"role":"symbol","title":"didJoin(_:inviter:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didJoin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the SDK automatically joins the group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/didJoin(_:inviter:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didJoinGroup:inviter:message:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/didjoin(_:inviter:message:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/joinGroupRequestDidDecline(_:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidDecline:reason:"}],"role":"symbol","title":"joinGroupRequestDidDecline(_:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinGroupRequestDidDecline"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"If you set the group type as AgoraChatGroupStylePublicJoinNeedApproval, when the group owner declines a join request, the user that sends the request receives this callback."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidDecline(_:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/joingrouprequestdiddecline(_:reason:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupInvitationDidDecline(_:invitee:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidDecline:invitee:reason:"}],"role":"symbol","title":"groupInvitationDidDecline(_:invitee:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidDecline"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the group invitation is declined."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidDecline(_:invitee:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupinvitationdiddecline(_:invitee:reason:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)":{"role":"symbol","title":"groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"muteExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the group members are added to the group mute list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupMuteListDidUpdate:addedMutedMembers:muteExpire:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupmutelistdidupdate(_:addedmutedmembers:muteexpire:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupFileListDidUpdate(_:addedSharedFile:)":{"navigatorTitle":[{"kind":"identifier","text":"groupFileListDidUpdate:addedSharedFile:"}],"role":"symbol","title":"groupFileListDidUpdate(_:addedSharedFile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupFileListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedSharedFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupSharedFile","preciseIdentifier":"c:objc(cs)AgoraChatGroupSharedFile"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the group shared file is uploaded."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupFileListDidUpdate(_:addedSharedFile:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupfilelistdidupdate(_:addedsharedfile:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupInvitationDidReceive(_:groupName:inviter:message:)":{"role":"symbol","title":"groupInvitationDidReceive(_:groupName:inviter:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the user receives a group invitation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidReceive(_:groupName:inviter:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupinvitationdidreceive(_:groupname:inviter:message:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupSpecificationDidUpdate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"groupSpecificationDidUpdate:"}],"role":"symbol","title":"groupSpecificationDidUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupSpecificationDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Occurs when the group specification update,Need to call for details of the API (IAgoraChatGroupManager.h : getGroupSpecificationFromServerWithId) to get the latest information"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupSpecificationDidUpdate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupspecificationdidupdate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupWhiteListDidUpdate(_:addedWhiteListMembers:)":{"navigatorTitle":[{"kind":"identifier","text":"groupWhiteListDidUpdate:addedWhiteListMembers:"}],"role":"symbol","title":"groupWhiteListDidUpdate(_:addedWhiteListMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupWhiteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedWhiteListMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the group members are added to the allowlist."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupWhiteListDidUpdate(_:addedWhiteListMembers:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupwhitelistdidupdate(_:addedwhitelistmembers:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/joinGroupRequestDidApprove(_:)":{"navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidApprove:"}],"role":"symbol","title":"joinGroupRequestDidApprove(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinGroupRequestDidApprove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"If you set the group type as AgoraChatGroupStylePublicJoinNeedApproval, when the group owner approves the join request, the user that sends the request receives this callback."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidApprove(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/joingrouprequestdidapprove(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupWhiteListDidUpdate(_:removedWhiteListMembers:)":{"navigatorTitle":[{"kind":"identifier","text":"groupWhiteListDidUpdate:removedWhiteListMembers:"}],"role":"symbol","title":"groupWhiteListDidUpdate(_:removedWhiteListMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupWhiteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedWhiteListMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the group members are removed from the allowlist."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupWhiteListDidUpdate(_:removedWhiteListMembers:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupwhitelistdidupdate(_:removedwhitelistmembers:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/userDidJoin(_:user:)":{"role":"symbol","title":"userDidJoin(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidJoin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user joins a group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/userDidJoin(_:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidJoinGroup:user:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/userdidjoin(_:user:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupInvitationDidReceive(_:inviter:message:)":{"navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:inviter:message:"}],"deprecated":true,"role":"symbol","title":"groupInvitationDidReceive(_:inviter:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Occurs when the user receives a group invitation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidReceive(_:inviter:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupinvitationdidreceive(_:inviter:message:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate":{"role":"symbol","title":"AgoraChatGroupManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}],"abstract":[{"type":"text","text":"The group manager delegates."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupFileListDidUpdate(_:removedSharedFile:)":{"navigatorTitle":[{"kind":"identifier","text":"groupFileListDidUpdate:removedSharedFile:"}],"role":"symbol","title":"groupFileListDidUpdate(_:removedSharedFile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupFileListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedSharedFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the shared file of the group is removed."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupFileListDidUpdate(_:removedSharedFile:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupfilelistdidupdate(_:removedsharedfile:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupAdminListDidUpdate(_:addedAdmin:)":{"navigatorTitle":[{"kind":"identifier","text":"groupAdminListDidUpdate:addedAdmin:"}],"role":"symbol","title":"groupAdminListDidUpdate(_:addedAdmin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a group member is added to the admin list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:addedAdmin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupadminlistdidupdate(_:addedadmin:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupAllMemberMuteChanged(_:isAllMemberMuted:)":{"navigatorTitle":[{"kind":"identifier","text":"groupAllMemberMuteChanged:isAllMemberMuted:"}],"role":"symbol","title":"groupAllMemberMuteChanged(_:isAllMemberMuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAllMemberMuteChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAllMemberMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the mute state of all group members changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAllMemberMuteChanged(_:isAllMemberMuted:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupallmembermutechanged(_:isallmembermuted:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupStateChanged(_:isDisabled:)":{"navigatorTitle":[{"kind":"identifier","text":"groupStateChanged:isDisabled:"}],"role":"symbol","title":"groupStateChanged(_:isDisabled:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupStateChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"isDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the disabled state of group changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupStateChanged(_:isDisabled:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupstatechanged(_:isdisabled:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupListDidUpdate(_:)":{"role":"symbol","title":"groupListDidUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupListDidUpdate"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the group list updates."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupListDidUpdate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupListDidUpdate:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/grouplistdidupdate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/didLeave(_:reason:)":{"role":"symbol","title":"didLeave(_:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupLeaveReason","preciseIdentifier":"c:@E@AgoraChatGroupLeaveReason"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the user leaves a group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/didLeave(_:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didLeaveGroup:reason:"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/didleave(_:reason:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/didJoin(_:inviter:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/didLeave(_:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:addedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:removedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAllMemberMuteChanged(_:isAllMemberMuted:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAnnouncementDidUpdate(_:announcement:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupFileListDidUpdate(_:addedSharedFile:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupFileListDidUpdate(_:removedSharedFile:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidAccept(_:invitee:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupInvitationDidReceive(_:inviter:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupListDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupMuteListDidUpdate(_:removedMutedMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupSpecificationDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupStateChanged(_:isDisabled:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupWhiteListDidUpdate(_:addedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupWhiteListDidUpdate(_:removedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidApprove(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/userDidJoin(_:user:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/userDidLeave(_:user:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidAccept(_:invitee:)\/title","value":"groupInvitationDidAccept:invitee:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidAccept(_:invitee:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidAccept:invitee:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAdminListDidUpdate(_:removedAdmin:)\/title","value":"groupAdminListDidUpdate:removedAdmin:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAdminListDidUpdate(_:removedAdmin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupAdminListDidUpdate:removedAdmin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/title","value":"groupOwnerDidUpdate:newOwner:oldOwner:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupOwnerDidUpdate:newOwner:oldOwner:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1userDidLeave(_:user:)\/title","value":"userDidLeaveGroup:user:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1userDidLeave(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidLeaveGroup:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAnnouncementDidUpdate(_:announcement:)\/title","value":"groupAnnouncementDidUpdate:announcement:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAnnouncementDidUpdate(_:announcement:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupAnnouncementDidUpdate:announcement:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupMuteListDidUpdate(_:removedMutedMembers:)\/title","value":"groupMuteListDidUpdate:removedMutedMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupMuteListDidUpdate(_:removedMutedMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMuteListDidUpdate:removedMutedMembers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1joinGroupRequestDidReceive(_:user:reason:)\/title","value":"joinGroupRequestDidReceive:user:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1joinGroupRequestDidReceive(_:user:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidReceive:user:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1didJoin(_:inviter:message:)\/title","value":"didJoinGroup:inviter:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1didJoin(_:inviter:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didJoinGroup:inviter:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1joinGroupRequestDidDecline(_:reason:)\/title","value":"joinGroupRequestDidDecline:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1joinGroupRequestDidDecline(_:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidDecline:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidDecline(_:invitee:reason:)\/title","value":"groupInvitationDidDecline:invitee:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidDecline(_:invitee:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidDecline:invitee:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/title","value":"groupMuteListDidUpdate:addedMutedMembers:muteExpire:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMuteListDidUpdate:addedMutedMembers:muteExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupFileListDidUpdate(_:addedSharedFile:)\/title","value":"groupFileListDidUpdate:addedSharedFile:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupFileListDidUpdate(_:addedSharedFile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupFileListDidUpdate:addedSharedFile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidReceive(_:groupName:inviter:message:)\/title","value":"groupInvitationDidReceive:groupName:inviter:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidReceive(_:groupName:inviter:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupSpecificationDidUpdate(_:)\/title","value":"groupSpecificationDidUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupSpecificationDidUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupSpecificationDidUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupWhiteListDidUpdate(_:addedWhiteListMembers:)\/title","value":"groupWhiteListDidUpdate:addedWhiteListMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupWhiteListDidUpdate(_:addedWhiteListMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupWhiteListDidUpdate:addedWhiteListMembers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1joinGroupRequestDidApprove(_:)\/title","value":"joinGroupRequestDidApprove:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1joinGroupRequestDidApprove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidApprove:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupWhiteListDidUpdate(_:removedWhiteListMembers:)\/title","value":"groupWhiteListDidUpdate:removedWhiteListMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupWhiteListDidUpdate(_:removedWhiteListMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupWhiteListDidUpdate:removedWhiteListMembers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1userDidJoin(_:user:)\/title","value":"userDidJoinGroup:user:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1userDidJoin(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidJoinGroup:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidReceive(_:inviter:message:)\/title","value":"groupInvitationDidReceive:inviter:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupInvitationDidReceive(_:inviter:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidReceive:inviter:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate\/title","value":"AgoraChatGroupManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupFileListDidUpdate(_:removedSharedFile:)\/title","value":"groupFileListDidUpdate:removedSharedFile:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupFileListDidUpdate(_:removedSharedFile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupFileListDidUpdate:removedSharedFile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAdminListDidUpdate(_:addedAdmin:)\/title","value":"groupAdminListDidUpdate:addedAdmin:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAdminListDidUpdate(_:addedAdmin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupAdminListDidUpdate:addedAdmin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAllMemberMuteChanged(_:isAllMemberMuted:)\/title","value":"groupAllMemberMuteChanged:isAllMemberMuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAllMemberMuteChanged(_:isAllMemberMuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupAllMemberMuteChanged:isAllMemberMuted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupStateChanged(_:isDisabled:)\/title","value":"groupStateChanged:isDisabled:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupStateChanged(_:isDisabled:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupStateChanged:isDisabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupListDidUpdate(_:)\/title","value":"groupListDidUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupListDidUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupListDidUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1didLeave(_:reason:)\/title","value":"didLeaveGroup:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1didLeave(_:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didLeaveGroup:reason:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}