{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparam"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparam"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The silent message params object"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"title":"AgoraChatSilentModeParam","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatSilentModeParam","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/init(paramType:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/paramType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/remindType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeDuration","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeEndTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeStartTime"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/silentModeStartTime":{"role":"symbol","title":"silentModeStartTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentModeStartTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeTime","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeTime"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The start time of interval type for silent messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeStartTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silentModeStartTime"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/silentmodestarttime"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/init(paramType:)":{"role":"symbol","title":"init(paramType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/init(paramType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParamType:"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/init(paramtype:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/silentModeEndTime":{"role":"symbol","title":"silentModeEndTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentModeEndTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeTime","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeTime"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The end time of interval type for silent messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeEndTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silentModeEndTime"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/silentmodeendtime"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam":{"role":"symbol","title":"AgoraChatSilentModeParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"abstract":[{"type":"text","text":"The silent message params object"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/paramType":{"role":"symbol","title":"paramType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType"}],"abstract":[{"type":"text","text":"Parameter type for silent messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/paramType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paramType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/paramtype"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/silentModeDuration":{"role":"symbol","title":"silentModeDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"silentModeDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The duration for silent messages (in minute)."},{"type":"text","text":" "},{"type":"text","text":"A value of 0 indicates that silent messages is disabled，A maximum of 7 x 24 x 60 minutes can be set.An expiration timestamp is returned， disabled return 0."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"silentModeDuration"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/silentmodeduration"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/remindType":{"role":"symbol","title":"remindType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushRemindType","preciseIdentifier":"c:@E@AgoraChatPushRemindType"}],"abstract":[{"type":"text","text":"The remind type for push messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/remindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remindType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/remindtype"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatSilentModeParam"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/paramType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/remindType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeDuration","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeEndTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/silentModeStartTime"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/init(paramType:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParam"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1silentModeStartTime\/title","value":"silentModeStartTime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1silentModeStartTime\/fragments","value":[{"kind":"identifier","text":"silentModeStartTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1init(paramType:)\/title","value":"initWithParamType:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1init(paramType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParamType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1silentModeEndTime\/title","value":"silentModeEndTime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1silentModeEndTime\/fragments","value":[{"kind":"identifier","text":"silentModeEndTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam\/title","value":"AgoraChatSilentModeParam"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1paramType\/title","value":"paramType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1paramType\/fragments","value":[{"kind":"identifier","text":"paramType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1silentModeDuration\/title","value":"silentModeDuration"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1silentModeDuration\/fragments","value":[{"kind":"identifier","text":"silentModeDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1remindType\/title","value":"remindType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1remindType\/fragments","value":[{"kind":"identifier","text":"remindType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}