{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocationMessageBody"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatlocationmessagebody"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatlocationmessagebody"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBody"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The location message body."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocationMessageBody"}],"title":"AgoraChatLocationMessageBody","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatLocationMessageBody","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocationMessageBody"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/init(latitude:longitude:address:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/init(latitude:longitude:address:buildingName:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/address","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/buildingName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/latitude","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/longitude"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody/address":{"role":"symbol","title":"address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The address."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/address","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"address"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody\/address"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody":{"role":"symbol","title":"AgoraChatLocationMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocationMessageBody"}],"abstract":[{"type":"text","text":"The location message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLocationMessageBody"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBody":{"role":"symbol","title":"AgoraChatMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageBody"}],"abstract":[{"type":"text","text":"The message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBody"}],"url":"\/documentation\/agorachat\/agorachatmessagebody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody/buildingName":{"role":"symbol","title":"buildingName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildingName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"buildingName"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/buildingName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildingName"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody\/buildingname"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody/latitude":{"role":"symbol","title":"latitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The location latitude."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/latitude","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latitude"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody\/latitude"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody/longitude":{"role":"symbol","title":"longitude","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The location longitude."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/longitude","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"longitude"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody\/longitude"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody/init(latitude:longitude:address:buildingName:)":{"role":"symbol","title":"init(latitude:longitude:address:buildingName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"buildingName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initialize a location message body instance"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/init(latitude:longitude:address:buildingName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLatitude:longitude:address:buildingName:"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody\/init(latitude:longitude:address:buildingname:)"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLocationMessageBody/init(latitude:longitude:address:)":{"role":"symbol","title":"init(latitude:longitude:address:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a location message body instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/init(latitude:longitude:address:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLatitude:longitude:address:"}],"url":"\/documentation\/agorachat\/agorachatlocationmessagebody\/init(latitude:longitude:address:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatLocationMessageBody"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocationMessageBody"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatLocationMessageBody"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/address","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/buildingName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/latitude","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/longitude"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/init(latitude:longitude:address:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLocationMessageBody\/init(latitude:longitude:address:buildingName:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBody"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLocationMessageBody"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatMessageBody","text":"AgoraChatMessageBody"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1address\/title","value":"address"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1address\/fragments","value":[{"kind":"identifier","text":"address"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody\/title","value":"AgoraChatLocationMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatLocationMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBody\/title","value":"AgoraChatMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1buildingName\/title","value":"buildingName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1buildingName\/fragments","value":[{"kind":"identifier","text":"buildingName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1latitude\/title","value":"latitude"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1latitude\/fragments","value":[{"kind":"identifier","text":"latitude"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1longitude\/title","value":"longitude"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1longitude\/fragments","value":[{"kind":"identifier","text":"longitude"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1init(latitude:longitude:address:buildingName:)\/title","value":"initWithLatitude:longitude:address:buildingName:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1init(latitude:longitude:address:buildingName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLatitude:longitude:address:buildingName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1init(latitude:longitude:address:)\/title","value":"initWithLatitude:longitude:address:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLocationMessageBody~1init(latitude:longitude:address:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLatitude:longitude:address:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}