{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatManagerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The chat related callbacks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"title":"AgoraChatManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatManagerDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/cmdMessagesDidReceive(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/conversationListDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageAckHasChanged()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageDidRead(_:groupAcks:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageAttachmentStatusDidChange(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageReactionDidChange(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageStatusDidChange(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidDeliver(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidRead(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidRecall(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidReceive(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesInfoDidRecall(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/onConversationRead(_:to:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/conversationListDidUpdate(_:)":{"role":"symbol","title":"conversationListDidUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationListDidUpdate"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatConversation","preciseIdentifier":"c:objc(cs)AgoraChatConversation"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the conversation list changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/conversationListDidUpdate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversationListDidUpdate:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/conversationlistdidupdate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/cmdMessagesDidReceive(_:)":{"navigatorTitle":[{"kind":"identifier","text":"cmdMessagesDidReceive:"}],"role":"symbol","title":"cmdMessagesDidReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmdMessagesDidReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when receiving command messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/cmdMessagesDidReceive(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/cmdmessagesdidreceive(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messagesDidRecall(_:)":{"deprecated":true,"role":"symbol","title":"messagesDidRecall(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidRecall"},{"kind":"text","text":"(["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[{"type":"text","text":"Occurs when a received message is recalled."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidRecall(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesDidRecall:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagesdidrecall(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate":{"role":"symbol","title":"AgoraChatManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"abstract":[{"type":"text","text":"The chat related callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messagesDidReceive(_:)":{"role":"symbol","title":"messagesDidReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the SDK receives new messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidReceive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesDidReceive:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagesdidreceive(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/onConversationRead(_:to:)":{"role":"symbol","title":"onConversationRead(_:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a conversation read receipt is received."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/onConversationRead(_:to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConversationRead:to:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/onconversationread(_:to:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messageAttachmentStatusDidChange(_:error:)":{"role":"symbol","title":"messageAttachmentStatusDidChange(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageAttachmentStatusDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the message attachment status changed."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageAttachmentStatusDidChange(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageAttachmentStatusDidChange:error:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messageattachmentstatusdidchange(_:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messageReactionDidChange(_:)":{"navigatorTitle":[{"kind":"identifier","text":"messageReactionDidChange:"}],"role":"symbol","title":"messageReactionDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionDidChange"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatMessageReactionChange","preciseIdentifier":"c:objc(cs)AgoraChatMessageReactionChange"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the Reaction data changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageReactionDidChange(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagereactiondidchange(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messageStatusDidChange(_:error:)":{"role":"symbol","title":"messageStatusDidChange(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageStatusDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when message status has changed. You need to set the parameter as nil."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageStatusDidChange(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageStatusDidChange:error:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagestatusdidchange(_:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/groupMessageDidRead(_:groupAcks:)":{"navigatorTitle":[{"kind":"identifier","text":"groupMessageDidRead:groupAcks:"}],"role":"symbol","title":"groupMessageDidRead(_:groupAcks:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageDidRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupAcks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatGroupMessageAck","preciseIdentifier":"c:objc(cs)AgoraChatGroupMessageAck"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the SDK receives read receipts for group messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageDidRead(_:groupAcks:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessagedidread(_:groupacks:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messagesInfoDidRecall(_:)":{"role":"symbol","title":"messagesInfoDidRecall(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesInfoDidRecall"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatRecallMessageInfo","preciseIdentifier":"c:objc(cs)AgoraChatRecallMessageInfo"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when a message is recalled."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesInfoDidRecall(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesInfoDidRecall:"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagesinfodidrecall(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messagesDidRead(_:)":{"navigatorTitle":[{"kind":"identifier","text":"messagesDidRead:"}],"role":"symbol","title":"messagesDidRead(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidRead"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when receiving read acknowledgement in message list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidRead(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagesdidread(_:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/groupMessageAckHasChanged()":{"role":"symbol","title":"groupMessageAckHasChanged()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMessageAckHasChanged"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Occurs when the current group read messages count changed."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageAckHasChanged()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupMessageAckHasChanged"}],"url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/groupmessageackhaschanged()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatManagerDelegate/messagesDidDeliver(_:)":{"navigatorTitle":[{"kind":"identifier","text":"messagesDidDeliver:"}],"role":"symbol","title":"messagesDidDeliver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidDeliver"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when receiving delivered acknowledgement in message list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidDeliver(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmanagerdelegate\/messagesdiddeliver(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/cmdMessagesDidReceive(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/conversationListDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageAckHasChanged()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/groupMessageDidRead(_:groupAcks:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageAttachmentStatusDidChange(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageReactionDidChange(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messageStatusDidChange(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidDeliver(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidRead(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidRecall(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesDidReceive(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/messagesInfoDidRecall(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatManagerDelegate\/onConversationRead(_:to:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatManagerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1conversationListDidUpdate(_:)\/title","value":"conversationListDidUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1conversationListDidUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationListDidUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1cmdMessagesDidReceive(_:)\/title","value":"cmdMessagesDidReceive:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1cmdMessagesDidReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cmdMessagesDidReceive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidRecall(_:)\/title","value":"messagesDidRecall:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidRecall(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidRecall:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate\/title","value":"AgoraChatManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidReceive(_:)\/title","value":"messagesDidReceive:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidReceive:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1onConversationRead(_:to:)\/title","value":"onConversationRead:to:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1onConversationRead(_:to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationRead:to:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messageAttachmentStatusDidChange(_:error:)\/title","value":"messageAttachmentStatusDidChange:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messageAttachmentStatusDidChange(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageAttachmentStatusDidChange:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messageReactionDidChange(_:)\/title","value":"messageReactionDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messageReactionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageReactionDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messageStatusDidChange(_:error:)\/title","value":"messageStatusDidChange:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messageStatusDidChange(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageStatusDidChange:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageDidRead(_:groupAcks:)\/title","value":"groupMessageDidRead:groupAcks:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageDidRead(_:groupAcks:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMessageDidRead:groupAcks:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesInfoDidRecall(_:)\/title","value":"messagesInfoDidRecall:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesInfoDidRecall(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesInfoDidRecall:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidRead(_:)\/title","value":"messagesDidRead:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidRead(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidRead:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageAckHasChanged()\/title","value":"groupMessageAckHasChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1groupMessageAckHasChanged()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupMessageAckHasChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidDeliver(_:)\/title","value":"messagesDidDeliver:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatManagerDelegate~1messagesDidDeliver(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidDeliver:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}