{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroup"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The group."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"}],"title":"AgoraChatGroup","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatGroup","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroup"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/init(id:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/adminList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/announcement","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/blacklist","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/description","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/groupId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/groupName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isBlocked","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isDisabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isMuteAllMembers","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isPublic","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isPushNotificationEnabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/memberList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/muteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/occupants","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/occupantsCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/owner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/permissionType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/setting","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/settings","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/sharedFileList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/users","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/whiteList"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/users":{"role":"symbol","title":"users","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"users"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"All occupants of the group, including the group owner, admins, and all other group members."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/users","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"users"}],"url":"\/documentation\/agorachat\/agorachatgroup\/users"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/memberList":{"role":"symbol","title":"memberList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The member list of the group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/memberList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberList"}],"url":"\/documentation\/agorachat\/agorachatgroup\/memberlist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/whiteList":{"role":"symbol","title":"whiteList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whiteList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The allowlist of the chat group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/whiteList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"whiteList"}],"url":"\/documentation\/agorachat\/agorachatgroup\/whitelist"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The description of the group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/agorachat\/agorachatgroup\/description"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/isPublic":{"role":"symbol","title":"isPublic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the group is a public group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isPublic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPublic"}],"url":"\/documentation\/agorachat\/agorachatgroup\/ispublic"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/setting":{"deprecated":true,"role":"symbol","title":"setting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupOptions","preciseIdentifier":"c:objc(cs)AgoraChatGroupOptions"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Setting options of group, require fetch group’s detail first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/setting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setting"}],"url":"\/documentation\/agorachat\/agorachatgroup\/setting"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/isMuteAllMembers":{"role":"symbol","title":"isMuteAllMembers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMuteAllMembers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether all the group members are muted."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isMuteAllMembers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isMuteAllMembers"}],"url":"\/documentation\/agorachat\/agorachatgroup\/ismuteallmembers"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/announcement":{"role":"symbol","title":"announcement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The announcement of the group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupAnnouncementWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/announcement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"announcement"}],"url":"\/documentation\/agorachat\/agorachatgroup\/announcement"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/owner":{"role":"symbol","title":"owner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"owner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The owner of the group who has the highest privilege of the group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/owner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"owner"}],"url":"\/documentation\/agorachat\/agorachatgroup\/owner"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup":{"role":"symbol","title":"AgoraChatGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"}],"abstract":[{"type":"text","text":"The group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroup"}],"url":"\/documentation\/agorachat\/agorachatgroup"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/blacklist":{"role":"symbol","title":"blacklist","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blacklist"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The blocklist of the chat group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/blacklist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"blacklist"}],"url":"\/documentation\/agorachat\/agorachatgroup\/blacklist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/groupName":{"role":"symbol","title":"groupName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The subject of the group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" to get the group details first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/groupName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupName"}],"url":"\/documentation\/agorachat\/agorachatgroup\/groupname"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/isPushNotificationEnabled":{"role":"symbol","title":"isPushNotificationEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPushNotificationEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable the push notification service for the group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isPushNotificationEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPushNotificationEnabled"}],"url":"\/documentation\/agorachat\/agorachatgroup\/ispushnotificationenabled"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/occupants":{"deprecated":true,"role":"symbol","title":"occupants","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"occupants"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"All occupants of the group, includes the group owner and admins and all other group members."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/occupants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"occupants"}],"url":"\/documentation\/agorachat\/agorachatgroup\/occupants"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/isDisabled":{"role":"symbol","title":"isDisabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the group is disabled. The default value for reading or pulling roaming messages from the database is NO"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isDisabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDisabled"}],"url":"\/documentation\/agorachat\/agorachatgroup\/isdisabled"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/muteList":{"role":"symbol","title":"muteList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The list of muted members."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/muteList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteList"}],"url":"\/documentation\/agorachat\/agorachatgroup\/mutelist"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/sharedFileList":{"role":"symbol","title":"sharedFileList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedFileList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatGroupSharedFile","preciseIdentifier":"c:objc(cs)AgoraChatGroupSharedFile"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The list of group shared files."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/sharedFileList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedFileList"}],"url":"\/documentation\/agorachat\/agorachatgroup\/sharedfilelist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/init(id:)":{"role":"symbol","title":"init(id:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Gets the group instance. Creates an instance if it does not exist."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/init(id:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupWithId:"}],"url":"\/documentation\/agorachat\/agorachatgroup\/init(id:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/adminList":{"role":"symbol","title":"adminList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adminList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The admins of the group who have the group management authority. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/adminList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adminList"}],"url":"\/documentation\/agorachat\/agorachatgroup\/adminlist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/occupantsCount":{"role":"symbol","title":"occupantsCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"occupantsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total number of group occupants, including the owner, admins, and all other group members. To get the value of this member, you need to call getGroupSpecificationFromServerWithId first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/occupantsCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"occupantsCount"}],"url":"\/documentation\/agorachat\/agorachatgroup\/occupantscount"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/isBlocked":{"role":"symbol","title":"isBlocked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBlocked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to block the current group‘s messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isBlocked","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isBlocked"}],"url":"\/documentation\/agorachat\/agorachatgroup\/isblocked"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/settings":{"role":"symbol","title":"settings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupOptions","preciseIdentifier":"c:objc(cs)AgoraChatGroupOptions"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The setting options of group. To get the value of this member, you need to call "},{"type":"codeVoice","code":"getGroupSpecificationFromServerWithId"},{"type":"text","text":" first."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/settings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"settings"}],"url":"\/documentation\/agorachat\/agorachatgroup\/settings"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/permissionType":{"role":"symbol","title":"permissionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupPermissionType","preciseIdentifier":"c:@E@AgoraChatGroupPermissionType"}],"abstract":[{"type":"text","text":"The group membership type of the current login account."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/permissionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"permissionType"}],"url":"\/documentation\/agorachat\/agorachatgroup\/permissiontype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/groupId":{"role":"symbol","title":"groupId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The group ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/groupId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupId"}],"url":"\/documentation\/agorachat\/agorachatgroup\/groupid"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroup"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatGroup"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/adminList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/announcement","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/blacklist","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/description","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/groupId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/groupName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isBlocked","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isDisabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isMuteAllMembers","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isPublic","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/isPushNotificationEnabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/memberList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/muteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/occupants","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/occupantsCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/owner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/permissionType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/setting","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/settings","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/sharedFileList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/users","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/whiteList"]},{"title":"Type Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/init(id:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1users\/title","value":"users"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1users\/fragments","value":[{"kind":"identifier","text":"users"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1memberList\/title","value":"memberList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1memberList\/fragments","value":[{"kind":"identifier","text":"memberList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1whiteList\/title","value":"whiteList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1whiteList\/fragments","value":[{"kind":"identifier","text":"whiteList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isPublic\/title","value":"isPublic"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isPublic\/fragments","value":[{"kind":"identifier","text":"isPublic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1setting\/title","value":"setting"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1setting\/fragments","value":[{"kind":"identifier","text":"setting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isMuteAllMembers\/title","value":"isMuteAllMembers"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isMuteAllMembers\/fragments","value":[{"kind":"identifier","text":"isMuteAllMembers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1announcement\/title","value":"announcement"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1announcement\/fragments","value":[{"kind":"identifier","text":"announcement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1owner\/title","value":"owner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1owner\/fragments","value":[{"kind":"identifier","text":"owner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/title","value":"AgoraChatGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1blacklist\/title","value":"blacklist"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1blacklist\/fragments","value":[{"kind":"identifier","text":"blacklist"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1groupName\/title","value":"groupName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1groupName\/fragments","value":[{"kind":"identifier","text":"groupName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isPushNotificationEnabled\/title","value":"isPushNotificationEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isPushNotificationEnabled\/fragments","value":[{"kind":"identifier","text":"isPushNotificationEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1occupants\/title","value":"occupants"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1occupants\/fragments","value":[{"kind":"identifier","text":"occupants"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isDisabled\/title","value":"isDisabled"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isDisabled\/fragments","value":[{"kind":"identifier","text":"isDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1muteList\/title","value":"muteList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1muteList\/fragments","value":[{"kind":"identifier","text":"muteList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1sharedFileList\/title","value":"sharedFileList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1sharedFileList\/fragments","value":[{"kind":"identifier","text":"sharedFileList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1init(id:)\/title","value":"groupWithId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1init(id:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"groupWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1adminList\/title","value":"adminList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1adminList\/fragments","value":[{"kind":"identifier","text":"adminList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1occupantsCount\/title","value":"occupantsCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1occupantsCount\/fragments","value":[{"kind":"identifier","text":"occupantsCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isBlocked\/title","value":"isBlocked"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1isBlocked\/fragments","value":[{"kind":"identifier","text":"isBlocked"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1settings\/title","value":"settings"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1settings\/fragments","value":[{"kind":"identifier","text":"settings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1permissionType\/title","value":"permissionType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1permissionType\/fragments","value":[{"kind":"identifier","text":"permissionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1groupId\/title","value":"groupId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1groupId\/fragments","value":[{"kind":"identifier","text":"groupId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}