{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatServerCheckType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatserverchecktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatserverchecktype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This enum lists the server diagnostic tests which are run for the current user when you call AgoraChatClient::serviceCheckWithUsername. This is an asynchronous method. If there is an error, check the error code to know the error information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatServerCheckType"}],"title":"AgoraChatServerCheckType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatServerCheckType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/accountValidation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/doLogin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/doLogout","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/getDNSListFromServer","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/getTokenFromServer"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatserverchecktype\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/doLogout":{"role":"symbol","title":"AgoraChatServerCheckType.doLogout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doLogout"}],"abstract":[{"type":"text","text":"The check of the login mode."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/doLogout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckDoLogout"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype\/dologout"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/getDNSListFromServer":{"role":"symbol","title":"AgoraChatServerCheckType.getDNSListFromServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDNSListFromServer"}],"abstract":[{"type":"text","text":"The check of the account validity."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/getDNSListFromServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckGetDNSListFromServer"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype\/getdnslistfromserver"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatserverchecktype\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/doLogin":{"role":"symbol","title":"AgoraChatServerCheckType.doLogin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doLogin"}],"abstract":[{"type":"text","text":"The check of getting the token from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/doLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckDoLogin"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype\/dologin"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/accountValidation":{"role":"symbol","title":"AgoraChatServerCheckType.accountValidation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountValidation"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/accountValidation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype\/accountvalidation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/getTokenFromServer":{"role":"symbol","title":"AgoraChatServerCheckType.getTokenFromServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTokenFromServer"}],"abstract":[{"type":"text","text":"The check of getting DNS from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/getTokenFromServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckGetTokenFromServer"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype\/gettokenfromserver"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType":{"role":"symbol","title":"AgoraChatServerCheckType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatServerCheckType"}],"abstract":[{"type":"text","text":"This enum lists the server diagnostic tests which are run for the current user when you call AgoraChatClient::serviceCheckWithUsername. This is an asynchronous method. If there is an error, check the error code to know the error information."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckType"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatserverchecktype\/equatable-implementations"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatServerCheckType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatServerCheckType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/accountValidation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/doLogin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/doLogout","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/getDNSListFromServer","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/getTokenFromServer"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatServerCheckType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1doLogout\/title","value":"AgoraChatServerCheckDoLogout"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1doLogout\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckDoLogout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1getDNSListFromServer\/title","value":"AgoraChatServerCheckGetDNSListFromServer"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1getDNSListFromServer\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckGetDNSListFromServer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1doLogin\/title","value":"AgoraChatServerCheckDoLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1doLogin\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckDoLogin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1accountValidation\/title","value":"AgoraChatServerCheckAccountValidation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1accountValidation\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1getTokenFromServer\/title","value":"AgoraChatServerCheckGetTokenFromServer"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1getTokenFromServer\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckGetTokenFromServer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType\/title","value":"AgoraChatServerCheckType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}