{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatthreadmanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatthreadmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message thread event callback protocol."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"title":"AgoraChatThreadManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatThreadManagerDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadCreate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadDestroy(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onUserKickOutOfChatThread(_:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate/onChatThreadUpdate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onChatThreadUpdate:"}],"role":"symbol","title":"onChatThreadUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the message thread is updated."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadUpdate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onchatthreadupdate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate/onChatThreadCreate(_:)":{"role":"symbol","title":"onChatThreadCreate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadCreate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a message thread is created."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadCreate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onChatThreadCreate:"}],"url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onchatthreadcreate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate/onChatThreadDestroy(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onChatThreadDestroy:"}],"role":"symbol","title":"onChatThreadDestroy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadDestroy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the message thread is destroyed."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadDestroy(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onchatthreaddestroy(_:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate":{"role":"symbol","title":"AgoraChatThreadManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"abstract":[{"type":"text","text":"The message thread event callback protocol."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate/onUserKickOutOfChatThread(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserKickOutOfChatThread:"}],"role":"symbol","title":"onUserKickOutOfChatThread(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserKickOutOfChatThread"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user is kicked out of the message thread."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onUserKickOutOfChatThread(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onuserkickoutofchatthread(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatThreadManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadCreate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadDestroy(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onUserKickOutOfChatThread(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadUpdate(_:)\/title","value":"onChatThreadUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadCreate(_:)\/title","value":"onChatThreadCreate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadCreate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadCreate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadDestroy(_:)\/title","value":"onChatThreadDestroy:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadDestroy(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadDestroy:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate\/title","value":"AgoraChatThreadManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onUserKickOutOfChatThread(_:)\/title","value":"onUserKickOutOfChatThread:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onUserKickOutOfChatThread(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserKickOutOfChatThread:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}