{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatUserInfoManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatuserinfomanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatuserinfomanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/fetchUserInfo(byId:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/fetchUserInfo(byId:type:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/updateOwn(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/updateOwnUserInfo(_:with:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatUserInfoManager"}],"title":"IAgoraChatUserInfoManager","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)IAgoraChatUserInfoManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"IAgoraChatUserInfoManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatUserInfoManager/fetchUserInfo(byId:type:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"fetchUserInfoById:type:completion:"}],"role":"symbol","title":"fetchUserInfo(byId:type:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byId"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the specific user information by user ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/fetchUserInfo(byId:type:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatuserinfomanager\/fetchuserinfo(byid:type:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatUserInfoManager/updateOwn(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updateOwnUserInfo:completion:"}],"role":"symbol","title":"updateOwn(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateOwn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatUserInfo","preciseIdentifier":"c:objc(cs)AgoraChatUserInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatUserInfo","preciseIdentifier":"c:objc(cs)AgoraChatUserInfo"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sets all of the user’s information."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/updateOwn(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatuserinfomanager\/updateown(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatUserInfoManager/fetchUserInfo(byId:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"fetchUserInfoById:completion:"}],"role":"symbol","title":"fetchUserInfo(byId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byId"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the user information by user ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/fetchUserInfo(byId:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatuserinfomanager\/fetchuserinfo(byid:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatUserInfoManager":{"role":"symbol","title":"IAgoraChatUserInfoManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatUserInfoManager"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatUserInfoManager"}],"url":"\/documentation\/agorachat\/iagorachatuserinfomanager"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatUserInfoManager/updateOwnUserInfo(_:with:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updateOwnUserInfo:withType:completion:"}],"role":"symbol","title":"updateOwnUserInfo(_:with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateOwnUserInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatUserInfoType","preciseIdentifier":"c:@E@AgoraChatUserInfoType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatUserInfo","preciseIdentifier":"c:objc(cs)AgoraChatUserInfo"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sets a specific user information of the user."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/updateOwnUserInfo(_:with:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatuserinfomanager\/updateownuserinfo(_:with:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IAgoraChatUserInfoManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IAgoraChatUserInfoManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IAgoraChatUserInfoManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/fetchUserInfo(byId:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/fetchUserInfo(byId:type:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/updateOwn(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatUserInfoManager\/updateOwnUserInfo(_:with:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatUserInfoManager"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1fetchUserInfo(byId:type:completion:)\/title","value":"fetchUserInfoById:type:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1fetchUserInfo(byId:type:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchUserInfoById:type:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1updateOwn(_:completion:)\/title","value":"updateOwnUserInfo:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1updateOwn(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateOwnUserInfo:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1fetchUserInfo(byId:completion:)\/title","value":"fetchUserInfoById:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1fetchUserInfo(byId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchUserInfoById:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager\/title","value":"IAgoraChatUserInfoManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatUserInfoManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1updateOwnUserInfo(_:with:completion:)\/title","value":"updateOwnUserInfo:withType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatUserInfoManager~1updateOwnUserInfo(_:with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateOwnUserInfo:withType:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}