{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatTranslateManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachattranslatemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachattranslatemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/getTranslationResult(byMsgId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/loadTranslateResults(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeAllTranslations()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeTranslations(byConversationId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeTranslations(byMsgId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/updateTranslate(_:conversationId:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatTranslateManager"}],"title":"IAgoraChatTranslateManager","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)IAgoraChatTranslateManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/updateTranslate(_:conversationId:)":{"navigatorTitle":[{"kind":"identifier","text":"updateTranslate:conversationId:"}],"role":"symbol","title":"updateTranslate(_:conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTranslate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatTranslationResult","preciseIdentifier":"c:objc(cs)AgoraChatTranslationResult"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set translate info of message"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/updateTranslate(_:conversationId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/updatetranslate(_:conversationid:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/removeTranslations(byMsgId:)":{"navigatorTitle":[{"kind":"identifier","text":"removeTranslationsByMsgId:"}],"role":"symbol","title":"removeTranslations(byMsgId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTranslations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byMsgId"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Remove translation infos by messageIds"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeTranslations(byMsgId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/removetranslations(bymsgid:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/loadTranslateResults(_:)":{"navigatorTitle":[{"kind":"identifier","text":"loadTranslateResults:"}],"role":"symbol","title":"loadTranslateResults(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTranslateResults"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!) -> ["},{"kind":"typeIdentifier","text":"AgoraChatTranslationResult","preciseIdentifier":"c:objc(cs)AgoraChatTranslationResult"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Gets the latest message translation information for the specified number of messages"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/loadTranslateResults(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/loadtranslateresults(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/removeTranslations(byConversationId:)":{"navigatorTitle":[{"kind":"identifier","text":"removeTranslationsByConversationId:"}],"role":"symbol","title":"removeTranslations(byConversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTranslations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byConversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Remove translation infos by conversationId"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeTranslations(byConversationId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/removetranslations(byconversationid:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/removeAllTranslations()":{"navigatorTitle":[{"kind":"identifier","text":"removeAllTranslations"}],"role":"symbol","title":"removeAllTranslations()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllTranslations"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Remove all translation infos"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeAllTranslations()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/removealltranslations()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager":{"role":"symbol","title":"IAgoraChatTranslateManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatTranslateManager"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}],"url":"\/documentation\/agorachat\/iagorachattranslatemanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatTranslateManager/getTranslationResult(byMsgId:)":{"navigatorTitle":[{"kind":"identifier","text":"getTranslationResultByMsgId:"}],"role":"symbol","title":"getTranslationResult(byMsgId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTranslationResult"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byMsgId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"AgoraChatTranslationResult","preciseIdentifier":"c:objc(cs)AgoraChatTranslationResult"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Get translate info by messageId"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/getTranslationResult(byMsgId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachattranslatemanager\/gettranslationresult(bymsgid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IAgoraChatTranslateManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/getTranslationResult(byMsgId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/loadTranslateResults(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeAllTranslations()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeTranslations(byConversationId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/removeTranslations(byMsgId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatTranslateManager\/updateTranslate(_:conversationId:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatTranslateManager"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1updateTranslate(_:conversationId:)\/title","value":"updateTranslate:conversationId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1updateTranslate(_:conversationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateTranslate:conversationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1removeTranslations(byMsgId:)\/title","value":"removeTranslationsByMsgId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1removeTranslations(byMsgId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTranslationsByMsgId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1loadTranslateResults(_:)\/title","value":"loadTranslateResults:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1loadTranslateResults(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTranslateResults:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1removeTranslations(byConversationId:)\/title","value":"removeTranslationsByConversationId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1removeTranslations(byConversationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTranslationsByConversationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1removeAllTranslations()\/title","value":"removeAllTranslations"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1removeAllTranslations()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllTranslations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager\/title","value":"IAgoraChatTranslateManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatTranslateManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1getTranslationResult(byMsgId:)\/title","value":"getTranslationResultByMsgId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatTranslateManager~1getTranslationResult(byMsgId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTranslationResultByMsgId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}