{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPushManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatpushmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatpushmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/noPushGroups","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/noPushUIds","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/pushOptions"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/clearRemindType(forConversation:conversationType:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/disableOfflinePushStart(_:end:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/enableOfflinePush()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPreferredNotificationLanguageCompletion(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushNotificationOptionsFromServer(completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushOptionsFromServerWithError(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushTemplate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentMode(for:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentMode(forConversation:conversationType:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentModeForAll(completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setPreferredNotificationLanguage(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setPushTemplate(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setSilentModeForAll(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setSilentModeForConversation(_:conversationType:params:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/update(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/update(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushDisplayName(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushDisplayName(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forGroups:disablePush:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forGroups:disablePush:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forUsers:disablePush:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forUsers:disablePush:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPushManager"}],"title":"IAgoraChatPushManager","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)IAgoraChatPushManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"IAgoraChatPushManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/update(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushDisplayStyle:completion:"}],"role":"symbol","title":"update(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sets the display style for the push notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/update(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/update(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/noPushGroups":{"navigatorTitle":[{"kind":"identifier","text":"noPushGroups"}],"deprecated":true,"role":"symbol","title":"noPushGroups","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPushGroups"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Gets the list of groups which have blocked the push notification."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -getSilentModeForConversations:completion: instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/noPushGroups","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/nopushgroups"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/updatePushService(forGroups:disablePush:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushServiceForGroups:disablePush:"}],"deprecated":true,"role":"symbol","title":"updatePushService(forGroups:disablePush:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePushService"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forGroups"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"disablePush"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"}],"abstract":[{"type":"text","text":"Sets wether to turn on or turn off the push notification."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -setSilentModeForConversation:conversationType: params:completion:  instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forGroups:disablePush:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/updatepushservice(forgroups:disablepush:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/updatePushService(forUsers:disablePush:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushServiceForUsers:disablePush:"}],"deprecated":true,"role":"symbol","title":"updatePushService(forUsers:disablePush:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePushService"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUsers"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"disablePush"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"}],"abstract":[{"type":"text","text":"Sets whether to receive push notification of the specific contacts."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -setSilentModeForConversation:conversationType: params:completion:  instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forUsers:disablePush:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/updatepushservice(forusers:disablepush:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/setPreferredNotificationLanguage(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"setPreferredNotificationLanguage:completion:"}],"role":"symbol","title":"setPreferredNotificationLanguage(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredNotificationLanguage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set the translation language for push messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setPreferredNotificationLanguage(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/setpreferrednotificationlanguage(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/pushOptions":{"navigatorTitle":[{"kind":"identifier","text":"pushOptions"}],"role":"symbol","title":"pushOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushOptions","preciseIdentifier":"c:objc(cs)AgoraChatPushOptions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The message push configuration options."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/pushOptions","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/pushoptions"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getSilentMode(forConversation:conversationType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getSilentModeForConversation:conversationType:completion:"}],"role":"symbol","title":"getSilentMode(forConversation:conversationType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatSilentModeResult","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Get conversation silent mode  message data."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentMode(forConversation:conversationType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getsilentmode(forconversation:conversationtype:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getPushNotificationOptionsFromServer(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getPushNotificationOptionsFromServerWithCompletion:"}],"role":"symbol","title":"getPushNotificationOptionsFromServer(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPushNotificationOptionsFromServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatPushOptions","preciseIdentifier":"c:objc(cs)AgoraChatPushOptions"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the push options from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushNotificationOptionsFromServer(completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getpushnotificationoptionsfromserver(completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/updatePushDisplayName(_:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushDisplayName:"}],"role":"symbol","title":"updatePushDisplayName(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePushDisplayName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets the display name of the push notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushDisplayName(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/updatepushdisplayname(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/update(_:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushDisplayStyle:"}],"role":"symbol","title":"update(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatPushDisplayStyle","preciseIdentifier":"c:@E@AgoraChatPushDisplayStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"}],"abstract":[{"type":"text","text":"Sets the display style for the push notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/update(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/update(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/setSilentModeForAll(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"setSilentModeForAll:completion:"}],"role":"symbol","title":"setSilentModeForAll(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSilentModeForAll"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParam","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeParam"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatSilentModeResult","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set global silent mode  message data."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setSilentModeForAll(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/setsilentmodeforall(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/updatePushService(forGroups:disablePush:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushServiceForGroups:disablePush:completion:"}],"deprecated":true,"role":"symbol","title":"updatePushService(forGroups:disablePush:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePushService"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forGroups"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"disablePush"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the display style for the push notification."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -setSilentModeForConversation:conversationType: params:completion:  instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forGroups:disablePush:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/updatepushservice(forgroups:disablepush:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getPreferredNotificationLanguageCompletion(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getPreferredNotificationLanguageCompletion:"}],"role":"symbol","title":"getPreferredNotificationLanguageCompletion(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPreferredNotificationLanguageCompletion"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Get the translation language for push messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPreferredNotificationLanguageCompletion(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getpreferrednotificationlanguagecompletion(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/noPushUIds":{"navigatorTitle":[{"kind":"identifier","text":"noPushUIds"}],"deprecated":true,"role":"symbol","title":"noPushUIds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPushUIds"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Gets the list of user ID which have blocked the push notification."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -getSilentModeForConversations:completion: instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/noPushUIds","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/nopushuids"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getSilentModeForAll(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getSilentModeForAllWithCompletion:"}],"role":"symbol","title":"getSilentModeForAll(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSilentModeForAll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatSilentModeResult","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Get global silent mode  message data."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentModeForAll(completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getsilentmodeforall(completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/enableOfflinePush()":{"navigatorTitle":[{"kind":"identifier","text":"enableOfflinePush"}],"deprecated":true,"role":"symbol","title":"enableOfflinePush()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOfflinePush"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"}],"abstract":[{"type":"text","text":"Turns on the push notification."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -setSilentModeForAll:completion:  instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/enableOfflinePush()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/enableofflinepush()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/setPushTemplate(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"setPushTemplate:completion:"}],"role":"symbol","title":"setPushTemplate(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPushTemplate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set the push template for offline push."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setPushTemplate(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/setpushtemplate(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager":{"role":"symbol","title":"IAgoraChatPushManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPushManager"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatPushManager"}],"url":"\/documentation\/agorachat\/iagorachatpushmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/updatePushService(forUsers:disablePush:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushServiceForUsers:disablePush:completion:"}],"deprecated":true,"role":"symbol","title":"updatePushService(forUsers:disablePush:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePushService"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUsers"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"disablePush"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets whether to receive the push notification of the contacts."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -setSilentModeForConversation:conversationType: params:completion:  instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forUsers:disablePush:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/updatepushservice(forusers:disablepush:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getSilentMode(for:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getSilentModeForConversations:completion:"}],"role":"symbol","title":"getSilentMode(for:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatConversation","preciseIdentifier":"c:objc(cs)AgoraChatConversation"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeResult","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeResult"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the silent mode data setting for multiple sessions."},{"type":"text","text":" "},{"type":"text","text":"Notice:A maximum of 20 pieces of data at a time.If it is not set or set to expire , it will not be returned in the result dictionary"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentMode(for:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getsilentmode(for:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/updatePushDisplayName(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"updatePushDisplayName:completion:"}],"role":"symbol","title":"updatePushDisplayName(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePushDisplayName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sets the display name of the push notification."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushDisplayName(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/updatepushdisplayname(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/clearRemindType(forConversation:conversationType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"clearRemindTypeForConversation:conversationType:completion:"}],"role":"symbol","title":"clearRemindType(forConversation:conversationType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearRemindType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forConversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatSilentModeResult","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Clear conversation  remind type for push messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/clearRemindType(forConversation:conversationType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/clearremindtype(forconversation:conversationtype:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getPushOptionsFromServerWithError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getPushOptionsFromServerWithError:"}],"role":"symbol","title":"getPushOptionsFromServerWithError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPushOptionsFromServerWithError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"AgoraChatPushOptions","preciseIdentifier":"c:objc(cs)AgoraChatPushOptions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the push options from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushOptionsFromServerWithError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getpushoptionsfromserverwitherror(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/disableOfflinePushStart(_:end:)":{"navigatorTitle":[{"kind":"identifier","text":"disableOfflinePushStart:end:"}],"deprecated":true,"role":"symbol","title":"disableOfflinePushStart(_:end:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableOfflinePushStart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"}],"abstract":[{"type":"text","text":"Turns off the push notification."},{"type":"text","text":" "},{"type":"text","text":"Deprecated. Please use  -setSilentModeForAll:completion:  instead."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/disableOfflinePushStart(_:end:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/disableofflinepushstart(_:end:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/getPushTemplate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getPushTemplate:"}],"role":"symbol","title":"getPushTemplate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPushTemplate"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the offline push template for Settings."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushTemplate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/getpushtemplate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPushManager/setSilentModeForConversation(_:conversationType:params:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"setSilentModeForConversation:conversationType:params:completion:"}],"role":"symbol","title":"setSilentModeForConversation(_:conversationType:params:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSilentModeForConversation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParam","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeParam"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatSilentModeResult","preciseIdentifier":"c:objc(cs)AgoraChatSilentModeResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set conversation silent mode  message data."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setSilentModeForConversation(_:conversationType:params:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpushmanager\/setsilentmodeforconversation(_:conversationtype:params:completion:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IAgoraChatPushManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IAgoraChatPushManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IAgoraChatPushManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/noPushGroups","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/noPushUIds","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/pushOptions"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/clearRemindType(forConversation:conversationType:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/disableOfflinePushStart(_:end:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/enableOfflinePush()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPreferredNotificationLanguageCompletion(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushNotificationOptionsFromServer(completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushOptionsFromServerWithError(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getPushTemplate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentMode(for:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentMode(forConversation:conversationType:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/getSilentModeForAll(completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setPreferredNotificationLanguage(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setPushTemplate(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setSilentModeForAll(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/setSilentModeForConversation(_:conversationType:params:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/update(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/update(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushDisplayName(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushDisplayName(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forGroups:disablePush:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forGroups:disablePush:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forUsers:disablePush:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPushManager\/updatePushService(forUsers:disablePush:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPushManager"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1update(_:completion:)\/title","value":"updatePushDisplayStyle:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1update(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushDisplayStyle:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1noPushGroups\/title","value":"noPushGroups"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1noPushGroups\/fragments","value":[{"kind":"identifier","text":"noPushGroups"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forGroups:disablePush:)\/title","value":"updatePushServiceForGroups:disablePush:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forGroups:disablePush:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushServiceForGroups:disablePush:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forUsers:disablePush:)\/title","value":"updatePushServiceForUsers:disablePush:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forUsers:disablePush:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushServiceForUsers:disablePush:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setPreferredNotificationLanguage(_:completion:)\/title","value":"setPreferredNotificationLanguage:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setPreferredNotificationLanguage(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredNotificationLanguage:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1pushOptions\/title","value":"pushOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1pushOptions\/fragments","value":[{"kind":"identifier","text":"pushOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getSilentMode(forConversation:conversationType:completion:)\/title","value":"getSilentModeForConversation:conversationType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getSilentMode(forConversation:conversationType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSilentModeForConversation:conversationType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPushNotificationOptionsFromServer(completion:)\/title","value":"getPushNotificationOptionsFromServerWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPushNotificationOptionsFromServer(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPushNotificationOptionsFromServerWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushDisplayName(_:)\/title","value":"updatePushDisplayName:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushDisplayName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushDisplayName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1update(_:)\/title","value":"updatePushDisplayStyle:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1update(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushDisplayStyle:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setSilentModeForAll(_:completion:)\/title","value":"setSilentModeForAll:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setSilentModeForAll(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSilentModeForAll:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forGroups:disablePush:completion:)\/title","value":"updatePushServiceForGroups:disablePush:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forGroups:disablePush:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushServiceForGroups:disablePush:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPreferredNotificationLanguageCompletion(_:)\/title","value":"getPreferredNotificationLanguageCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPreferredNotificationLanguageCompletion(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPreferredNotificationLanguageCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1noPushUIds\/title","value":"noPushUIds"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1noPushUIds\/fragments","value":[{"kind":"identifier","text":"noPushUIds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getSilentModeForAll(completion:)\/title","value":"getSilentModeForAllWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getSilentModeForAll(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSilentModeForAllWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1enableOfflinePush()\/title","value":"enableOfflinePush"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1enableOfflinePush()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableOfflinePush"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setPushTemplate(_:completion:)\/title","value":"setPushTemplate:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setPushTemplate(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPushTemplate:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager\/title","value":"IAgoraChatPushManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatPushManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forUsers:disablePush:completion:)\/title","value":"updatePushServiceForUsers:disablePush:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushService(forUsers:disablePush:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushServiceForUsers:disablePush:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getSilentMode(for:completion:)\/title","value":"getSilentModeForConversations:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getSilentMode(for:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSilentModeForConversations:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushDisplayName(_:completion:)\/title","value":"updatePushDisplayName:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1updatePushDisplayName(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePushDisplayName:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1clearRemindType(forConversation:conversationType:completion:)\/title","value":"clearRemindTypeForConversation:conversationType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1clearRemindType(forConversation:conversationType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearRemindTypeForConversation:conversationType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPushOptionsFromServerWithError(_:)\/title","value":"getPushOptionsFromServerWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPushOptionsFromServerWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPushOptionsFromServerWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1disableOfflinePushStart(_:end:)\/title","value":"disableOfflinePushStart:end:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1disableOfflinePushStart(_:end:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableOfflinePushStart:end:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPushTemplate(_:)\/title","value":"getPushTemplate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1getPushTemplate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPushTemplate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setSilentModeForConversation(_:conversationType:params:completion:)\/title","value":"setSilentModeForConversation:conversationType:params:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPushManager~1setSilentModeForConversation(_:conversationType:params:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSilentModeForConversation:conversationType:params:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}