{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartH"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/kpushnodisturbingstarth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/kpushnodisturbingstarth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/kPushNoDisturbingStartH","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartH"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"kPushNoDisturbingStartH","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:AgoraChatPushOptions.h@372@macro@kPushNoDisturbingStartH","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"kPushNoDisturbingStartH"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/kPushNoDisturbingStartH":{"role":"symbol","title":"kPushNoDisturbingStartH","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartH"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/kPushNoDisturbingStartH","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kPushNoDisturbingStartH"}],"url":"\/documentation\/agorachat\/kpushnodisturbingstarth"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kPushNoDisturbingStartH"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartH"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1kPushNoDisturbingStartH\/title","value":"kPushNoDisturbingStartH"}],"traits":[{"interfaceLanguage":"occ"}]}]}