{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","text":"AgoraChatMultiDevicesEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"threadId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aThreadId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aExt"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multideviceschatthreadeventdidreceive(_:threadid:ext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multideviceschatthreadeventdidreceive(_:threadid:ext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The multi-device event callback of thread"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:threadId:ext:"}],"role":"symbol","title":"multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"threadId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatMultiDevicesDelegate(im)multiDevicesChatThreadEventDidReceive:threadId:ext:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate":{"role":"symbol","title":"AgoraChatMultiDevicesDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:threadId:ext:"}],"role":"symbol","title":"multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"threadId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The multi-device event callback of thread"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multideviceschatthreadeventdidreceive(_:threadid:ext:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"multiDevicesChatThreadEventDidReceive:threadId:ext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:threadId:ext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent","text":"AgoraChatMultiDevicesEvent"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aEvent"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aThreadId"},{"kind":"text","text":" "},{"kind":"identifier","text":"ext:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aExt"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate\/title","value":"AgoraChatMultiDevicesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesChatThreadEventDidReceive(_:threadId:ext:)\/title","value":"multiDevicesChatThreadEventDidReceive:threadId:ext:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesChatThreadEventDidReceive(_:threadId:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:threadId:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}