{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"undisturbData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callback to other devices after setting Do Not Disturb for a single session after enabling multiple devices"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}],"role":"symbol","title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatMultiDevicesDelegate(im)multiDevicesUndisturbEventNotifyFormOtherDeviceData:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}],"role":"symbol","title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Callback to other devices after setting Do Not Disturb for a single session after enabling multiple devices"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate":{"role":"symbol","title":"AgoraChatMultiDevicesDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"undisturbData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/title","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate\/title","value":"AgoraChatMultiDevicesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}