{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGroupFileList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aGroupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageNumber"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aPageNum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aPageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCompletionBlock"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile","preciseIdentifier":"c:objc(cs)AgoraChatGroupSharedFile","text":"AgoraChatGroupSharedFile"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an asynchronous method."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatgroupmanager\/getgroupfilelist(withid:pagenumber:pagesize:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatgroupmanager\/getgroupfilelist(withid:pagenumber:pagesize:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager\/getGroupFileList(withId:pageNumber:pageSize:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the share files of group from the server."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getGroupFileListWithId:pageNumber:pageSize:completion:"}],"role":"symbol","title":"getGroupFileList(withId:pageNumber:pageSize:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGroupFileList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatGroupSharedFile","preciseIdentifier":"c:objc(cs)AgoraChatGroupSharedFile"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatGroupManager(im)getGroupFileListWithId:pageNumber:pageSize:completion:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatGroupManager/getGroupFileList(withId:pageNumber:pageSize:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getGroupFileListWithId:pageNumber:pageSize:completion:"}],"role":"symbol","title":"getGroupFileList(withId:pageNumber:pageSize:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getGroupFileList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatGroupSharedFile","preciseIdentifier":"c:objc(cs)AgoraChatGroupSharedFile"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the share files of group from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager\/getGroupFileList(withId:pageNumber:pageSize:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatgroupmanager\/getgroupfilelist(withid:pagenumber:pagesize:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatGroupManager":{"role":"symbol","title":"IAgoraChatGroupManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatGroupManager"}],"abstract":[{"type":"text","text":"The group operations."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatGroupManager"}],"url":"\/documentation\/agorachat\/iagorachatgroupmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile":{"role":"symbol","title":"AgoraChatGroupSharedFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupSharedFile"}],"abstract":[{"type":"text","text":"The group shared file object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getGroupFileListWithId:pageNumber:pageSize:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGroupFileListWithId:pageNumber:pageSize:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getGroupFileListWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aGroupId"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aPageNum"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aPageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<AgoraChatGroupSharedFile *> *, AgoraChatError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)AgoraChatError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aCompletionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager~1getGroupFileList(withId:pageNumber:pageSize:completion:)\/title","value":"getGroupFileListWithId:pageNumber:pageSize:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager~1getGroupFileList(withId:pageNumber:pageSize:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getGroupFileListWithId:pageNumber:pageSize:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager\/title","value":"IAgoraChatGroupManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatGroupManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile\/title","value":"AgoraChatGroupSharedFile"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}