{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroombekickedreason\/destroyed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroombekickedreason\/destroyed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason\/destroyed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removed by chatroom owner type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyed"}],"title":"AgoraChatroomBeKickedReason.destroyed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatroomBeKickedReason@AgoraChatroomBeKickedReasonDestroyed","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonDestroyed"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomBeKickedReason":{"role":"symbol","title":"AgoraChatroomBeKickedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomBeKickedReason"}],"abstract":[{"type":"text","text":"The casuse type for kicking out from a chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomBeKickedReason"}],"url":"\/documentation\/agorachat\/agorachatroombekickedreason"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomBeKickedReason/destroyed":{"role":"symbol","title":"AgoraChatroomBeKickedReason.destroyed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroyed"}],"abstract":[{"type":"text","text":"Removed by chatroom owner type"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason\/destroyed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonDestroyed"}],"url":"\/documentation\/agorachat\/agorachatroombekickedreason\/destroyed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatroomBeKickedReasonDestroyed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonDestroyed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonDestroyed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason\/title","value":"AgoraChatroomBeKickedReason"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomBeKickedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason~1destroyed\/title","value":"AgoraChatroomBeKickedReasonDestroyed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason~1destroyed\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonDestroyed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}