{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup","text":"AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedAdmin"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupadminlistdidupdate(_:addedadmin:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupadminlistdidupdate(_:addedadmin:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:addedAdmin:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when a group member is added to the admin list."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"groupAdminListDidUpdate:addedAdmin:"}],"role":"symbol","title":"groupAdminListDidUpdate(_:addedAdmin:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatGroupManagerDelegate(im)groupAdminListDidUpdate:addedAdmin:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate":{"role":"symbol","title":"AgoraChatGroupManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}],"abstract":[{"type":"text","text":"The group manager delegates."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupManagerDelegate/groupAdminListDidUpdate(_:addedAdmin:)":{"navigatorTitle":[{"kind":"identifier","text":"groupAdminListDidUpdate:addedAdmin:"}],"role":"symbol","title":"groupAdminListDidUpdate(_:addedAdmin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a group member is added to the admin list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupManagerDelegate\/groupAdminListDidUpdate(_:addedAdmin:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatgroupmanagerdelegate\/groupadminlistdidupdate(_:addedadmin:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup":{"role":"symbol","title":"AgoraChatGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"}],"abstract":[{"type":"text","text":"The group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroup"}],"url":"\/documentation\/agorachat\/agorachatgroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupAdminListDidUpdate:addedAdmin:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupAdminListDidUpdate:addedAdmin:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupAdminListDidUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup","text":"AgoraChatGroup"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aGroup"},{"kind":"text","text":" "},{"kind":"identifier","text":"addedAdmin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aAdmin"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate\/title","value":"AgoraChatGroupManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAdminListDidUpdate(_:addedAdmin:)\/title","value":"groupAdminListDidUpdate:addedAdmin:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupManagerDelegate~1groupAdminListDidUpdate(_:addedAdmin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupAdminListDidUpdate:addedAdmin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/title","value":"AgoraChatGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroup"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}