{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"beRemoved"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroombekickedreason\/beremoved"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroombekickedreason\/beremoved"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason\/beRemoved","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"beRemoved"}],"title":"AgoraChatroomBeKickedReason.beRemoved","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatroomBeKickedReason@AgoraChatroomBeKickedReasonBeRemoved","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonBeRemoved"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomBeKickedReason":{"role":"symbol","title":"AgoraChatroomBeKickedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomBeKickedReason"}],"abstract":[{"type":"text","text":"The casuse type for kicking out from a chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomBeKickedReason"}],"url":"\/documentation\/agorachat\/agorachatroombekickedreason"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomBeKickedReason/beRemoved":{"role":"symbol","title":"AgoraChatroomBeKickedReason.beRemoved","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"beRemoved"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomBeKickedReason\/beRemoved","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonBeRemoved"}],"url":"\/documentation\/agorachat\/agorachatroombekickedreason\/beremoved"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatroomBeKickedReasonBeRemoved"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonBeRemoved"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonBeRemoved"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason\/title","value":"AgoraChatroomBeKickedReason"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomBeKickedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason~1beRemoved\/title","value":"AgoraChatroomBeKickedReasonBeRemoved"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomBeKickedReason~1beRemoved\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomBeKickedReasonBeRemoved"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}