{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatrecallmessageinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatrecallmessageinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message recall information object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}],"title":"AgoraChatRecallMessageInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatRecallMessageInfo","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo\/recallBy","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo\/recallMessage"]}],"references":{"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRecallMessageInfo/recallBy":{"role":"symbol","title":"recallBy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recallBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Users who recall messages"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo\/recallBy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recallBy"}],"url":"\/documentation\/agorachat\/agorachatrecallmessageinfo\/recallby"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRecallMessageInfo/recallMessage":{"role":"symbol","title":"recallMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recallMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"}],"abstract":[{"type":"text","text":"A recall message"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo\/recallMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recallMessage"}],"url":"\/documentation\/agorachat\/agorachatrecallmessageinfo\/recallmessage"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRecallMessageInfo":{"role":"symbol","title":"AgoraChatRecallMessageInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}],"abstract":[{"type":"text","text":"The message recall information object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}],"url":"\/documentation\/agorachat\/agorachatrecallmessageinfo"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatRecallMessageInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo\/recallBy","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRecallMessageInfo\/recallMessage"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRecallMessageInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRecallMessageInfo~1recallBy\/title","value":"recallBy"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRecallMessageInfo~1recallBy\/fragments","value":[{"kind":"identifier","text":"recallBy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRecallMessageInfo~1recallMessage\/title","value":"recallMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRecallMessageInfo~1recallMessage\/fragments","value":[{"kind":"identifier","text":"recallMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRecallMessageInfo\/title","value":"AgoraChatRecallMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRecallMessageInfo\/fragments","value":[{"kind":"identifier","text":"AgoraChatRecallMessageInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}