{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroommanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The callbacks of chatroom."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"title":"AgoraChatroomManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatroomManagerDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:addedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:removedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAnnouncementDidUpdate(_:announcement:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAttributesDidRemoved(_:attributes:from:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAttributesDidUpdated(_:attributeMap:from:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomMuteListDidUpdate(_:removedMutedMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomSpecificationDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didDismiss(from:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveKicked(from:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserJoinedChatroom(_:username:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserLeavedChatroom(_:username:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/userDidJoin(_:user:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/userDidLeave(_:user:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/userDidJoin(_:user:)":{"role":"symbol","title":"userDidJoin(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidJoin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A user joined a chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/userDidJoin(_:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidJoinChatroom:user:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/userdidjoin(_:user:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)":{"navigatorTitle":[{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}],"role":"symbol","title":"chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"muteExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Users are added to the mute list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroommutelistdidupdate(_:addedmutedmembers:muteexpire:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAttributesDidUpdated(_:attributeMap:from:)":{"role":"symbol","title":"chatroomAttributesDidUpdated(_:attributeMap:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAttributesDidUpdated"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeMap"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The announcement is updated."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAttributesDidUpdated(_:attributeMap:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAttributesDidUpdated:attributeMap:from:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomattributesdidupdated(_:attributemap:from:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/didDismiss(from:reason:)":{"role":"symbol","title":"didDismiss(from:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatroomBeKickedReason","preciseIdentifier":"c:@E@AgoraChatroomBeKickedReason"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user is dismissed from a chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didDismiss(from:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissFromChatroom:reason:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/diddismiss(from:reason:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)":{"role":"symbol","title":"chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAllMemberMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Whether group members are all muted."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAllMemberMuteChanged:isAllMemberMuted:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomallmembermutechanged(_:isallmembermuted:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomMuteListDidUpdate(_:removedMutedMembers:)":{"role":"symbol","title":"chatroomMuteListDidUpdate(_:removedMutedMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomMuteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedMutedMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Users are removed from the mute list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomMuteListDidUpdate(_:removedMutedMembers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomMuteListDidUpdate:removedMutedMembers:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroommutelistdidupdate(_:removedmutedmembers:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAnnouncementDidUpdate(_:announcement:)":{"navigatorTitle":[{"kind":"identifier","text":"chatroomAnnouncementDidUpdate:announcement:"}],"role":"symbol","title":"chatroomAnnouncementDidUpdate(_:announcement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAnnouncementDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The announcement is updated."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAnnouncementDidUpdate(_:announcement:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomannouncementdidupdate(_:announcement:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/didReceiveUserLeavedChatroom(_:username:)":{"deprecated":true,"role":"symbol","title":"didReceiveUserLeavedChatroom(_:username:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveUserLeavedChatroom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A user leaved the chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserLeavedChatroom(_:username:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveUserLeavedChatroom:username:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/didreceiveuserleavedchatroom(_:username:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAttributesDidRemoved(_:attributes:from:)":{"role":"symbol","title":"chatroomAttributesDidRemoved(_:attributes:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAttributesDidRemoved"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The announcement is updated."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAttributesDidRemoved(_:attributes:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAttributesDidRemoved:attributes:from:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomattributesdidremoved(_:attributes:from:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomSpecificationDidUpdate(_:)":{"role":"symbol","title":"chatroomSpecificationDidUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomSpecificationDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the chatroom specification update,Need to call for a chat room details API (IAgoraChatroomManager. H: getChatroomSpecificationFromServerWithId) to get the latest information chat room"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomSpecificationDidUpdate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomSpecificationDidUpdate:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomspecificationdidupdate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAdminListDidUpdate(_:removedAdmin:)":{"role":"symbol","title":"chatroomAdminListDidUpdate(_:removedAdmin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A user is removed from the admin list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:removedAdmin:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAdminListDidUpdate:removedAdmin:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomadminlistdidupdate(_:removedadmin:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/userDidLeave(_:user:)":{"navigatorTitle":[{"kind":"identifier","text":"userDidLeaveChatroom:user:"}],"role":"symbol","title":"userDidLeave(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user leaves a chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/userDidLeave(_:user:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/userdidleave(_:user:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)":{"role":"symbol","title":"chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomWhiteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedWhiteListMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Users are added to the allowlist."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomWhiteListDidUpdate:addedWhiteListMembers:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomwhitelistdidupdate(_:addedwhitelistmembers:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomAdminListDidUpdate(_:addedAdmin:)":{"role":"symbol","title":"chatroomAdminListDidUpdate(_:addedAdmin:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomAdminListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedAdmin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A user is added to the admin list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:addedAdmin:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomAdminListDidUpdate:addedAdmin:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomadminlistdidupdate(_:addedadmin:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/didReceiveUserJoinedChatroom(_:username:)":{"deprecated":true,"role":"symbol","title":"didReceiveUserJoinedChatroom(_:username:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user joins a chat room"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserJoinedChatroom(_:username:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveUserJoinedChatroom:username:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/didreceiveuserjoinedchatroom(_:username:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate":{"role":"symbol","title":"AgoraChatroomManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"abstract":[{"type":"text","text":"The callbacks of chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/didReceiveKicked(from:reason:)":{"deprecated":true,"role":"symbol","title":"didReceiveKicked(from:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveKicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatroomBeKickedReason","preciseIdentifier":"c:@E@AgoraChatroomBeKickedReason"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"User was kicked out from the chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveKicked(from:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveKickedFromChatroom:reason:"}],"url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/didreceivekicked(from:reason:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomOwnerDidUpdate(_:newOwner:oldOwner:)":{"navigatorTitle":[{"kind":"identifier","text":"chatroomOwnerDidUpdate:newOwner:oldOwner:"}],"role":"symbol","title":"chatroomOwnerDidUpdate(_:newOwner:oldOwner:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomOwnerDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The owner is updated."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomOwnerDidUpdate(_:newOwner:oldOwner:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomownerdidupdate(_:newowner:oldowner:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroomManagerDelegate/chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)":{"navigatorTitle":[{"kind":"identifier","text":"chatroomWhiteListDidUpdate:removedWhiteListMembers:"}],"role":"symbol","title":"chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomWhiteListDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatroom","preciseIdentifier":"c:objc(cs)AgoraChatroom"},{"kind":"text","text":", "},{"kind":"externalParam","text":"removedWhiteListMembers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Users are removed from the allowlist."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatroommanagerdelegate\/chatroomwhitelistdidupdate(_:removedwhitelistmembers:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatroomManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:addedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAdminListDidUpdate(_:removedAdmin:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAllMemberMuteChanged(_:isAllMemberMuted:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAnnouncementDidUpdate(_:announcement:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAttributesDidRemoved(_:attributes:from:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomAttributesDidUpdated(_:attributeMap:from:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomMuteListDidUpdate(_:removedMutedMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomSpecificationDidUpdate(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didDismiss(from:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveKicked(from:reason:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserJoinedChatroom(_:username:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/didReceiveUserLeavedChatroom(_:username:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/userDidJoin(_:user:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroomManagerDelegate\/userDidLeave(_:user:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroomManagerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1userDidJoin(_:user:)\/title","value":"userDidJoinChatroom:user:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1userDidJoin(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidJoinChatroom:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/title","value":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomMuteListDidUpdate(_:addedMutedMembers:muteExpire:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:addedMutedMembers:muteExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAttributesDidUpdated(_:attributeMap:from:)\/title","value":"chatroomAttributesDidUpdated:attributeMap:from:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAttributesDidUpdated(_:attributeMap:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAttributesDidUpdated:attributeMap:from:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didDismiss(from:reason:)\/title","value":"didDismissFromChatroom:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didDismiss(from:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissFromChatroom:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAllMemberMuteChanged(_:isAllMemberMuted:)\/title","value":"chatroomAllMemberMuteChanged:isAllMemberMuted:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAllMemberMuteChanged(_:isAllMemberMuted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAllMemberMuteChanged:isAllMemberMuted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomMuteListDidUpdate(_:removedMutedMembers:)\/title","value":"chatroomMuteListDidUpdate:removedMutedMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomMuteListDidUpdate(_:removedMutedMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomMuteListDidUpdate:removedMutedMembers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAnnouncementDidUpdate(_:announcement:)\/title","value":"chatroomAnnouncementDidUpdate:announcement:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAnnouncementDidUpdate(_:announcement:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAnnouncementDidUpdate:announcement:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveUserLeavedChatroom(_:username:)\/title","value":"didReceiveUserLeavedChatroom:username:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveUserLeavedChatroom(_:username:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveUserLeavedChatroom:username:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAttributesDidRemoved(_:attributes:from:)\/title","value":"chatroomAttributesDidRemoved:attributes:from:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAttributesDidRemoved(_:attributes:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAttributesDidRemoved:attributes:from:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomSpecificationDidUpdate(_:)\/title","value":"chatroomSpecificationDidUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomSpecificationDidUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomSpecificationDidUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAdminListDidUpdate(_:removedAdmin:)\/title","value":"chatroomAdminListDidUpdate:removedAdmin:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAdminListDidUpdate(_:removedAdmin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAdminListDidUpdate:removedAdmin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1userDidLeave(_:user:)\/title","value":"userDidLeaveChatroom:user:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1userDidLeave(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidLeaveChatroom:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)\/title","value":"chatroomWhiteListDidUpdate:addedWhiteListMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomWhiteListDidUpdate(_:addedWhiteListMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomWhiteListDidUpdate:addedWhiteListMembers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAdminListDidUpdate(_:addedAdmin:)\/title","value":"chatroomAdminListDidUpdate:addedAdmin:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomAdminListDidUpdate(_:addedAdmin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomAdminListDidUpdate:addedAdmin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveUserJoinedChatroom(_:username:)\/title","value":"didReceiveUserJoinedChatroom:username:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveUserJoinedChatroom(_:username:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveUserJoinedChatroom:username:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/title","value":"AgoraChatroomManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatroomManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveKicked(from:reason:)\/title","value":"didReceiveKickedFromChatroom:reason:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1didReceiveKicked(from:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveKickedFromChatroom:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomOwnerDidUpdate(_:newOwner:oldOwner:)\/title","value":"chatroomOwnerDidUpdate:newOwner:oldOwner:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomOwnerDidUpdate(_:newOwner:oldOwner:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomOwnerDidUpdate:newOwner:oldOwner:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)\/title","value":"chatroomWhiteListDidUpdate:removedWhiteListMembers:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroomManagerDelegate~1chatroomWhiteListDidUpdate(_:removedWhiteListMembers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatroomWhiteListDidUpdate:removedWhiteListMembers:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}