{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushRemindType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpushremindtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpushremindtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The remind type of push message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushRemindType"}],"title":"AgoraChatPushRemindType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatPushRemindType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushRemindType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/all","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/mentionOnly","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/none"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType":{"role":"symbol","title":"AgoraChatPushRemindType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushRemindType"}],"abstract":[{"type":"text","text":"The remind type of push message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushRemindType"}],"url":"\/documentation\/agorachat\/agorachatpushremindtype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatpushremindtype\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatpushremindtype\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType/all":{"role":"symbol","title":"AgoraChatPushRemindType.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushRemindTypeAll"}],"url":"\/documentation\/agorachat\/agorachatpushremindtype\/all"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatpushremindtype\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType/none":{"role":"symbol","title":"AgoraChatPushRemindType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"Only @me messages are remind."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushRemindTypeNone"}],"url":"\/documentation\/agorachat\/agorachatpushremindtype\/none"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType/mentionOnly":{"role":"symbol","title":"AgoraChatPushRemindType.mentionOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionOnly"}],"abstract":[{"type":"text","text":"All messages are remind."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/mentionOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushRemindTypeMentionOnly"}],"url":"\/documentation\/agorachat\/agorachatpushremindtype\/mentiononly"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatPushRemindType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushRemindType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatPushRemindType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/all","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/mentionOnly","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType\/none"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushRemindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType\/title","value":"AgoraChatPushRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushRemindType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType~1all\/title","value":"AgoraChatPushRemindTypeAll"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType~1all\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushRemindTypeAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType~1none\/title","value":"AgoraChatPushRemindTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType~1none\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushRemindTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType~1mentionOnly\/title","value":"AgoraChatPushRemindTypeMentionOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType~1mentionOnly\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushRemindTypeMentionOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}