{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The SDK setting options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatOptions"}],"title":"AgoraChatOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatOptions","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/init(appkey:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/apnsCertName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/appkey","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/area","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoAcceptFriendInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoAcceptGroupInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoDownloadThumbnail","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/canChatroomOwnerLeave","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/deleteMessagesOnLeaveChatroom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/deleteMessagesOnLeaveGroup","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableConsoleLog","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableDeliveryAck","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableFpa","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableRequireReadAck","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableStatistics","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoAcceptFriendInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoAcceptGroupInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoDownloadThumbnail","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoLogin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoTransferMessageAttachments","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isChatroomOwnerLeaveAllowed","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isDeleteMessagesWhenExitChatRoom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isDeleteMessagesWhenExitGroup","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/logLevel","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/pushKitCertName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/sortMessageByServerTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/usingHttpsOnly"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/enableFpa":{"role":"symbol","title":"enableFpa","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableFpa"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable fpa feature. The default value is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableFpa","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableFpa"}],"url":"\/documentation\/agorachat\/agorachatoptions\/enablefpa"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/chatPort":{"role":"symbol","title":"chatPort","fragments":[{"kind":"identifier","text":"chatPort"}],"abstract":[{"type":"text","text":"The chat server port."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/chatPort","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatoptions\/chatport"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/restServer":{"role":"symbol","title":"restServer","fragments":[{"kind":"identifier","text":"restServer"}],"abstract":[{"type":"text","text":"The REST server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/restServer","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatoptions\/restserver"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/autoDownloadThumbnail":{"role":"symbol","title":"autoDownloadThumbnail","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoDownloadThumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically download image or video thumbnails and voice messages. The default value is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoDownloadThumbnail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoDownloadThumbnail"}],"url":"\/documentation\/agorachat\/agorachatoptions\/autodownloadthumbnail"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/sortMessageByServerTime":{"role":"symbol","title":"sortMessageByServerTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sortMessageByServerTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to sort messages by server received time when loading message from database. The default value is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/sortMessageByServerTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sortMessageByServerTime"}],"url":"\/documentation\/agorachat\/agorachatoptions\/sortmessagebyservertime"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/enableDnsConfig":{"role":"symbol","title":"enableDnsConfig","fragments":[{"kind":"identifier","text":"enableDnsConfig"}],"abstract":[{"type":"text","text":"Whether to allow using DNS. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableDnsConfig","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatoptions\/enablednsconfig"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isChatroomOwnerLeaveAllowed":{"deprecated":true,"role":"symbol","title":"isChatroomOwnerLeaveAllowed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatroomOwnerLeaveAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"if allow chat room’s owner can leave the chat room. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isChatroomOwnerLeaveAllowed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChatroomOwnerLeaveAllowed"}],"url":"\/documentation\/agorachat\/agorachatoptions\/ischatroomownerleaveallowed"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/appkey":{"role":"symbol","title":"appkey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appkey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The app key, which is the unique identifier of the project."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/appkey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appkey"}],"url":"\/documentation\/agorachat\/agorachatoptions\/appkey"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isAutoDownloadThumbnail":{"deprecated":true,"role":"symbol","title":"isAutoDownloadThumbnail","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoDownloadThumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically download thumbnail of image&video and audio. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoDownloadThumbnail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAutoDownloadThumbnail"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isautodownloadthumbnail"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isAutoAcceptFriendInvitation":{"deprecated":true,"role":"symbol","title":"isAutoAcceptFriendInvitation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoAcceptFriendInvitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically approve friend request. The default value is NO."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoAcceptFriendInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAutoAcceptFriendInvitation"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isautoacceptfriendinvitation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isAutoAcceptGroupInvitation":{"deprecated":true,"role":"symbol","title":"isAutoAcceptGroupInvitation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoAcceptGroupInvitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically accept group invitation. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoAcceptGroupInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAutoAcceptGroupInvitation"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isautoacceptgroupinvitation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/autoAcceptFriendInvitation":{"role":"symbol","title":"autoAcceptFriendInvitation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoAcceptFriendInvitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically approve contact request. The default value is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoAcceptFriendInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoAcceptFriendInvitation"}],"url":"\/documentation\/agorachat\/agorachatoptions\/autoacceptfriendinvitation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/chatServer":{"role":"symbol","title":"chatServer","fragments":[{"kind":"identifier","text":"chatServer"}],"abstract":[{"type":"text","text":"The chat server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/chatServer","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatoptions\/chatserver"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/canChatroomOwnerLeave":{"role":"symbol","title":"canChatroomOwnerLeave","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canChatroomOwnerLeave"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to allow the chatroom owner leave the room. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/canChatroomOwnerLeave","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canChatroomOwnerLeave"}],"url":"\/documentation\/agorachat\/agorachatoptions\/canchatroomownerleave"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/deleteMessagesOnLeaveChatroom":{"role":"symbol","title":"deleteMessagesOnLeaveChatroom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessagesOnLeaveChatroom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to delete all the chat room messages when leaving the chat room. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/deleteMessagesOnLeaveChatroom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteMessagesOnLeaveChatroom"}],"url":"\/documentation\/agorachat\/agorachatoptions\/deletemessagesonleavechatroom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/autoAcceptGroupInvitation":{"role":"symbol","title":"autoAcceptGroupInvitation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoAcceptGroupInvitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically accept group invitation. The default value is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoAcceptGroupInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoAcceptGroupInvitation"}],"url":"\/documentation\/agorachat\/agorachatoptions\/autoacceptgroupinvitation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/usingHttpsOnly":{"role":"symbol","title":"usingHttpsOnly","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usingHttpsOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to only use the HTTPS protocol. The default value is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/usingHttpsOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"usingHttpsOnly"}],"url":"\/documentation\/agorachat\/agorachatoptions\/usinghttpsonly"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/area":{"role":"symbol","title":"area","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"area"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AreaCode","preciseIdentifier":"c:@E@AreaCode"}],"abstract":[{"type":"text","text":"The area code."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/area","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"area"}],"url":"\/documentation\/agorachat\/agorachatoptions\/area"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/enableStatistics":{"role":"symbol","title":"enableStatistics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable message statistics. The default value is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableStatistics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableStatistics"}],"url":"\/documentation\/agorachat\/agorachatoptions\/enablestatistics"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/logLevel":{"role":"symbol","title":"logLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatLogLevel","preciseIdentifier":"c:@E@AgoraChatLogLevel"}],"abstract":[{"type":"text","text":"The log output level. The default value is AgoraChatLogLevelDebug, which means all log levels."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/logLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"url":"\/documentation\/agorachat\/agorachatoptions\/loglevel"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isAutoTransferMessageAttachments":{"role":"symbol","title":"isAutoTransferMessageAttachments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoTransferMessageAttachments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically upload or download the attachment in the message. The default value is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoTransferMessageAttachments","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAutoTransferMessageAttachments"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isautotransfermessageattachments"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/apnsCertName":{"role":"symbol","title":"apnsCertName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apnsCertName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The certificate name of Apple Push Notification Service."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/apnsCertName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apnsCertName"}],"url":"\/documentation\/agorachat\/agorachatoptions\/apnscertname"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/dnsURL":{"role":"symbol","title":"dnsURL","fragments":[{"kind":"identifier","text":"dnsURL"}],"abstract":[{"type":"text","text":"The DNS url."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/dnsURL","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatoptions\/dnsurl"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/enableRequireReadAck":{"role":"symbol","title":"enableRequireReadAck","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableRequireReadAck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether need to receive the message read receipt. The default value is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableRequireReadAck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableRequireReadAck"}],"url":"\/documentation\/agorachat\/agorachatoptions\/enablerequirereadack"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/deleteMessagesOnLeaveGroup":{"role":"symbol","title":"deleteMessagesOnLeaveGroup","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessagesOnLeaveGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to delete all the group messages when leaving the group. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/deleteMessagesOnLeaveGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteMessagesOnLeaveGroup"}],"url":"\/documentation\/agorachat\/agorachatoptions\/deletemessagesonleavegroup"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/init(appkey:)":{"role":"symbol","title":"init(appkey:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appkey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets a SDK setting options instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/init(appkey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"optionsWithAppkey:"}],"url":"\/documentation\/agorachat\/agorachatoptions\/init(appkey:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/enableConsoleLog":{"role":"symbol","title":"enableConsoleLog","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableConsoleLog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to print logs on Console. The default value is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableConsoleLog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableConsoleLog"}],"url":"\/documentation\/agorachat\/agorachatoptions\/enableconsolelog"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/enableDeliveryAck":{"role":"symbol","title":"enableDeliveryAck","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDeliveryAck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to send the message delivery receipt. The default value is "},{"type":"codeVoice","code":"NO"},{"type":"text","text":". If you set it to "},{"type":"codeVoice","code":"YES"},{"type":"text","text":", the SDK automatically send a delivery receipt when you receive a chat message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableDeliveryAck","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableDeliveryAck"}],"url":"\/documentation\/agorachat\/agorachatoptions\/enabledeliveryack"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/pushKitCertName":{"role":"symbol","title":"pushKitCertName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushKitCertName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The certificate name of Apple PushKit Service."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/pushKitCertName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushKitCertName"}],"url":"\/documentation\/agorachat\/agorachatoptions\/pushkitcertname"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/extension":{"role":"symbol","title":"extension","fragments":[{"kind":"identifier","text":"extension"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/extension","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatoptions\/extension"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isDeleteMessagesWhenExitChatRoom":{"deprecated":true,"role":"symbol","title":"isDeleteMessagesWhenExitChatRoom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeleteMessagesWhenExitChatRoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to delete all the chat room messages when leaving the chat room. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isDeleteMessagesWhenExitChatRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDeleteMessagesWhenExitChatRoom"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isdeletemessageswhenexitchatroom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isDeleteMessagesWhenExitGroup":{"deprecated":true,"role":"symbol","title":"isDeleteMessagesWhenExitGroup","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDeleteMessagesWhenExitGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to delete all the group messages when leaving the group. The default value is YES."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isDeleteMessagesWhenExitGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDeleteMessagesWhenExitGroup"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isdeletemessageswhenexitgroup"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions":{"role":"symbol","title":"AgoraChatOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatOptions"}],"abstract":[{"type":"text","text":"The SDK setting options."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatOptions"}],"url":"\/documentation\/agorachat\/agorachatoptions"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatOptions/isAutoLogin":{"role":"symbol","title":"isAutoLogin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoLogin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable automatic login. The default value is "},{"type":"codeVoice","code":"YES"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAutoLogin"}],"url":"\/documentation\/agorachat\/agorachatoptions\/isautologin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/apnsCertName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/appkey","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/area","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoAcceptFriendInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoAcceptGroupInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/autoDownloadThumbnail","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/canChatroomOwnerLeave","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/chatPort","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/chatServer","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/deleteMessagesOnLeaveChatroom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/deleteMessagesOnLeaveGroup","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/dnsURL","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableConsoleLog","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableDeliveryAck","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableDnsConfig","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableFpa","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableRequireReadAck","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/enableStatistics","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/extension","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoAcceptFriendInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoAcceptGroupInvitation","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoDownloadThumbnail","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoLogin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isAutoTransferMessageAttachments","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isChatroomOwnerLeaveAllowed","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isDeleteMessagesWhenExitChatRoom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/isDeleteMessagesWhenExitGroup","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/logLevel","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/pushKitCertName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/restServer","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/sortMessageByServerTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/usingHttpsOnly"]},{"title":"Type Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatOptions\/init(appkey:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableFpa\/title","value":"enableFpa"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableFpa\/fragments","value":[{"kind":"identifier","text":"enableFpa"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1autoDownloadThumbnail\/title","value":"autoDownloadThumbnail"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1autoDownloadThumbnail\/fragments","value":[{"kind":"identifier","text":"autoDownloadThumbnail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1sortMessageByServerTime\/title","value":"sortMessageByServerTime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1sortMessageByServerTime\/fragments","value":[{"kind":"identifier","text":"sortMessageByServerTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isChatroomOwnerLeaveAllowed\/title","value":"isChatroomOwnerLeaveAllowed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isChatroomOwnerLeaveAllowed\/fragments","value":[{"kind":"identifier","text":"isChatroomOwnerLeaveAllowed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1appkey\/title","value":"appkey"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1appkey\/fragments","value":[{"kind":"identifier","text":"appkey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoDownloadThumbnail\/title","value":"isAutoDownloadThumbnail"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoDownloadThumbnail\/fragments","value":[{"kind":"identifier","text":"isAutoDownloadThumbnail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoAcceptFriendInvitation\/title","value":"isAutoAcceptFriendInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoAcceptFriendInvitation\/fragments","value":[{"kind":"identifier","text":"isAutoAcceptFriendInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoAcceptGroupInvitation\/title","value":"isAutoAcceptGroupInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoAcceptGroupInvitation\/fragments","value":[{"kind":"identifier","text":"isAutoAcceptGroupInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1autoAcceptFriendInvitation\/title","value":"autoAcceptFriendInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1autoAcceptFriendInvitation\/fragments","value":[{"kind":"identifier","text":"autoAcceptFriendInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1canChatroomOwnerLeave\/title","value":"canChatroomOwnerLeave"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1canChatroomOwnerLeave\/fragments","value":[{"kind":"identifier","text":"canChatroomOwnerLeave"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1deleteMessagesOnLeaveChatroom\/title","value":"deleteMessagesOnLeaveChatroom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1deleteMessagesOnLeaveChatroom\/fragments","value":[{"kind":"identifier","text":"deleteMessagesOnLeaveChatroom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1autoAcceptGroupInvitation\/title","value":"autoAcceptGroupInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1autoAcceptGroupInvitation\/fragments","value":[{"kind":"identifier","text":"autoAcceptGroupInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1usingHttpsOnly\/title","value":"usingHttpsOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1usingHttpsOnly\/fragments","value":[{"kind":"identifier","text":"usingHttpsOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1area\/title","value":"area"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1area\/fragments","value":[{"kind":"identifier","text":"area"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableStatistics\/title","value":"enableStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableStatistics\/fragments","value":[{"kind":"identifier","text":"enableStatistics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1logLevel\/title","value":"logLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1logLevel\/fragments","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoTransferMessageAttachments\/title","value":"isAutoTransferMessageAttachments"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoTransferMessageAttachments\/fragments","value":[{"kind":"identifier","text":"isAutoTransferMessageAttachments"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1apnsCertName\/title","value":"apnsCertName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1apnsCertName\/fragments","value":[{"kind":"identifier","text":"apnsCertName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableRequireReadAck\/title","value":"enableRequireReadAck"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableRequireReadAck\/fragments","value":[{"kind":"identifier","text":"enableRequireReadAck"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1deleteMessagesOnLeaveGroup\/title","value":"deleteMessagesOnLeaveGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1deleteMessagesOnLeaveGroup\/fragments","value":[{"kind":"identifier","text":"deleteMessagesOnLeaveGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1init(appkey:)\/title","value":"optionsWithAppkey:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1init(appkey:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"optionsWithAppkey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableConsoleLog\/title","value":"enableConsoleLog"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableConsoleLog\/fragments","value":[{"kind":"identifier","text":"enableConsoleLog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableDeliveryAck\/title","value":"enableDeliveryAck"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1enableDeliveryAck\/fragments","value":[{"kind":"identifier","text":"enableDeliveryAck"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1pushKitCertName\/title","value":"pushKitCertName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1pushKitCertName\/fragments","value":[{"kind":"identifier","text":"pushKitCertName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isDeleteMessagesWhenExitChatRoom\/title","value":"isDeleteMessagesWhenExitChatRoom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isDeleteMessagesWhenExitChatRoom\/fragments","value":[{"kind":"identifier","text":"isDeleteMessagesWhenExitChatRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isDeleteMessagesWhenExitGroup\/title","value":"isDeleteMessagesWhenExitGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isDeleteMessagesWhenExitGroup\/fragments","value":[{"kind":"identifier","text":"isDeleteMessagesWhenExitGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions\/title","value":"AgoraChatOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions\/fragments","value":[{"kind":"identifier","text":"AgoraChatOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoLogin\/title","value":"isAutoLogin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatOptions~1isAutoLogin\/fragments","value":[{"kind":"identifier","text":"isAutoLogin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}