{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageBodyType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagebodytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagebodytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The enum of message body types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageBodyType"}],"title":"AgoraChatMessageBodyType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatMessageBodyType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/cmd","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/custom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/file","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/image","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/location","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/text","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/video","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/voice"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType":{"role":"symbol","title":"AgoraChatMessageBodyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageBodyType"}],"abstract":[{"type":"text","text":"The enum of message body types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagebodytype\/equatable-implementations"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/location":{"role":"symbol","title":"AgoraChatMessageBodyType.location","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"}],"abstract":[{"type":"text","text":"A video message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeLocation"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/location"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagebodytype\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagebodytype\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/file":{"role":"symbol","title":"AgoraChatMessageBodyType.file","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"abstract":[{"type":"text","text":"A voice message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/file","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeFile"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/file"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/custom":{"role":"symbol","title":"AgoraChatMessageBodyType.custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"abstract":[{"type":"text","text":"A command message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/custom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeCustom"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/custom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/cmd":{"role":"symbol","title":"AgoraChatMessageBodyType.cmd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmd"}],"abstract":[{"type":"text","text":"A file message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/cmd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeCmd"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/cmd"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/text":{"role":"symbol","title":"AgoraChatMessageBodyType.text","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/text","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeText"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/text"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/image":{"role":"symbol","title":"AgoraChatMessageBodyType.image","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"abstract":[{"type":"text","text":"A text message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeImage"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/image"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/voice":{"role":"symbol","title":"AgoraChatMessageBodyType.voice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voice"}],"abstract":[{"type":"text","text":"A location message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/voice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeVoice"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/voice"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType/video":{"role":"symbol","title":"AgoraChatMessageBodyType.video","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"abstract":[{"type":"text","text":"An image message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/video","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeVideo"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype\/video"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageBodyType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/cmd","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/custom","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/file","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/image","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/location","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/text","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/video","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType\/voice"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageBodyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType\/title","value":"AgoraChatMessageBodyType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1location\/title","value":"AgoraChatMessageBodyTypeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1location\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1file\/title","value":"AgoraChatMessageBodyTypeFile"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1file\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1custom\/title","value":"AgoraChatMessageBodyTypeCustom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1custom\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeCustom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1cmd\/title","value":"AgoraChatMessageBodyTypeCmd"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1cmd\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeCmd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1text\/title","value":"AgoraChatMessageBodyTypeText"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1text\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1image\/title","value":"AgoraChatMessageBodyTypeImage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1image\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1voice\/title","value":"AgoraChatMessageBodyTypeVoice"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1voice\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeVoice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1video\/title","value":"AgoraChatMessageBodyTypeVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType~1video\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyTypeVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}