{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatImageMessageBody"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create an image message body by calling one of the following methods:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"-"},{"type":"codeVoice","code":"(instancetype)initWithData:displayName:"},{"type":"text","text":" "},{"type":"text","text":"-"},{"type":"codeVoice","code":"(instancetype)initWithData:thumbnailData:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: SDK will compress the image based on the attribute compressRatio when delivering the image."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatimagemessagebody"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatimagemessagebody"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The image message body."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatImageMessageBody"}],"title":"AgoraChatImageMessageBody","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatImageMessageBody","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/init(data:thumbnailData:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/compressionRatio","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/size","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDisplayName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDownloadStatus","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailFileLength","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailLocalPath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailRemotePath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailSecretKey","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailSize"]}],"references":{"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/compressionRatio":{"role":"symbol","title":"compressionRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compressionRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The compression ratio of the image file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/compressionRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"compressionRatio"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/compressionratio"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailSecretKey":{"role":"symbol","title":"thumbnailSecretKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSecretKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The secret key for the thumbnail. A key is required for verification when downloading thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailSecretKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailSecretKey"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnailsecretkey"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailLocalPath":{"role":"symbol","title":"thumbnailLocalPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailLocalPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The local path of the thumbnail."},{"type":"text","text":" "},{"type":"text","text":"UIImage *image = [UIImage imageWithContentsOfFile:thumbnailLocalPath];"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailLocalPath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailLocalPath"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnaillocalpath"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailFileLength":{"role":"symbol","title":"thumbnailFileLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailFileLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The data length (bytes) of the thumbnail file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailFileLength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailFileLength"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnailfilelength"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatFileMessageBody":{"role":"symbol","title":"AgoraChatFileMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatFileMessageBody"}],"abstract":[{"type":"text","text":"The file message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatFileMessageBody"}],"url":"\/documentation\/agorachat\/agorachatfilemessagebody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailDownloadStatus":{"role":"symbol","title":"thumbnailDownloadStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDownloadStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The download status of the thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnaildownloadstatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailSize":{"role":"symbol","title":"thumbnailSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The resolution of the thumbnail file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailSize"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnailsize"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/init(data:thumbnailData:)":{"role":"symbol","title":"init(data:thumbnailData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"thumbnailData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Initializes an image message body instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/init(data:thumbnailData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithData:thumbnailData:"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/init(data:thumbnaildata:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody":{"role":"symbol","title":"AgoraChatImageMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatImageMessageBody"}],"abstract":[{"type":"text","text":"The image message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The resolution of the image."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/size"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailDisplayName":{"role":"symbol","title":"thumbnailDisplayName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailDisplayName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The display name of thumbnail."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDisplayName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailDisplayName"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnaildisplayname"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatImageMessageBody/thumbnailRemotePath":{"role":"symbol","title":"thumbnailRemotePath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"thumbnailRemotePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The URL path of the thumbnail of the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailRemotePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thumbnailRemotePath"}],"url":"\/documentation\/agorachat\/agorachatimagemessagebody\/thumbnailremotepath"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatImageMessageBody"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/compressionRatio","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/size","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDisplayName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailDownloadStatus","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailFileLength","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailLocalPath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailRemotePath","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailSecretKey","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/thumbnailSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatImageMessageBody\/init(data:thumbnailData:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatImageMessageBody"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatFileMessageBody","preciseIdentifier":"c:objc(cs)AgoraChatFileMessageBody","text":"AgoraChatFileMessageBody"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1compressionRatio\/title","value":"compressionRatio"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1compressionRatio\/fragments","value":[{"kind":"identifier","text":"compressionRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailSecretKey\/title","value":"thumbnailSecretKey"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailSecretKey\/fragments","value":[{"kind":"identifier","text":"thumbnailSecretKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailLocalPath\/title","value":"thumbnailLocalPath"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailLocalPath\/fragments","value":[{"kind":"identifier","text":"thumbnailLocalPath"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailFileLength\/title","value":"thumbnailFileLength"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailFileLength\/fragments","value":[{"kind":"identifier","text":"thumbnailFileLength"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody\/title","value":"AgoraChatFileMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatFileMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatFileMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailDownloadStatus\/title","value":"thumbnailDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailDownloadStatus\/fragments","value":[{"kind":"identifier","text":"thumbnailDownloadStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailSize\/title","value":"thumbnailSize"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailSize\/fragments","value":[{"kind":"identifier","text":"thumbnailSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1init(data:thumbnailData:)\/title","value":"initWithData:thumbnailData:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1init(data:thumbnailData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:thumbnailData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody\/title","value":"AgoraChatImageMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatImageMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailDisplayName\/title","value":"thumbnailDisplayName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailDisplayName\/fragments","value":[{"kind":"identifier","text":"thumbnailDisplayName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailRemotePath\/title","value":"thumbnailRemotePath"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatImageMessageBody~1thumbnailRemotePath\/fragments","value":[{"kind":"identifier","text":"thumbnailRemotePath"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}