{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpushdisplaystyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpushdisplaystyle"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The display style of push message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"title":"AgoraChatPushDisplayStyle","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatPushDisplayStyle","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/messageSummary","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/simpleBanner"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/simpleBanner":{"role":"symbol","title":"AgoraChatPushDisplayStyle.simpleBanner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simpleBanner"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/simpleBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/simplebanner"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle":{"role":"symbol","title":"AgoraChatPushDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"abstract":[{"type":"text","text":"The display style of push message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/messageSummary":{"role":"symbol","title":"AgoraChatPushDisplayStyle.messageSummary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSummary"}],"abstract":[{"type":"text","text":"A simple banner that displays “You have a new message”."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/messageSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/messagesummary"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/equatable-implementations"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatPushDisplayStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/messageSummary","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/simpleBanner"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1simpleBanner\/title","value":"AgoraChatPushDisplayStyleSimpleBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1simpleBanner\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/title","value":"AgoraChatPushDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1messageSummary\/title","value":"AgoraChatPushDisplayStyleMessageSummary"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1messageSummary\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleMessageSummary"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}