{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroommessagepriority"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroommessagepriority"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The chat room message priorities."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}],"title":"AgoraChatRoomMessagePriority","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatRoomMessagePriority","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/high","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/low","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/normal"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatroommessagepriority\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority":{"role":"symbol","title":"AgoraChatRoomMessagePriority","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}],"abstract":[{"type":"text","text":"The chat room message priorities."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}],"url":"\/documentation\/agorachat\/agorachatroommessagepriority"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatroommessagepriority\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/high":{"role":"symbol","title":"AgoraChatRoomMessagePriority.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityHigh"}],"url":"\/documentation\/agorachat\/agorachatroommessagepriority\/high"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/normal":{"role":"symbol","title":"AgoraChatRoomMessagePriority.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityNormal"}],"url":"\/documentation\/agorachat\/agorachatroommessagepriority\/normal"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatroommessagepriority\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/low":{"role":"symbol","title":"AgoraChatRoomMessagePriority.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}],"url":"\/documentation\/agorachat\/agorachatroommessagepriority\/low"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatRoomMessagePriority"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/high","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/low","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/normal"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRoomMessagePriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority\/title","value":"AgoraChatRoomMessagePriority"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1high\/title","value":"AgoraChatRoomMessagePriorityHigh"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1high\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1normal\/title","value":"AgoraChatRoomMessagePriorityNormal"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1normal\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityNormal"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1low\/title","value":"AgoraChatRoomMessagePriorityLow"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1low\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}