{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagestatisticsdirection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagestatisticsdirection"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message direction types for querying."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"title":"AgoraChatMessageStatisticsDirection","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatMessageStatisticsDirection","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/all","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/receive","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/send"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/send":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection.send","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"send"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/send","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionSend"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/send"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/receive":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection.receive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receive"}],"abstract":[{"type":"text","text":"This message is sent from the local client."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/receive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionReceive"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/receive"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/all":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"The message is received by the local client."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/all"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"abstract":[{"type":"text","text":"The message direction types for querying."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageStatisticsDirection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/all","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/receive","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/send"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1send\/title","value":"AgoraChatMessageStatisticsDirectionSend"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1send\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionSend"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1receive\/title","value":"AgoraChatMessageStatisticsDirectionReceive"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1receive\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionReceive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1all\/title","value":"AgoraChatMessageStatisticsDirectionAll"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1all\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection\/title","value":"AgoraChatMessageStatisticsDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}