{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This enumeration takes user A logged into both DeviceA1 and DeviceA2 as an example to illustrate the various multi-device event types and when these events are triggered."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Multi-device event types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"title":"AgoraChatMultiDevicesEvent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatMultiDevicesEvent","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadCreate","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadDestroy","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadJoin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadKick","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadLeave","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadUpdate","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactAccept","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactAllow","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactDecline","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactRemove","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAble","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddAdmin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddMute","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddWhiteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllow","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApply","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyAccept","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyDecline","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAssignOwner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBlock","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupCreate","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupDestroy","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupDisabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInvite","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInviteAccept","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInviteDecline","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupJoin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupKick","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupLeave","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveAdmin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveAllBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveMute","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveWhiteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupUnBlock","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/unknow"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupCreate":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupCreate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupCreate"}],"abstract":[{"type":"text","text":"If user A removes a user from the blocklist on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupCreate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupCreate"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupcreate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/contactAccept":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.contactAccept","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactAccept"}],"abstract":[{"type":"text","text":"If user A deletes a contact on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactAccept","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactAccept"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/contactaccept"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAddWhiteList":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAddWhiteList","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAddWhiteList"}],"abstract":[{"type":"text","text":"If user A unmutes other group members in DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddWhiteList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAddWhiteList"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupaddwhitelist"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupApplyDecline":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupApplyDecline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupApplyDecline"}],"abstract":[{"type":"text","text":"If user A receives another user’s request to join the chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyDecline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupapplydecline"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupApplyAccept":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupApplyAccept","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupApplyAccept"}],"abstract":[{"type":"text","text":"If user A requests to join a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyAccept","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyAccept"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupapplyaccept"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAble":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAble","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAble"}],"abstract":[{"type":"text","text":"If user joined group is disabled, all devices of user A receive the event."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAble"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupable"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupKick":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupKick","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupKick"}],"abstract":[{"type":"text","text":"If user A declines another user’s group invitation on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupKick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupkick"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/contactDecline":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.contactDecline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactDecline"}],"abstract":[{"type":"text","text":"If user A accepts a contact invitation on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactDecline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactDecline"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/contactdecline"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupUnBlock":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupUnBlock","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupUnBlock"}],"abstract":[{"type":"text","text":"If user A blocks messages from a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupUnBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupUnBlock"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupunblock"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAddAdmin":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAddAdmin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAddAdmin"}],"abstract":[{"type":"text","text":"If user A assigns a group owner on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddAdmin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAddAdmin"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupaddadmin"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/contactRemove":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.contactRemove","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactRemove"}],"abstract":[{"type":"text","text":"Default."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactRemove","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactRemove"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/contactremove"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupBlock":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupBlock","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupBlock"}],"abstract":[{"type":"text","text":"If user A removes other users from a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupblock"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupRemoveAllBan":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupRemoveAllBan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupRemoveAllBan"}],"abstract":[{"type":"text","text":"If user A mutes all group members in DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveAllBan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveAllBan"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupremoveallban"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAddMute":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAddMute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAddMute"}],"abstract":[{"type":"text","text":"If user A removes a group admin on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddMute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAddMute"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupaddmute"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadDestroy":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadDestroy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadDestroy"}],"abstract":[{"type":"text","text":"User A creates an event in the sub-area of device A1, and other devices logged in to this account will receive this event"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadDestroy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadDestroy"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreaddestroy"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupInviteDecline":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupInviteDecline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInviteDecline"}],"abstract":[{"type":"text","text":"If user A accepts another user’s group invitation on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInviteDecline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupInviteDecline"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupinvitedecline"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAllBan":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAllBan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAllBan"}],"abstract":[{"type":"text","text":"If user A removes other member from the whitelist in DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllBan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllBan"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupallban"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupLeave":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupLeave","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupLeave"}],"abstract":[{"type":"text","text":"If user A joins a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupLeave","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupLeave"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupleave"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadKick":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadKick","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadKick"}],"abstract":[{"type":"text","text":"User A updates the event in the sub-area of device A1, and other devices logged in to this account will receive this event"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadKick","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadkick"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupApply":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupApply","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupApply"}],"abstract":[{"type":"text","text":"If user A leaves a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApply","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApply"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupapply"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadLeave":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadLeave","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadLeave"}],"abstract":[{"type":"text","text":"User A joins the event in the sub-area of device A1, and other devices logged in to this account will receive this event"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadLeave","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadLeave"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadleave"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadJoin":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadJoin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadJoin"}],"abstract":[{"type":"text","text":"User A destroys the event in the sub-area of device A1, and all other devices logged in to this account will receive this event"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadJoin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadJoin"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadjoin"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadUpdate":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadUpdate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadUpdate"}],"abstract":[{"type":"text","text":"User A leaves the event in the sub-area of device A1, and other devices logged in to this account will receive this event"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadUpdate"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadupdate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupInvite":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupInvite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvite"}],"abstract":[{"type":"text","text":"If user A declines another user’s request to join the chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInvite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupInvite"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupinvite"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupDisabled":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupDisabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupDisabled"}],"abstract":[{"type":"text","text":"If user A unmutes all group members in DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupDisabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupDisabled"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupdisabled"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupJoin":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupJoin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupJoin"}],"abstract":[{"type":"text","text":"If user A destroys a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupJoin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupJoin"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupjoin"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupRemoveAdmin":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupRemoveAdmin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupRemoveAdmin"}],"abstract":[{"type":"text","text":"If user A adds a group admin on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveAdmin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveAdmin"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupremoveadmin"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/contactAllow":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.contactAllow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactAllow"}],"abstract":[{"type":"text","text":"If user A adds another user into the blocklist on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactAllow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactAllow"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/contactallow"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupBan":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupBan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupBan"}],"abstract":[{"type":"text","text":"If user A removes other users from a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBan"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupban"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAllow":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAllow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAllow"}],"abstract":[{"type":"text","text":"If user A is added to the blocklist on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupallow"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupAssignOwner":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupAssignOwner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupAssignOwner"}],"abstract":[{"type":"text","text":"If user A unblocks messages from a chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAssignOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAssignOwner"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupassignowner"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/unknow":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.unknow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknow"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/unknow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventUnknow"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/unknow"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupRemoveMute":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupRemoveMute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupRemoveMute"}],"abstract":[{"type":"text","text":"If user A mutes other group members on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveMute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveMute"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupremovemute"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupDestroy":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupDestroy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupDestroy"}],"abstract":[{"type":"text","text":"If user A creates a chat group on Device A1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupDestroy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupDestroy"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupdestroy"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent":{"role":"symbol","title":"AgoraChatMultiDevicesEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"abstract":[{"type":"text","text":"Multi-device event types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupRemoveWhiteList":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupRemoveWhiteList","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupRemoveWhiteList"}],"abstract":[{"type":"text","text":"If user A Added other group member to the whitelist in DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveWhiteList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveWhiteList"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupremovewhitelist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/contactBan":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.contactBan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactBan"}],"abstract":[{"type":"text","text":"If user A declines a contact invitation on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactBan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactBan"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/contactban"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/groupInviteAccept":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.groupInviteAccept","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInviteAccept"}],"abstract":[{"type":"text","text":"If user A invites other users to join the chat group on DeviceA1, this event is triggered on DeviceA2."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInviteAccept","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupInviteAccept"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/groupinviteaccept"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesEvent/chatThreadCreate":{"role":"symbol","title":"AgoraChatMultiDevicesEvent.chatThreadCreate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThreadCreate"}],"abstract":[{"type":"text","text":"If user joined group cancel disabled, all devices of user A receive the event."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadCreate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadCreate"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesevent\/chatthreadcreate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadCreate","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadDestroy","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadJoin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadKick","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadLeave","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/chatThreadUpdate","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactAccept","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactAllow","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactDecline","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/contactRemove","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAble","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddAdmin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddMute","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAddWhiteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAllow","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApply","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyAccept","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupApplyDecline","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupAssignOwner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupBlock","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupCreate","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupDestroy","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupDisabled","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInvite","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInviteAccept","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupInviteDecline","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupJoin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupKick","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupLeave","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveAdmin","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveAllBan","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveMute","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupRemoveWhiteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/groupUnBlock","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesEvent\/unknow"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupCreate\/title","value":"AgoraChatMultiDevicesEventGroupCreate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupCreate\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupCreate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactAccept\/title","value":"AgoraChatMultiDevicesEventContactAccept"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactAccept\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactAccept"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAddWhiteList\/title","value":"AgoraChatMultiDevicesEventGroupAddWhiteList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAddWhiteList\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAddWhiteList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApplyDecline\/title","value":"AgoraChatMultiDevicesEventGroupApplyDecline"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApplyDecline\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyDecline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApplyAccept\/title","value":"AgoraChatMultiDevicesEventGroupApplyAccept"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApplyAccept\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApplyAccept"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAble\/title","value":"AgoraChatMultiDevicesEventGroupAble"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAble\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupKick\/title","value":"AgoraChatMultiDevicesEventGroupKick"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupKick\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupKick"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactDecline\/title","value":"AgoraChatMultiDevicesEventContactDecline"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactDecline\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactDecline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupUnBlock\/title","value":"AgoraChatMultiDevicesEventGroupUnBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupUnBlock\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupUnBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAddAdmin\/title","value":"AgoraChatMultiDevicesEventGroupAddAdmin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAddAdmin\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAddAdmin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactRemove\/title","value":"AgoraChatMultiDevicesEventContactRemove"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactRemove\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactRemove"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupBlock\/title","value":"AgoraChatMultiDevicesEventGroupBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupBlock\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveAllBan\/title","value":"AgoraChatMultiDevicesEventGroupRemoveAllBan"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveAllBan\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveAllBan"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAddMute\/title","value":"AgoraChatMultiDevicesEventGroupAddMute"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAddMute\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAddMute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadDestroy\/title","value":"AgoraChatMultiDevicesEventChatThreadDestroy"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadDestroy\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadDestroy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupInviteDecline\/title","value":"AgoraChatMultiDevicesEventGroupInviteDecline"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupInviteDecline\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupInviteDecline"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAllBan\/title","value":"AgoraChatMultiDevicesEventGroupAllBan"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAllBan\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllBan"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupLeave\/title","value":"AgoraChatMultiDevicesEventGroupLeave"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupLeave\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupLeave"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadKick\/title","value":"AgoraChatMultiDevicesEventChatThreadKick"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadKick\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadKick"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApply\/title","value":"AgoraChatMultiDevicesEventGroupApply"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupApply\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupApply"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadLeave\/title","value":"AgoraChatMultiDevicesEventChatThreadLeave"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadLeave\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadLeave"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadJoin\/title","value":"AgoraChatMultiDevicesEventChatThreadJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadJoin\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadJoin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadUpdate\/title","value":"AgoraChatMultiDevicesEventChatThreadUpdate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadUpdate\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupInvite\/title","value":"AgoraChatMultiDevicesEventGroupInvite"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupInvite\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupInvite"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupDisabled\/title","value":"AgoraChatMultiDevicesEventGroupDisabled"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupDisabled\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupJoin\/title","value":"AgoraChatMultiDevicesEventGroupJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupJoin\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupJoin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveAdmin\/title","value":"AgoraChatMultiDevicesEventGroupRemoveAdmin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveAdmin\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveAdmin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactAllow\/title","value":"AgoraChatMultiDevicesEventContactAllow"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactAllow\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactAllow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupBan\/title","value":"AgoraChatMultiDevicesEventGroupBan"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupBan\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupBan"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAllow\/title","value":"AgoraChatMultiDevicesEventGroupAllow"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAllow\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAllow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAssignOwner\/title","value":"AgoraChatMultiDevicesEventGroupAssignOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupAssignOwner\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupAssignOwner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1unknow\/title","value":"AgoraChatMultiDevicesEventUnknow"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1unknow\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventUnknow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveMute\/title","value":"AgoraChatMultiDevicesEventGroupRemoveMute"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveMute\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveMute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupDestroy\/title","value":"AgoraChatMultiDevicesEventGroupDestroy"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupDestroy\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupDestroy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/title","value":"AgoraChatMultiDevicesEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveWhiteList\/title","value":"AgoraChatMultiDevicesEventGroupRemoveWhiteList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupRemoveWhiteList\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupRemoveWhiteList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactBan\/title","value":"AgoraChatMultiDevicesEventContactBan"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1contactBan\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventContactBan"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupInviteAccept\/title","value":"AgoraChatMultiDevicesEventGroupInviteAccept"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1groupInviteAccept\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventGroupInviteAccept"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadCreate\/title","value":"AgoraChatMultiDevicesEventChatThreadCreate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesEvent~1chatThreadCreate\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesEventChatThreadCreate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}