{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The group type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupStyle"}],"title":"AgoraChatGroupStyle","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatGroupStyle","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStyle"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/privateMemberCanInvite","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/privateOnlyOwnerInvite","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicJoinNeedApproval","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicOpenJoin"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/publicOpenJoin":{"role":"symbol","title":"AgoraChatGroupStyle.publicOpenJoin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicOpenJoin"}],"abstract":[{"type":"text","text":"!  A public group, where the group owner can invite users to user. Users can send a join request and join the group if the owner approves it."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicOpenJoin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle\/publicopenjoin"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatgroupstyle\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatgroupstyle\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatgroupstyle\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/privateOnlyOwnerInvite":{"role":"symbol","title":"AgoraChatGroupStyle.privateOnlyOwnerInvite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"privateOnlyOwnerInvite"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/privateOnlyOwnerInvite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePrivateOnlyOwnerInvite"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle\/privateonlyownerinvite"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle":{"role":"symbol","title":"AgoraChatGroupStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupStyle"}],"abstract":[{"type":"text","text":"The group type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStyle"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/publicJoinNeedApproval":{"role":"symbol","title":"AgoraChatGroupStyle.publicJoinNeedApproval","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicJoinNeedApproval"}],"abstract":[{"type":"text","text":"!  A private group, where all the group members including the group owner, group manager, and other group members can invite users to join."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicJoinNeedApproval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle\/publicjoinneedapproval"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupStyle/privateMemberCanInvite":{"role":"symbol","title":"AgoraChatGroupStyle.privateMemberCanInvite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"privateMemberCanInvite"}],"abstract":[{"type":"text","text":"!  A private group, where only the group owner can invite users to join."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/privateMemberCanInvite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupStylePrivateMemberCanInvite"}],"url":"\/documentation\/agorachat\/agorachatgroupstyle\/privatemembercaninvite"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatGroupStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/privateMemberCanInvite","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/privateOnlyOwnerInvite","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicJoinNeedApproval","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupStyle\/publicOpenJoin"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicOpenJoin\/title","value":"AgoraChatGroupStylePublicOpenJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicOpenJoin\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePublicOpenJoin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1privateOnlyOwnerInvite\/title","value":"AgoraChatGroupStylePrivateOnlyOwnerInvite"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1privateOnlyOwnerInvite\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePrivateOnlyOwnerInvite"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle\/title","value":"AgoraChatGroupStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicJoinNeedApproval\/title","value":"AgoraChatGroupStylePublicJoinNeedApproval"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1publicJoinNeedApproval\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePublicJoinNeedApproval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1privateMemberCanInvite\/title","value":"AgoraChatGroupStylePrivateMemberCanInvite"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupStyle~1privateMemberCanInvite\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupStylePrivateMemberCanInvite"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}