{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatContactManagerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatcontactmanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatcontactmanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The contact related callbacks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"title":"AgoraChatContactManagerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatContactManagerDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidApprove(byUser:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidDecline(byUser:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidReceive(fromUser:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidAdd(byUser:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidRemove(byUser:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendshipDidRemove(byUser:)":{"role":"symbol","title":"friendshipDidRemove(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user is removed as a contact by another user."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidRemove(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendshipDidRemoveByUser:"}],"url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidremove(byuser:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate":{"role":"symbol","title":"AgoraChatContactManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"abstract":[{"type":"text","text":"The contact related callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendRequestDidApprove(byUser:)":{"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidApproveByUser:"}],"role":"symbol","title":"friendRequestDidApprove(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidApprove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a friend request is approved, user A will receive this callback after user B approved user A’s friend request."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidApprove(byUser:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendrequestdidapprove(byuser:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendRequestDidReceive(fromUser:message:)":{"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidReceiveFromUser:message:"}],"role":"symbol","title":"friendRequestDidReceive(fromUser:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when a user received a friend request."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidReceive(fromUser:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendrequestdidreceive(fromuser:message:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendRequestDidDecline(byUser:)":{"role":"symbol","title":"friendRequestDidDecline(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidDecline"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a friend request is declined."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidDecline(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendRequestDidDeclineByUser:"}],"url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendrequestdiddecline(byuser:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendshipDidAdd(byUser:)":{"navigatorTitle":[{"kind":"identifier","text":"friendshipDidAddByUser:"}],"role":"symbol","title":"friendshipDidAdd(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidAdd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the user is added as a contact by another user."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidAdd(byUser:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidadd(byuser:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatContactManagerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidApprove(byUser:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidDecline(byUser:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendRequestDidReceive(fromUser:message:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidAdd(byUser:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidRemove(byUser:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatContactManagerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidRemove(byUser:)\/title","value":"friendshipDidRemoveByUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidRemove(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidRemoveByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate\/title","value":"AgoraChatContactManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendRequestDidApprove(byUser:)\/title","value":"friendRequestDidApproveByUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendRequestDidApprove(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidApproveByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendRequestDidReceive(fromUser:message:)\/title","value":"friendRequestDidReceiveFromUser:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendRequestDidReceive(fromUser:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidReceiveFromUser:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendRequestDidDecline(byUser:)\/title","value":"friendRequestDidDeclineByUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendRequestDidDecline(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidDeclineByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidAdd(byUser:)\/title","value":"friendshipDidAddByUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidAdd(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidAddByUser:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}