{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message delivery states."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatus"}],"title":"AgoraChatMessageStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChatMessageStatus","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/delivering","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/failed","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/pending","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/succeed"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/failed":{"role":"symbol","title":"AgoraChatMessageStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"The message is successfully delivered."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatusFailed"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus\/failed"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/pending":{"role":"symbol","title":"AgoraChatMessageStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus\/pending"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagestatus\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus":{"role":"symbol","title":"AgoraChatMessageStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatus"}],"abstract":[{"type":"text","text":"The message delivery states."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatus"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagestatus\/equatable-implementations"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/succeed":{"role":"symbol","title":"AgoraChatMessageStatus.succeed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeed"}],"abstract":[{"type":"text","text":"The message is being delivered."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/succeed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatusSucceed"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus\/succeed"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/delivering":{"role":"symbol","title":"AgoraChatMessageStatus.delivering","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delivering"}],"abstract":[{"type":"text","text":"The message delivery is pending."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/delivering","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatusDelivering"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus\/delivering"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/agorachatmessagestatus\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMessageStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/delivering","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/failed","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/pending","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/succeed"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1failed\/title","value":"AgoraChatMessageStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1pending\/title","value":"AgoraChatMessageStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1pending\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus\/title","value":"AgoraChatMessageStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1succeed\/title","value":"AgoraChatMessageStatusSucceed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1succeed\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatusSucceed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1delivering\/title","value":"AgoraChatMessageStatusDelivering"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1delivering\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatusDelivering"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}