{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmultidevicesdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmultidevicesdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesContactEventDidReceive(_:username:ext:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesMessageBeRemoved(_:deviceId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"title":"AgoraChatMultiDevicesDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatMultiDevicesDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesContactEventDidReceive(_:username:ext:)":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesContactEventDidReceive:username:ext:"}],"role":"symbol","title":"multiDevicesContactEventDidReceive(_:username:ext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesContactEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The multi-device event callback of contact."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesContactEventDidReceive(_:username:ext:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicescontacteventdidreceive(_:username:ext:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesMessageBeRemoved(_:deviceId:)":{"role":"symbol","title":"multiDevicesMessageBeRemoved(_:deviceId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesMessageBeRemoved"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Callback to other devices after conversation deleted  message from server  after enabling multiple devices"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesMessageBeRemoved(_:deviceId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicesmessageberemoved(_:deviceid:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:threadId:ext:"}],"role":"symbol","title":"multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"threadId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The multi-device event callback of thread"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multideviceschatthreadeventdidreceive(_:threadid:ext:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesGroupEventDidReceive(_:groupId:ext:)":{"role":"symbol","title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The multi-device event callback of group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicesgroupeventdidreceive(_:groupid:ext:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}],"role":"symbol","title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Callback to other devices after setting Do Not Disturb for a single session after enabling multiple devices"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMultiDevicesDelegate":{"role":"symbol","title":"AgoraChatMultiDevicesDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}],"url":"\/documentation\/agorachat\/agorachatmultidevicesdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMultiDevicesDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesChatThreadEventDidReceive(_:threadId:ext:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesContactEventDidReceive(_:username:ext:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesMessageBeRemoved(_:deviceId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMultiDevicesDelegate\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesContactEventDidReceive(_:username:ext:)\/title","value":"multiDevicesContactEventDidReceive:username:ext:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesContactEventDidReceive(_:username:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesContactEventDidReceive:username:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesMessageBeRemoved(_:deviceId:)\/title","value":"multiDevicesMessageBeRemoved:deviceId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesMessageBeRemoved(_:deviceId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesChatThreadEventDidReceive(_:threadId:ext:)\/title","value":"multiDevicesChatThreadEventDidReceive:threadId:ext:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesChatThreadEventDidReceive(_:threadId:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesChatThreadEventDidReceive:threadId:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/title","value":"multiDevicesGroupEventDidReceive:groupId:ext:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/title","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate\/title","value":"AgoraChatMultiDevicesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMultiDevicesDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatMultiDevicesDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}