{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClientDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatclientdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatclientdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/autoLoginDidCompleteWithError(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/connectionStateDidChange(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/tokenDidExpire(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/tokenWillExpire(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidForced(toLogout:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidLoginFromOtherDevice()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidRemoveFromServer()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userDidForbidByServer()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClientDelegate"}],"title":"AgoraChatClientDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraChatClientDelegate","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatClientDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/userDidForbidByServer()":{"role":"symbol","title":"userDidForbidByServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"The delegate method will be invoked when the User account is forbidden."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userDidForbidByServer()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidForbidByServer"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate\/userdidforbidbyserver()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate":{"role":"symbol","title":"AgoraChatClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClientDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatClientDelegate"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/userAccountDidForced(toLogout:)":{"role":"symbol","title":"userAccountDidForced(toLogout:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidForced"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toLogout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The delegate method will be invoked when current IM account is forced to logout with the following reasons:"},{"type":"text","text":" "},{"type":"text","text":"1. The password is modified;"},{"type":"text","text":" "},{"type":"text","text":"2. Logged in too many devices;"},{"type":"text","text":" "},{"type":"text","text":"3. User for forbidden;"},{"type":"text","text":" "},{"type":"text","text":"4. Forced offline."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidForced(toLogout:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate\/useraccountdidforced(tologout:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/userAccountDidRemoveFromServer()":{"navigatorTitle":[{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"role":"symbol","title":"userAccountDidRemoveFromServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Occurs when the current chat user is removed from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidRemoveFromServer()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatclientdelegate\/useraccountdidremovefromserver()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/userAccountDidLoginFromOtherDevice()":{"role":"symbol","title":"userAccountDidLoginFromOtherDevice()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Occurs when the current user account is logged in to another device."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidLoginFromOtherDevice()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate\/useraccountdidloginfromotherdevice()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/connectionStateDidChange(_:)":{"role":"symbol","title":"connectionStateDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatConnectionState","preciseIdentifier":"c:@E@AgoraChatConnectionState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the connection state between the SDK and the server changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/connectionStateDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate\/connectionstatedidchange(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/tokenWillExpire(_:)":{"navigatorTitle":[{"kind":"identifier","text":"tokenWillExpire:"}],"role":"symbol","title":"tokenWillExpire(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenWillExpire"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatErrorCode","preciseIdentifier":"c:@E@AgoraChatErrorCode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"token will expire (log in using agoraToken)"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/tokenWillExpire(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatclientdelegate\/tokenwillexpire(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/autoLoginDidCompleteWithError(_:)":{"role":"symbol","title":"autoLoginDidCompleteWithError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoLoginDidCompleteWithError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the auto login is completed."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/autoLoginDidCompleteWithError(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoLoginDidCompleteWithError:"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate\/autologindidcompletewitherror(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/tokenDidExpire(_:)":{"navigatorTitle":[{"kind":"identifier","text":"tokenDidExpire:"}],"role":"symbol","title":"tokenDidExpire(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenDidExpire"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatErrorCode","preciseIdentifier":"c:@E@AgoraChatErrorCode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"token did expire (log in using agoraToken)"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/tokenDidExpire(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatclientdelegate\/tokendidexpire(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatClientDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatClientDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatClientDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/autoLoginDidCompleteWithError(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/connectionStateDidChange(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/tokenDidExpire(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/tokenWillExpire(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidForced(toLogout:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidLoginFromOtherDevice()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidRemoveFromServer()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userDidForbidByServer()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClientDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userDidForbidByServer()\/title","value":"userDidForbidByServer"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userDidForbidByServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidForbidByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate\/title","value":"AgoraChatClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidForced(toLogout:)\/title","value":"userAccountDidForcedToLogout:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidForced(toLogout:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidForcedToLogout:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidRemoveFromServer()\/title","value":"userAccountDidRemoveFromServer"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidRemoveFromServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidLoginFromOtherDevice()\/title","value":"userAccountDidLoginFromOtherDevice"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidLoginFromOtherDevice()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1connectionStateDidChange(_:)\/title","value":"connectionStateDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1connectionStateDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectionStateDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1tokenWillExpire(_:)\/title","value":"tokenWillExpire:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1tokenWillExpire(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenWillExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1autoLoginDidCompleteWithError(_:)\/title","value":"autoLoginDidCompleteWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1autoLoginDidCompleteWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"autoLoginDidCompleteWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1tokenDidExpire(_:)\/title","value":"tokenDidExpire:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1tokenDidExpire(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenDidExpire:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}