{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresence"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpresence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpresence"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The presence property class that contains presence properties, including the publisher’s user ID and current presence state, and the platform used by the online device, as well as the presence’s extension information, update time, and subscription expiration time."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresence"}],"title":"AgoraChatPresence","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatPresence","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresence"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/expirytime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/lastTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/publisher","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDescription","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDetails"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence/publisher":{"role":"symbol","title":"publisher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The user ID of the presence publisher."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/publisher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publisher"}],"url":"\/documentation\/agorachat\/agorachatpresence\/publisher"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence":{"role":"symbol","title":"AgoraChatPresence","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresence"}],"abstract":[{"type":"text","text":"The presence property class that contains presence properties, including the publisher’s user ID and current presence state, and the platform used by the online device, as well as the presence’s extension information, update time, and subscription expiration time."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresence"}],"url":"\/documentation\/agorachat\/agorachatpresence"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence/statusDescription":{"role":"symbol","title":"statusDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The presence description information."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusDescription"}],"url":"\/documentation\/agorachat\/agorachatpresence\/statusdescription"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence/expirytime":{"role":"symbol","title":"expirytime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirytime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The expiration time of the presence subscription."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/expirytime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expirytime"}],"url":"\/documentation\/agorachat\/agorachatpresence\/expirytime"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence/lastTime":{"role":"symbol","title":"lastTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The presence update time, which is generated by the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/lastTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastTime"}],"url":"\/documentation\/agorachat\/agorachatpresence\/lasttime"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence/statusDetails":{"role":"symbol","title":"statusDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDetails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatPresenceStatusDetail","preciseIdentifier":"c:objc(cs)AgoraChatPresenceStatusDetail"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The details of the current presence state."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusDetails"}],"url":"\/documentation\/agorachat\/agorachatpresence\/statusdetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatPresence"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresence"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatPresence"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/expirytime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/lastTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/publisher","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDescription","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDetails"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresence"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1publisher\/title","value":"publisher"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1publisher\/fragments","value":[{"kind":"identifier","text":"publisher"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence\/title","value":"AgoraChatPresence"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1statusDescription\/title","value":"statusDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1statusDescription\/fragments","value":[{"kind":"identifier","text":"statusDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1expirytime\/title","value":"expirytime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1expirytime\/fragments","value":[{"kind":"identifier","text":"expirytime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1lastTime\/title","value":"lastTime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1lastTime\/fragments","value":[{"kind":"identifier","text":"lastTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1statusDetails\/title","value":"statusDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1statusDetails\/fragments","value":[{"kind":"identifier","text":"statusDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}