{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatconversation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatconversation"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The chat conversation class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"title":"AgoraChatConversation","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatConversation","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatConversation"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/conversationId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/ext","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/isChatThread","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/latestMessage","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/messagesCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/type","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/unreadMessagesCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/append(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/deleteAllMessages(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/deleteMessage(withId:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/insert(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/lastReceivedMessage()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessage(withId:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(from:to:count:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(from:to:count:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(with:timestamp:count:fromUser:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessagesStart(fromId:count:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessagesStart(fromId:count:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markAllMessages(asRead:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markMessageAsRead(withId:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/removeMessages(fromServerMessageIds:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/removeMessagesFromServer(withTimeStamp:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/updateMessageChange(_:error:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessages(with:timestamp:count:fromUser:searchDirection:)":{"role":"symbol","title":"loadMessages(with:timestamp:count:fromUser:searchDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBodyType","preciseIdentifier":"c:@E@AgoraChatMessageBodyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Gets messages of certain types that a specified user sends in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(with:timestamp:count:fromUser:searchDirection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessages(with:timestamp:count:fromuser:searchdirection:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)":{"role":"symbol","title":"loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBodyType","preciseIdentifier":"c:@E@AgoraChatMessageBodyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets messages of certain types that a specified user sends in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessages(with:timestamp:count:fromuser:searchdirection:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessages(from:to:count:completion:)":{"role":"symbol","title":"loadMessages(from:to:count:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Loads a certain quantity of messages sent or received in a certain period from the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(from:to:count:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesFrom:to:count:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessages(from:to:count:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/insert(_:error:)":{"role":"symbol","title":"insert(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Inserts a message to a conversation in the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/insert(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insertMessage:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/insert(_:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/unreadMessagesCount":{"role":"symbol","title":"unreadMessagesCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMessagesCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The number of unread messages in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/unreadMessagesCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unreadMessagesCount"}],"url":"\/documentation\/agorachat\/agorachatconversation\/unreadmessagescount"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation":{"role":"symbol","title":"AgoraChatConversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"abstract":[{"type":"text","text":"The chat conversation class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConversation"}],"url":"\/documentation\/agorachat\/agorachatconversation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)":{"role":"symbol","title":"loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKeyword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Loads messages with keywords that the specified user sends in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessages(withkeyword:timestamp:count:fromuser:searchdirection:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/lastReceivedMessage()":{"role":"symbol","title":"lastReceivedMessage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastReceivedMessage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the last received message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/lastReceivedMessage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastReceivedMessage"}],"url":"\/documentation\/agorachat\/agorachatconversation\/lastreceivedmessage()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/markAllMessages(asRead:)":{"role":"symbol","title":"markAllMessages(asRead:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markAllMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"asRead"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Marks all messages in the local database as read."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markAllMessages(asRead:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"markAllMessagesAsRead:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/markallmessages(asread:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/deleteMessage(withId:error:)":{"role":"symbol","title":"deleteMessage(withId:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Deletes a message from the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/deleteMessage(withId:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteMessageWithId:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/deletemessage(withid:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/append(_:error:)":{"role":"symbol","title":"append(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"append"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Inserts a message to the end of a conversation in local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/append(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendMessage:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/append(_:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/conversationId":{"role":"symbol","title":"conversationId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The conversation ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/conversationId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversationId"}],"url":"\/documentation\/agorachat\/agorachatconversation\/conversationid"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)":{"role":"symbol","title":"loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKeyword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Loads messages with specified keyword from local database. Returning messages are sorted by receiving timestamp based on AgoraChatMessageSearchDirection. If reference timestamp is negative, load from the latest messages; if message count is negative, will be handled as count=1"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessages(withkeyword:timestamp:count:fromuser:searchdirection:completion:)"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/isChatThread":{"role":"symbol","title":"isChatThread","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatThread"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the conversation is a thread conversation:"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/isChatThread","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChatThread"}],"url":"\/documentation\/agorachat\/agorachatconversation\/ischatthread"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)":{"role":"symbol","title":"loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadCustomMsg"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKeyword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Loads custom messages with keywords that the specified user sends in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadCustomMsgWithKeyword:timestamp:count:fromUser:searchDirection:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadcustommsg(withkeyword:timestamp:count:fromuser:searchdirection:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"}],"abstract":[{"type":"text","text":"The conversation type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/agorachat\/agorachatconversation\/type"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessagesStart(fromId:count:searchDirection:)":{"role":"symbol","title":"loadMessagesStart(fromId:count:searchDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessagesStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Loads the messages from the local database, starting from a specific message ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessagesStart(fromId:count:searchDirection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesStartFromId:count:searchDirection:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessagesstart(fromid:count:searchdirection:)"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/deleteAllMessages(_:)":{"role":"symbol","title":"deleteAllMessages(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteAllMessages"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Deletes all the messages in the conversation from the memory and local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/deleteAllMessages(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteAllMessages:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/deleteallmessages(_:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessagesStart(fromId:count:searchDirection:completion:)":{"role":"symbol","title":"loadMessagesStart(fromId:count:searchDirection:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessagesStart"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Loads messages starting from the specified message ID from local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessagesStart(fromId:count:searchDirection:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesStartFromId:count:searchDirection:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessagesstart(fromid:count:searchdirection:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessage(withId:error:)":{"role":"symbol","title":"loadMessage(withId:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets a message with the specified message ID from the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessage(withId:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessageWithId:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessage(withid:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/markMessageAsRead(withId:error:)":{"role":"symbol","title":"markMessageAsRead(withId:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markMessageAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Marks a message in the local database as read."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markMessageAsRead(withId:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"markMessageAsReadWithId:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/markmessageasread(withid:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadMessages(from:to:count:)":{"role":"symbol","title":"loadMessages(from:to:count:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Loads a certain quantity of messages sent or received in a certain period from the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(from:to:count:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadMessagesFrom:to:count:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadmessages(from:to:count:)"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/removeMessages(fromServerMessageIds:completion:)":{"role":"symbol","title":"removeMessages(fromServerMessageIds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromServerMessageIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Removes messages from the conversation by timestamp."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/removeMessages(fromServerMessageIds:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeMessagesFromServerMessageIds:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/removemessages(fromservermessageids:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)":{"role":"symbol","title":"loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadCustomMsg"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKeyword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Loads custom messages with keywords that the specified user sends in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadCustomMsgWithKeyword:timestamp:count:fromUser:searchDirection:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/loadcustommsg(withkeyword:timestamp:count:fromuser:searchdirection:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/messagesCount":{"role":"symbol","title":"messagesCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The message count in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/messagesCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesCount"}],"url":"\/documentation\/agorachat\/agorachatconversation\/messagescount"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/ext":{"role":"symbol","title":"ext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"The conversation extension attribute."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/ext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ext"}],"url":"\/documentation\/agorachat\/agorachatconversation\/ext"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/updateMessageChange(_:error:)":{"role":"symbol","title":"updateMessageChange(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMessageChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Updates a message in the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/updateMessageChange(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateMessageChange:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/updatemessagechange(_:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/latestMessage":{"role":"symbol","title":"latestMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The latest message in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/latestMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latestMessage"}],"url":"\/documentation\/agorachat\/agorachatconversation\/latestmessage"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/removeMessagesFromServer(withTimeStamp:completion:)":{"role":"symbol","title":"removeMessagesFromServer(withTimeStamp:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMessagesFromServer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTimeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Removes messages from the conversation by message ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/removeMessagesFromServer(withTimeStamp:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeMessagesFromServerWithTimeStamp:completion:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/removemessagesfromserver(withtimestamp:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatConversation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatConversation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatConversation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/conversationId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/ext","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/isChatThread","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/latestMessage","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/messagesCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/type","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/unreadMessagesCount"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/append(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/deleteAllMessages(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/deleteMessage(withId:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/insert(_:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/lastReceivedMessage()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessage(withId:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(from:to:count:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(from:to:count:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(with:timestamp:count:fromUser:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessagesStart(fromId:count:searchDirection:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/loadMessagesStart(fromId:count:searchDirection:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markAllMessages(asRead:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markMessageAsRead(withId:error:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/removeMessages(fromServerMessageIds:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/removeMessagesFromServer(withTimeStamp:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/updateMessageChange(_:error:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(with:timestamp:count:fromUser:searchDirection:)\/title","value":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(with:timestamp:count:fromUser:searchDirection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)\/title","value":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(with:timestamp:count:fromUser:searchDirection:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(from:to:count:completion:)\/title","value":"loadMessagesFrom:to:count:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(from:to:count:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesFrom:to:count:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1insert(_:error:)\/title","value":"insertMessage:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1insert(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertMessage:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1unreadMessagesCount\/title","value":"unreadMessagesCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1unreadMessagesCount\/fragments","value":[{"kind":"identifier","text":"unreadMessagesCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/title","value":"AgoraChatConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/fragments","value":[{"kind":"identifier","text":"AgoraChatConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)\/title","value":"loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1lastReceivedMessage()\/title","value":"lastReceivedMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1lastReceivedMessage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lastReceivedMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1markAllMessages(asRead:)\/title","value":"markAllMessagesAsRead:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1markAllMessages(asRead:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markAllMessagesAsRead:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1deleteMessage(withId:error:)\/title","value":"deleteMessageWithId:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1deleteMessage(withId:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteMessageWithId:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1append(_:error:)\/title","value":"appendMessage:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1append(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appendMessage:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1conversationId\/title","value":"conversationId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1conversationId\/fragments","value":[{"kind":"identifier","text":"conversationId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)\/title","value":"loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(withKeyword:timestamp:count:fromUser:searchDirection:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithKeyword:timestamp:count:fromUser:searchDirection:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1isChatThread\/title","value":"isChatThread"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1isChatThread\/fragments","value":[{"kind":"identifier","text":"isChatThread"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)\/title","value":"loadCustomMsgWithKeyword:timestamp:count:fromUser:searchDirection:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadCustomMsgWithKeyword:timestamp:count:fromUser:searchDirection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessagesStart(fromId:count:searchDirection:)\/title","value":"loadMessagesStartFromId:count:searchDirection:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessagesStart(fromId:count:searchDirection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesStartFromId:count:searchDirection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1deleteAllMessages(_:)\/title","value":"deleteAllMessages:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1deleteAllMessages(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteAllMessages:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessagesStart(fromId:count:searchDirection:completion:)\/title","value":"loadMessagesStartFromId:count:searchDirection:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessagesStart(fromId:count:searchDirection:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesStartFromId:count:searchDirection:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessage(withId:error:)\/title","value":"loadMessageWithId:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessage(withId:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessageWithId:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1markMessageAsRead(withId:error:)\/title","value":"markMessageAsReadWithId:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1markMessageAsRead(withId:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markMessageAsReadWithId:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(from:to:count:)\/title","value":"loadMessagesFrom:to:count:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadMessages(from:to:count:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesFrom:to:count:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1removeMessages(fromServerMessageIds:completion:)\/title","value":"removeMessagesFromServerMessageIds:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1removeMessages(fromServerMessageIds:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeMessagesFromServerMessageIds:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)\/title","value":"loadCustomMsgWithKeyword:timestamp:count:fromUser:searchDirection:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1loadCustomMsg(withKeyword:timestamp:count:fromUser:searchDirection:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadCustomMsgWithKeyword:timestamp:count:fromUser:searchDirection:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1messagesCount\/title","value":"messagesCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1messagesCount\/fragments","value":[{"kind":"identifier","text":"messagesCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1ext\/title","value":"ext"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1ext\/fragments","value":[{"kind":"identifier","text":"ext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1updateMessageChange(_:error:)\/title","value":"updateMessageChange:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1updateMessageChange(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateMessageChange:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1latestMessage\/title","value":"latestMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1latestMessage\/fragments","value":[{"kind":"identifier","text":"latestMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1removeMessagesFromServer(withTimeStamp:completion:)\/title","value":"removeMessagesFromServerWithTimeStamp:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1removeMessagesFromServer(withTimeStamp:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeMessagesFromServerWithTimeStamp:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}