{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupSharedFile"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupsharedfile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupsharedfile"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The group shared file object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupSharedFile"}],"title":"AgoraChatGroupSharedFile","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatGroupSharedFile","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/init(id:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/createTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/createdAt","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileOwner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileSize"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/fileName":{"role":"symbol","title":"fileName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The name of the file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileName"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/filename"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/createdAt":{"role":"symbol","title":"createdAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The Unix timestamp for creating the file, in ms."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/createdAt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createdAt"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/createdat"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/init(id:)":{"role":"symbol","title":"init(id:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Gets the shared file instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/init(id:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedFileWithId:"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/init(id:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/fileId":{"role":"symbol","title":"fileId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The file ID, which is the unique identifier of a file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileId"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/fileid"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile":{"role":"symbol","title":"AgoraChatGroupSharedFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupSharedFile"}],"abstract":[{"type":"text","text":"The group shared file object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/fileOwner":{"role":"symbol","title":"fileOwner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The owner of the file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileOwner"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/fileowner"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/createTime":{"deprecated":true,"role":"symbol","title":"createTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Create Time of File"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/createTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTime"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/createtime"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupSharedFile/fileSize":{"role":"symbol","title":"fileSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"The data length (bytes) of the file."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileSize"}],"url":"\/documentation\/agorachat\/agorachatgroupsharedfile\/filesize"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupSharedFile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/createTime","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/createdAt","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileName","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileOwner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/fileSize"]},{"title":"Type Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupSharedFile\/init(id:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupSharedFile"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileName\/title","value":"fileName"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileName\/fragments","value":[{"kind":"identifier","text":"fileName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1createdAt\/title","value":"createdAt"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1createdAt\/fragments","value":[{"kind":"identifier","text":"createdAt"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1init(id:)\/title","value":"sharedFileWithId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1init(id:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedFileWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileId\/title","value":"fileId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileId\/fragments","value":[{"kind":"identifier","text":"fileId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile\/title","value":"AgoraChatGroupSharedFile"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupSharedFile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileOwner\/title","value":"fileOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileOwner\/fragments","value":[{"kind":"identifier","text":"fileOwner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1createTime\/title","value":"createTime"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1createTime\/fragments","value":[{"kind":"identifier","text":"createTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileSize\/title","value":"fileSize"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupSharedFile~1fileSize\/fragments","value":[{"kind":"identifier","text":"fileSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}