{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroom"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject","doc:\/\/com.easemob.AgoraChat\/s7CVarArgP","doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP","doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The chat room object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"}],"title":"AgoraChatroom","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChatroom","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatroom"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/init()","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/init(id:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/adminList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/announcement","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/blacklist","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/chatroomId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/description","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/isMuteAllMembers","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/maxMembersCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/maxOccupantsCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/memberList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/members","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/membersCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/muteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/occupants","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/occupantsCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/owner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/permissionType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/subject","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/whiteList-5ujq2","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/whitelist-fvbw"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/occupantsCount":{"role":"symbol","title":"occupantsCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"occupantsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The current number of members in the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/occupantsCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"occupantsCount"}],"url":"\/documentation\/agorachat\/agorachatroom\/occupantscount"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/occupants":{"deprecated":true,"role":"symbol","title":"occupants","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"occupants"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Deprecated, please use - members instead. The list of members in the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/occupants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"occupants"}],"url":"\/documentation\/agorachat\/agorachatroom\/occupants"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/muteList":{"role":"symbol","title":"muteList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The list of muted members."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/muteList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteList"}],"url":"\/documentation\/agorachat\/agorachatroom\/mutelist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/members":{"deprecated":true,"role":"symbol","title":"members","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"members"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Deprecated, please use -memberList instead. The list of members in the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/members","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"members"}],"url":"\/documentation\/agorachat\/agorachatroom\/members"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/adminList":{"role":"symbol","title":"adminList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adminList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The admins of the chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/adminList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adminList"}],"url":"\/documentation\/agorachat\/agorachatroom\/adminlist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/chatroomId":{"role":"symbol","title":"chatroomId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatroomId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The chat room ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/chatroomId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomId"}],"url":"\/documentation\/agorachat\/agorachatroom\/chatroomid"},"doc://com.easemob.AgoraChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s23CustomStringConvertibleP"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/maxOccupantsCount":{"role":"symbol","title":"maxOccupantsCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxOccupantsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The maximum member number of the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/maxOccupantsCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxOccupantsCount"}],"url":"\/documentation\/agorachat\/agorachatroom\/maxoccupantscount"},"doc://com.easemob.AgoraChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.easemob.AgoraChat\/s28CustomDebugStringConvertibleP"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom":{"role":"symbol","title":"AgoraChatroom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"}],"abstract":[{"type":"text","text":"The chat room object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatroom"}],"url":"\/documentation\/agorachat\/agorachatroom"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/permissionType":{"role":"symbol","title":"permissionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatroomPermissionType","preciseIdentifier":"c:@E@AgoraChatroomPermissionType"}],"abstract":[{"type":"text","text":"The chatroom membership type of the current login account."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/permissionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"permissionType"}],"url":"\/documentation\/agorachat\/agorachatroom\/permissiontype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/blacklist":{"role":"symbol","title":"blacklist","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blacklist"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The blocklist of the chatroom."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/blacklist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"blacklist"}],"url":"\/documentation\/agorachat\/agorachatroom\/blacklist"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/maxMembersCount":{"deprecated":true,"role":"symbol","title":"maxMembersCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMembersCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Deprecated, please use -maxOccupantsCount instead.The maximum member number of the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/maxMembersCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxMembersCount"}],"url":"\/documentation\/agorachat\/agorachatroom\/maxmemberscount"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/whiteList-5ujq2":{"deprecated":true,"role":"symbol","title":"whiteList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whiteList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"List of whitelist members"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/whiteList-5ujq2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"whiteList"}],"url":"\/documentation\/agorachat\/agorachatroom\/whitelist-5ujq2"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/init()":{"deprecated":true,"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!()"}],"abstract":[{"type":"text","text":"Deprecated, please use  {@link +chatroomWithId:}  instead.Initializes chatroom instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/agorachat\/agorachatroom\/init()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/whitelist-fvbw":{"role":"symbol","title":"whitelist","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whitelist"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The allowlist members "}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/whitelist-fvbw","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"whitelist"}],"url":"\/documentation\/agorachat\/agorachatroom\/whitelist-fvbw"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/membersCount":{"deprecated":true,"role":"symbol","title":"membersCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"membersCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Deprecated, please use -occupantsCount instead. The total number of members in the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/membersCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"membersCount"}],"url":"\/documentation\/agorachat\/agorachatroom\/memberscount"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/announcement":{"role":"symbol","title":"announcement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"announcement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The announcement of the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/announcement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"announcement"}],"url":"\/documentation\/agorachat\/agorachatroom\/announcement"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/owner":{"role":"symbol","title":"owner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"owner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The owner of the chat room. There is only one owner per chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/owner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"owner"}],"url":"\/documentation\/agorachat\/agorachatroom\/owner"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/isMuteAllMembers":{"role":"symbol","title":"isMuteAllMembers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMuteAllMembers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether all members of the chat room are muted."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/isMuteAllMembers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isMuteAllMembers"}],"url":"\/documentation\/agorachat\/agorachatroom\/ismuteallmembers"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The description of chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/agorachat\/agorachatroom\/description"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/init(id:)":{"role":"symbol","title":"init(id:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Constructs a chatroom instance with chatroom ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/init(id:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatroomWithId:"}],"url":"\/documentation\/agorachat\/agorachatroom\/init(id:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/subject":{"role":"symbol","title":"subject","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The subject of the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/subject","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subject"}],"url":"\/documentation\/agorachat\/agorachatroom\/subject"},"doc://com.easemob.AgoraChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.easemob.AgoraChat\/s7CVarArgP"},"doc://com.easemob.AgoraChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatroom/memberList":{"role":"symbol","title":"memberList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The list of members in the chat room."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/memberList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberList"}],"url":"\/documentation\/agorachat\/agorachatroom\/memberlist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatroom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatroom"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChatroom"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/adminList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/announcement","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/blacklist","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/chatroomId","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/description","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/isMuteAllMembers","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/maxMembersCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/maxOccupantsCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/memberList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/members","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/membersCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/muteList","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/occupants","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/occupantsCount","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/owner","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/permissionType","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/subject","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/whiteList-5ujq2","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/whitelist-fvbw"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/init()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatroom\/init(id:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatroom"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1occupantsCount\/title","value":"occupantsCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1occupantsCount\/fragments","value":[{"kind":"identifier","text":"occupantsCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1occupants\/title","value":"occupants"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1occupants\/fragments","value":[{"kind":"identifier","text":"occupants"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1muteList\/title","value":"muteList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1muteList\/fragments","value":[{"kind":"identifier","text":"muteList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1members\/title","value":"members"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1members\/fragments","value":[{"kind":"identifier","text":"members"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1adminList\/title","value":"adminList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1adminList\/fragments","value":[{"kind":"identifier","text":"adminList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1chatroomId\/title","value":"chatroomId"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1chatroomId\/fragments","value":[{"kind":"identifier","text":"chatroomId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1maxOccupantsCount\/title","value":"maxOccupantsCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1maxOccupantsCount\/fragments","value":[{"kind":"identifier","text":"maxOccupantsCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/title","value":"AgoraChatroom"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom\/fragments","value":[{"kind":"identifier","text":"AgoraChatroom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1permissionType\/title","value":"permissionType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1permissionType\/fragments","value":[{"kind":"identifier","text":"permissionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1blacklist\/title","value":"blacklist"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1blacklist\/fragments","value":[{"kind":"identifier","text":"blacklist"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1maxMembersCount\/title","value":"maxMembersCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1maxMembersCount\/fragments","value":[{"kind":"identifier","text":"maxMembersCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1whiteList-5ujq2\/title","value":"whiteList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1whiteList-5ujq2\/fragments","value":[{"kind":"identifier","text":"whiteList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1whitelist-fvbw\/title","value":"whitelist"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1whitelist-fvbw\/fragments","value":[{"kind":"identifier","text":"whitelist"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1membersCount\/title","value":"membersCount"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1membersCount\/fragments","value":[{"kind":"identifier","text":"membersCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1announcement\/title","value":"announcement"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1announcement\/fragments","value":[{"kind":"identifier","text":"announcement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1owner\/title","value":"owner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1owner\/fragments","value":[{"kind":"identifier","text":"owner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1isMuteAllMembers\/title","value":"isMuteAllMembers"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1isMuteAllMembers\/fragments","value":[{"kind":"identifier","text":"isMuteAllMembers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1init(id:)\/title","value":"chatroomWithId:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1init(id:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"chatroomWithId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1subject\/title","value":"subject"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1subject\/fragments","value":[{"kind":"identifier","text":"subject"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1memberList\/title","value":"memberList"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatroom~1memberList\/fragments","value":[{"kind":"identifier","text":"memberList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}