{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/areacode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/areacode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/SQ","doc:\/\/com.easemob.AgoraChat\/SH","doc:\/\/com.easemob.AgoraChat\/SY","doc:\/\/com.easemob.AgoraChat\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/AS","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/CN","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/EU","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/GLOB","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/IN","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/JP","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/NA"]},{"title":"Initializers","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/Equatable-Implementations","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"}],"title":"AreaCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AreaCode","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AreaCode"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/EU":{"role":"symbol","title":"AreaCode.EU","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EU"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/EU","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeEU"}],"url":"\/documentation\/agorachat\/areacode\/eu"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorachat\/areacode\/init(rawvalue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/AS":{"role":"symbol","title":"AreaCode.AS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AS"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/AS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeAS"}],"url":"\/documentation\/agorachat\/areacode\/as"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode":{"role":"symbol","title":"AreaCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCode"}],"url":"\/documentation\/agorachat\/areacode"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/CN":{"role":"symbol","title":"AreaCode.CN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CN"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/CN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeCN"}],"url":"\/documentation\/agorachat\/areacode\/cn"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/areacode\/equatable-implementations"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/IN":{"role":"symbol","title":"AreaCode.IN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"IN"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/IN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeIN"}],"url":"\/documentation\/agorachat\/areacode\/in"},"doc://com.easemob.AgoraChat/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.easemob.AgoraChat\/SY"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/GLOB":{"role":"symbol","title":"AreaCode.GLOB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"GLOB"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/GLOB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeGLOB"}],"url":"\/documentation\/agorachat\/areacode\/glob"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/NA":{"role":"symbol","title":"AreaCode.NA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NA"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/NA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeNA"}],"url":"\/documentation\/agorachat\/areacode\/na"},"doc://com.easemob.AgoraChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.easemob.AgoraChat\/SQ"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorachat\/areacode\/rawrepresentable-implementations"},"doc://com.easemob.AgoraChat/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.easemob.AgoraChat\/s8SendableP"},"doc://com.easemob.AgoraChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.easemob.AgoraChat\/SH"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/JP":{"role":"symbol","title":"AreaCode.JP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JP"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/JP","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeJP"}],"url":"\/documentation\/agorachat\/areacode\/jp"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AreaCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AreaCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AreaCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/AS","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/CN","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/EU","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/GLOB","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/IN","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/JP","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/NA"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1EU\/title","value":"AreaCodeEU"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1EU\/fragments","value":[{"kind":"identifier","text":"AreaCodeEU"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1AS\/title","value":"AreaCodeAS"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1AS\/fragments","value":[{"kind":"identifier","text":"AreaCodeAS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/title","value":"AreaCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/fragments","value":[{"kind":"identifier","text":"AreaCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1CN\/title","value":"AreaCodeCN"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1CN\/fragments","value":[{"kind":"identifier","text":"AreaCodeCN"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1IN\/title","value":"AreaCodeIN"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1IN\/fragments","value":[{"kind":"identifier","text":"AreaCodeIN"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1GLOB\/title","value":"AreaCodeGLOB"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1GLOB\/fragments","value":[{"kind":"identifier","text":"AreaCodeGLOB"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1NA\/title","value":"AreaCodeNA"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1NA\/fragments","value":[{"kind":"identifier","text":"AreaCodeNA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1JP\/title","value":"AreaCodeJP"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1JP\/fragments","value":[{"kind":"identifier","text":"AreaCodeJP"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}