{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatStatisticsManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol contains methods that are used to calculate the number of local messages of certain types sent and\/or received in a specified period, as well as their traffic."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This traffic statistics function is disabled by default. To use this function, you need to enable it by setting {@link AgoraChatOptions#enableStatistics} prior to the SDK initialization. The SDK can collect statistics of messages that are sent and received after this function is enabled."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK only calculates the traffic of messages that are sent and received within the last 30 days after the traffic statistics function is enabled."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The message traffic is calculated as follows:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For a text, command, location or custom message, the message traffic is the traffic of the message body."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For an image or video message, the message traffic is the traffic sum of the message body, the image or video file, and the thumbnail."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For a file or voice message, the message traffic is the traffic sum of the message body and the attachment."}]}]}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For messages with attachments, the traffic will be calculated only if the download is successful."},{"type":"text","text":" "},{"type":"text","text":"If an attachment is downloaded multiple times, its download traffic will be accumulated."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For roaming messages pulled from the server, if they already exist in the local database, the SDK ignores them during traffic calculation."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK only measures the traffic of local messages, but not the actual message traffic. Generally, the calculated traffic volume is smaller than the actual traffic because of the following:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The traffic of the common protocol data generated during message sending is not considered;"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For the received messages, the server aggregates them and adds common fields. During traffic statistics, the SDK only calculates the traffic of individual messages, but ignoring the traffic of common fields."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatstatisticsmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatstatisticsmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The protocol that defines statistical operations of message traffic."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"title":"IAgoraChatStatisticsManager","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)IAgoraChatStatisticsManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageCount(withStart:end:direction:type:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatistics(byId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatisticsSize(withStart:end:direction:type:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager/getMessageStatistics(byId:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessageStatisticsById:"}],"role":"symbol","title":"getMessageStatistics(byId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatistics"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatistics","preciseIdentifier":"c:objc(cs)AgoraChatMessageStatistics"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the message traffic statistics by message ID."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatistics(byId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatistics(byid:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager/getMessageCount(withStart:end:direction:type:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessageCountWithStart:end:direction:type:"}],"role":"symbol","title":"getMessageCount(withStart:end:direction:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsDirection","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsType","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Gets the count of messages of certain types that are sent and\/or received in a specified period."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageCount(withStart:end:direction:type:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagecount(withstart:end:direction:type:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager/getMessageStatisticsSize(withStart:end:direction:type:)":{"navigatorTitle":[{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:end:direction:type:"}],"role":"symbol","title":"getMessageStatisticsSize(withStart:end:direction:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMessageStatisticsSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsDirection","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsDirection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageStatisticsType","preciseIdentifier":"c:@E@AgoraChatMessageStatisticsType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Gets the total traffic amount of messages that meet the statistical conditions."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatisticsSize(withStart:end:direction:type:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatstatisticsmanager\/getmessagestatisticssize(withstart:end:direction:type:)"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatStatisticsManager":{"role":"symbol","title":"IAgoraChatStatisticsManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"abstract":[{"type":"text","text":"The protocol that defines statistical operations of message traffic."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}],"url":"\/documentation\/agorachat\/iagorachatstatisticsmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IAgoraChatStatisticsManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageCount(withStart:end:direction:type:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatistics(byId:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatStatisticsManager\/getMessageStatisticsSize(withStart:end:direction:type:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatStatisticsManager"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatistics(byId:)\/title","value":"getMessageStatisticsById:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatistics(byId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageStatisticsById:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageCount(withStart:end:direction:type:)\/title","value":"getMessageCountWithStart:end:direction:type:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageCount(withStart:end:direction:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageCountWithStart:end:direction:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatisticsSize(withStart:end:direction:type:)\/title","value":"getMessageStatisticsSizeWithStart:end:direction:type:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager~1getMessageStatisticsSize(withStart:end:direction:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMessageStatisticsSizeWithStart:end:direction:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager\/title","value":"IAgoraChatStatisticsManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatStatisticsManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatStatisticsManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}