{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPresenceManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatpresencemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatpresencemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The presence management protocol that defines how to manage presence states."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPresenceManager"}],"title":"IAgoraChatPresenceManager","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)IAgoraChatPresenceManager","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/add(_:delegateQueue:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/fetchPresenceStatus(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/fetchSubscribedMembers(withPageNum:pageSize:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/publishPresence(withDescription:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/remove(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/subscribe(_:expiry:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/unsubscribe(_:completion:)"]}],"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager":{"role":"symbol","title":"IAgoraChatPresenceManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPresenceManager"}],"abstract":[{"type":"text","text":"The presence management protocol that defines how to manage presence states."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}],"url":"\/documentation\/agorachat\/iagorachatpresencemanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/fetchSubscribedMembers(withPageNum:pageSize:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"fetchSubscribedMembersWithPageNum:pageSize:Completion:"}],"role":"symbol","title":"fetchSubscribedMembers(withPageNum:pageSize:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSubscribedMembers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageNum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Uses pagination to get a list of users whose presence states you have subscribed to."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/fetchSubscribedMembers(withPageNum:pageSize:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/fetchsubscribedmembers(withpagenum:pagesize:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/publishPresence(withDescription:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"publishPresenceWithDescription:completion:"}],"role":"symbol","title":"publishPresence(withDescription:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishPresence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Publishes a custom presence state."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/publishPresence(withDescription:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/publishpresence(withdescription:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/subscribe(_:expiry:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"subscribe:expiry:completion:"}],"role":"symbol","title":"subscribe(_:expiry:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"expiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatPresence","preciseIdentifier":"c:objc(cs)AgoraChatPresence"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Subscribes to a user’s presence states. If the subscription succeeds, the subscriber will receive the callback when the user’s presence state changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/subscribe(_:expiry:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/subscribe(_:expiry:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/fetchPresenceStatus(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"fetchPresenceStatus:completion:"}],"role":"symbol","title":"fetchPresenceStatus(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPresenceStatus"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"AgoraChatPresence","preciseIdentifier":"c:objc(cs)AgoraChatPresence"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the current presence state of users."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/fetchPresenceStatus(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/fetchpresencestatus(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/unsubscribe(_:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"unsubscribe:completion:"}],"role":"symbol","title":"unsubscribe(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Unsubscribes from a user’s presence states."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/unsubscribe(_:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/unsubscribe(_:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/add(_:delegateQueue:)":{"navigatorTitle":[{"kind":"identifier","text":"addDelegate:delegateQueue:"}],"role":"symbol","title":"add(_:delegateQueue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatPresenceManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatPresenceManagerDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegateQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Adds a delegate."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/add(_:delegateQueue:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/add(_:delegatequeue:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatPresenceManager/remove(_:)":{"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"role":"symbol","title":"remove(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatPresenceManagerDelegate","preciseIdentifier":"c:objc(pl)AgoraChatPresenceManagerDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes a delegate."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/remove(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatpresencemanager\/remove(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IAgoraChatPresenceManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/add(_:delegateQueue:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/fetchPresenceStatus(_:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/fetchSubscribedMembers(withPageNum:pageSize:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/publishPresence(withDescription:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/remove(_:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/subscribe(_:expiry:completion:)","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatPresenceManager\/unsubscribe(_:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.easemob.AgoraChat\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatPresenceManager"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager\/title","value":"IAgoraChatPresenceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatPresenceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1fetchSubscribedMembers(withPageNum:pageSize:completion:)\/title","value":"fetchSubscribedMembersWithPageNum:pageSize:Completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1fetchSubscribedMembers(withPageNum:pageSize:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchSubscribedMembersWithPageNum:pageSize:Completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1publishPresence(withDescription:completion:)\/title","value":"publishPresenceWithDescription:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1publishPresence(withDescription:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publishPresenceWithDescription:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1subscribe(_:expiry:completion:)\/title","value":"subscribe:expiry:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1subscribe(_:expiry:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribe:expiry:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1fetchPresenceStatus(_:completion:)\/title","value":"fetchPresenceStatus:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1fetchPresenceStatus(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPresenceStatus:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1unsubscribe(_:completion:)\/title","value":"unsubscribe:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1unsubscribe(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribe:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1add(_:delegateQueue:)\/title","value":"addDelegate:delegateQueue:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1add(_:delegateQueue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDelegate:delegateQueue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1remove(_:)\/title","value":"removeDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatPresenceManager~1remove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}