{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/kpushnodisturbingstartm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/kpushnodisturbingstartm"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/kPushNoDisturbingStartM","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"kPushNoDisturbingStartM","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:AgoraChatPushOptions.h@440@macro@kPushNoDisturbingStartM","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"kPushNoDisturbingStartM"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/kPushNoDisturbingStartM":{"role":"symbol","title":"kPushNoDisturbingStartM","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/kPushNoDisturbingStartM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kPushNoDisturbingStartM"}],"url":"\/documentation\/agorachat\/kpushnodisturbingstartm"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"kPushNoDisturbingStartM"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"kPushNoDisturbingStartM"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1kPushNoDisturbingStartM\/title","value":"kPushNoDisturbingStartM"}],"traits":[{"interfaceLanguage":"occ"}]}]}