{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"KSDK_GROUP_MINUSERSCOUNT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/ksdk_group_minuserscount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/ksdk_group_minuserscount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/KSDK_GROUP_MINUSERSCOUNT","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"KSDK_GROUP_MINUSERSCOUNT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"KSDK_GROUP_MINUSERSCOUNT","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:AgoraChatGroupOptions.h@170@macro@KSDK_GROUP_MINUSERSCOUNT","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"KSDK_GROUP_MINUSERSCOUNT"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/KSDK_GROUP_MINUSERSCOUNT":{"role":"symbol","title":"KSDK_GROUP_MINUSERSCOUNT","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"KSDK_GROUP_MINUSERSCOUNT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/KSDK_GROUP_MINUSERSCOUNT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KSDK_GROUP_MINUSERSCOUNT"}],"url":"\/documentation\/agorachat\/ksdk_group_minuserscount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"KSDK_GROUP_MINUSERSCOUNT"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"KSDK_GROUP_MINUSERSCOUNT"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1KSDK_GROUP_MINUSERSCOUNT\/title","value":"KSDK_GROUP_MINUSERSCOUNT"}],"traits":[{"interfaceLanguage":"occ"}]}]}