{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presenceStatusDidChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presences"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence","preciseIdentifier":"c:objc(cs)AgoraChatPresence","text":"AgoraChatPresence"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpresencemanagerdelegate\/presencestatusdidchanged(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpresencemanagerdelegate\/presencestatusdidchanged(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceManagerDelegate\/presenceStatusDidChanged(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the presence state of a subscribed user changes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presenceStatusDidChanged"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatPresence","preciseIdentifier":"c:objc(cs)AgoraChatPresence"},{"kind":"text","text":"])"}],"title":"presenceStatusDidChanged(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatPresenceManagerDelegate(im)presenceStatusDidChanged:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"presenceStatusDidChanged:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresenceManagerDelegate":{"role":"symbol","title":"AgoraChatPresenceManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresenceManagerDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol that defines presence callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresenceManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatpresencemanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence":{"role":"symbol","title":"AgoraChatPresence","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresence"}],"abstract":[{"type":"text","text":"The presence property class that contains presence properties, including the publisher’s user ID and current presence state, and the platform used by the online device, as well as the presence’s extension information, update time, and subscription expiration time."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresence"}],"url":"\/documentation\/agorachat\/agorachatpresence"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresenceManagerDelegate/presenceStatusDidChanged(_:)":{"role":"symbol","title":"presenceStatusDidChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presenceStatusDidChanged"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraChatPresence","preciseIdentifier":"c:objc(cs)AgoraChatPresence"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Occurs when the presence state of a subscribed user changes."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceManagerDelegate\/presenceStatusDidChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presenceStatusDidChanged:"}],"url":"\/documentation\/agorachat\/agorachatpresencemanagerdelegate\/presencestatusdidchanged(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presenceStatusDidChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presenceStatusDidChanged:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"presenceStatusDidChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatPresence *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"presences"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceManagerDelegate\/title","value":"AgoraChatPresenceManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresenceManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence\/title","value":"AgoraChatPresence"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceManagerDelegate~1presenceStatusDidChanged(_:)\/title","value":"presenceStatusDidChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceManagerDelegate~1presenceStatusDidChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presenceStatusDidChanged:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}