{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simpleBanner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpushdisplaystyle\/simplebanner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpushdisplaystyle\/simplebanner"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/simpleBanner","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simpleBanner"}],"title":"AgoraChatPushDisplayStyle.simpleBanner","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatPushDisplayStyle@AgoraChatPushDisplayStyleSimpleBanner","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle":{"role":"symbol","title":"AgoraChatPushDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"abstract":[{"type":"text","text":"The display style of push message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushDisplayStyle/simpleBanner":{"role":"symbol","title":"AgoraChatPushDisplayStyle.simpleBanner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simpleBanner"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushDisplayStyle\/simpleBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}],"url":"\/documentation\/agorachat\/agorachatpushdisplaystyle\/simplebanner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatPushDisplayStyleSimpleBanner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/title","value":"AgoraChatPushDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1simpleBanner\/title","value":"AgoraChatPushDisplayStyleSimpleBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushDisplayStyle~1simpleBanner\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushDisplayStyleSimpleBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}