{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloading"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatdownloadstatus\/downloading"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatdownloadstatus\/downloading"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus\/downloading","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloading"}],"title":"AgoraChatDownloadStatus.downloading","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatDownloadStatus@AgoraChatDownloadStatusDownloading","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatusDownloading"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatDownloadStatus/downloading":{"role":"symbol","title":"AgoraChatDownloadStatus.downloading","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloading"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus\/downloading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatusDownloading"}],"url":"\/documentation\/agorachat\/agorachatdownloadstatus\/downloading"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatDownloadStatus":{"role":"symbol","title":"AgoraChatDownloadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The status types for downloading the file message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatdownloadstatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatDownloadStatusDownloading"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatusDownloading"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatDownloadStatusDownloading"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus~1downloading\/title","value":"AgoraChatDownloadStatusDownloading"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus~1downloading\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatusDownloading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/title","value":"AgoraChatDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}