{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"description"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"code"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","preciseIdentifier":"c:@E@AgoraChatErrorCode","text":"AgoraChatErrorCode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachaterror\/init(description:code:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachaterror\/init(description:code:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError\/init(description:code:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes an error instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatErrorCode","preciseIdentifier":"c:@E@AgoraChatErrorCode"},{"kind":"text","text":")"}],"title":"init(description:code:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)AgoraChatError(im)initWithDescription:code:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDescription:code:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError/init(description:code:)":{"role":"symbol","title":"init(description:code:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatErrorCode","preciseIdentifier":"c:@E@AgoraChatErrorCode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes an error instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError\/init(description:code:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDescription:code:"}],"url":"\/documentation\/agorachat\/agorachaterror\/init(description:code:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode":{"role":"symbol","title":"AgoraChatErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorCode"}],"url":"\/documentation\/agorachat\/agorachaterrorcode"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDescription:code:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDescription:code:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDescription:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aDescription"},{"kind":"text","text":" "},{"kind":"identifier","text":"code:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","preciseIdentifier":"c:@E@AgoraChatErrorCode","text":"AgoraChatErrorCode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError~1init(description:code:)\/title","value":"initWithDescription:code:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError~1init(description:code:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDescription:code:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/title","value":"AgoraChatErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}