{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSelfIdsOnOtherPlatform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCompletionBlock"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an asynchronous method."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatcontactmanager\/getselfidsonotherplatform(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatcontactmanager\/getselfidsonotherplatform(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatContactManager\/getSelfIdsOnOtherPlatform(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the ID list of the current account on another platform (Windows or Web)"},{"type":"text","text":" "},{"type":"text","text":"The ID usage is similar to friend username."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getSelfIdsOnOtherPlatformWithCompletion:"}],"role":"symbol","title":"getSelfIdsOnOtherPlatform(completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSelfIdsOnOtherPlatform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatContactManager(im)getSelfIdsOnOtherPlatformWithCompletion:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatContactManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatContactManager/getSelfIdsOnOtherPlatform(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getSelfIdsOnOtherPlatformWithCompletion:"}],"role":"symbol","title":"getSelfIdsOnOtherPlatform(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSelfIdsOnOtherPlatform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Gets the ID list of the current account on another platform (Windows or Web)"},{"type":"text","text":" "},{"type":"text","text":"The ID usage is similar to friend username."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatContactManager\/getSelfIdsOnOtherPlatform(completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatcontactmanager\/getselfidsonotherplatform(completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatContactManager":{"role":"symbol","title":"IAgoraChatContactManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatContactManager"}],"abstract":[{"type":"text","text":"The contact management."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatContactManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatContactManager"}],"url":"\/documentation\/agorachat\/iagorachatcontactmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getSelfIdsOnOtherPlatformWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSelfIdsOnOtherPlatformWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getSelfIdsOnOtherPlatformWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<NSString *> *, AgoraChatError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)AgoraChatError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aCompletionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatContactManager~1getSelfIdsOnOtherPlatform(completion:)\/title","value":"getSelfIdsOnOtherPlatformWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatContactManager~1getSelfIdsOnOtherPlatform(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getSelfIdsOnOtherPlatformWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatContactManager\/title","value":"IAgoraChatContactManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatContactManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatContactManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}