{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDetails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceStatusDetail","preciseIdentifier":"c:objc(cs)AgoraChatPresenceStatusDetail","text":"AgoraChatPresenceStatusDetail"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpresence\/statusdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpresence\/statusdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The details of the current presence state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDetails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatPresenceStatusDetail","preciseIdentifier":"c:objc(cs)AgoraChatPresenceStatusDetail"},{"kind":"text","text":"]?"}],"title":"statusDetails","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatPresence(py)statusDetails","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"statusDetails"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresenceStatusDetail":{"role":"symbol","title":"AgoraChatPresenceStatusDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresenceStatusDetail"}],"abstract":[{"type":"text","text":"The presence details, including the platform used by the publisher’s current online device and the current presence state."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresenceStatusDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresenceStatusDetail"}],"url":"\/documentation\/agorachat\/agorachatpresencestatusdetail"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence/statusDetails":{"role":"symbol","title":"statusDetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDetails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraChatPresenceStatusDetail","preciseIdentifier":"c:objc(cs)AgoraChatPresenceStatusDetail"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The details of the current presence state."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence\/statusDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusDetails"}],"url":"\/documentation\/agorachat\/agorachatpresence\/statusdetails"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPresence":{"role":"symbol","title":"AgoraChatPresence","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPresence"}],"abstract":[{"type":"text","text":"The presence property class that contains presence properties, including the publisher’s user ID and current presence state, and the platform used by the online device, as well as the presence’s extension information, update time, and subscription expiration time."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPresence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPresence"}],"url":"\/documentation\/agorachat\/agorachatpresence"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"statusDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"statusDetails"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<AgoraChatPresenceStatusDetail *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"statusDetails"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceStatusDetail\/title","value":"AgoraChatPresenceStatusDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresenceStatusDetail\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresenceStatusDetail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1statusDetails\/title","value":"statusDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence~1statusDetails\/fragments","value":[{"kind":"identifier","text":"statusDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence\/title","value":"AgoraChatPresence"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPresence\/fragments","value":[{"kind":"identifier","text":"AgoraChatPresence"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}