{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagestatus\/pending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagestatus\/pending"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/pending","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"title":"AgoraChatMessageStatus.pending","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMessageStatus@AgoraChatMessageStatusPending","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus":{"role":"symbol","title":"AgoraChatMessageStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatus"}],"abstract":[{"type":"text","text":"The message delivery states."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatus"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatus/pending":{"role":"symbol","title":"AgoraChatMessageStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}],"url":"\/documentation\/agorachat\/agorachatmessagestatus\/pending"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageStatusPending"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus\/title","value":"AgoraChatMessageStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1pending\/title","value":"AgoraChatMessageStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatus~1pending\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatusPending"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}