{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatloglevel\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatloglevel\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLogLevel\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Output warnings and errors."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"title":"AgoraChatLogLevel.error","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatLogLevel@AgoraChatLogLevelError","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatLogLevelError"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLogLevel"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLogLevel":{"role":"symbol","title":"AgoraChatLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatLogLevel"}],"abstract":[{"type":"text","text":"Log output level types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLogLevel"}],"url":"\/documentation\/agorachat\/agorachatloglevel"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatLogLevel/error":{"role":"symbol","title":"AgoraChatLogLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"Output warnings and errors."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatLogLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatLogLevelError"}],"url":"\/documentation\/agorachat\/agorachatloglevel\/error"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatLogLevelError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatLogLevelError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatLogLevelError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLogLevel\/title","value":"AgoraChatLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLogLevel\/fragments","value":[{"kind":"identifier","text":"AgoraChatLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLogLevel~1error\/title","value":"AgoraChatLogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatLogLevel~1error\/fragments","value":[{"kind":"identifier","text":"AgoraChatLogLevelError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}