{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThread"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThread","preciseIdentifier":"c:objc(cs)AgoraChatThread","text":"AgoraChatThread"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatthreadevent\/chatthread"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatthreadevent\/chatthread"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent\/chatThread","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message thread object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThread"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatThread","preciseIdentifier":"c:objc(cs)AgoraChatThread"},{"kind":"text","text":"!"}],"title":"chatThread","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatThreadEvent(py)chatThread","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"chatThread"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadEvent/chatThread":{"role":"symbol","title":"chatThread","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatThread"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatThread","preciseIdentifier":"c:objc(cs)AgoraChatThread"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The message thread object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent\/chatThread","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatThread"}],"url":"\/documentation\/agorachat\/agorachatthreadevent\/chatthread"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadEvent":{"role":"symbol","title":"AgoraChatThreadEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadEvent"}],"abstract":[{"type":"text","text":"The message thread event class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatThreadEvent"}],"url":"\/documentation\/agorachat\/agorachatthreadevent"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThread":{"role":"symbol","title":"AgoraChatThread","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThread"}],"abstract":[{"type":"text","text":"The message thread model class, which defines attributes of a message thread."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThread","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatThread"}],"url":"\/documentation\/agorachat\/agorachatthread"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"chatThread"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chatThread"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThread","preciseIdentifier":"c:objc(cs)AgoraChatThread","text":"AgoraChatThread"},{"kind":"text","text":" * "},{"kind":"identifier","text":"chatThread"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadEvent~1chatThread\/title","value":"chatThread"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadEvent~1chatThread\/fragments","value":[{"kind":"identifier","text":"chatThread"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadEvent\/title","value":"AgoraChatThreadEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatThreadEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThread\/title","value":"AgoraChatThread"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThread\/fragments","value":[{"kind":"identifier","text":"AgoraChatThread"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}