{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EU"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/areacode\/eu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/areacode\/eu"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/EU","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EU"}],"title":"AreaCode.EU","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AreaCode@AreaCodeEU","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AreaCodeEU"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode/EU":{"role":"symbol","title":"AreaCode.EU","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EU"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode\/EU","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCodeEU"}],"url":"\/documentation\/agorachat\/areacode\/eu"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AreaCode":{"role":"symbol","title":"AreaCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AreaCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AreaCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AreaCode"}],"url":"\/documentation\/agorachat\/areacode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AreaCodeEU"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AreaCodeEU"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AreaCodeEU"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1EU\/title","value":"AreaCodeEU"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode~1EU\/fragments","value":[{"kind":"identifier","text":"AreaCodeEU"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/title","value":"AreaCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AreaCode\/fragments","value":[{"kind":"identifier","text":"AreaCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}