{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"andCount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatpageresult\/init(list:andcount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatpageresult\/init(list:andcount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPageResult\/init(list:andCount:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the result instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"andCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(list:andCount:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)AgoraChatPageResult(cm)pageResultWithList:andCount:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"pageResultWithList:andCount:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPageResult"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPageResult":{"role":"symbol","title":"AgoraChatPageResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPageResult"}],"abstract":[{"type":"text","text":"The sub-section result."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPageResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPageResult"}],"url":"\/documentation\/agorachat\/agorachatpageresult"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPageResult/init(list:andCount:)":{"role":"symbol","title":"init(list:andCount:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"andCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the result instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPageResult\/init(list:andCount:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageResultWithList:andCount:"}],"url":"\/documentation\/agorachat\/agorachatpageresult\/init(list:andcount:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"pageResultWithList:andCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pageResultWithList:andCount:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"pageResultWithList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aList"},{"kind":"text","text":" "},{"kind":"identifier","text":"andCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPageResult\/title","value":"AgoraChatPageResult"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPageResult\/fragments","value":[{"kind":"identifier","text":"AgoraChatPageResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPageResult~1init(list:andCount:)\/title","value":"pageResultWithList:andCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPageResult~1init(list:andCount:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pageResultWithList:andCount:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}