{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customExt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCustomExt"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatcustommessagebody\/init(event:customext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatcustommessagebody\/init(event:customext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCustomMessageBody\/init(event:customExt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a custom message body instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customExt"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"title":"init(event:customExt:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)AgoraChatCustomMessageBody(im)initWithEvent:customExt:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEvent:customExt:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCustomMessageBody"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatCustomMessageBody":{"role":"symbol","title":"AgoraChatCustomMessageBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatCustomMessageBody"}],"abstract":[{"type":"text","text":"The custom message body."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCustomMessageBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatCustomMessageBody"}],"url":"\/documentation\/agorachat\/agorachatcustommessagebody"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatCustomMessageBody/init(event:customExt:)":{"role":"symbol","title":"init(event:customExt:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customExt"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes a custom message body instance."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatCustomMessageBody\/init(event:customExt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithEvent:customExt:"}],"url":"\/documentation\/agorachat\/agorachatcustommessagebody\/init(event:customext:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithEvent:customExt:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvent:customExt:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aEvent"},{"kind":"text","text":" "},{"kind":"identifier","text":"customExt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aCustomExt"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCustomMessageBody\/title","value":"AgoraChatCustomMessageBody"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCustomMessageBody\/fragments","value":[{"kind":"identifier","text":"AgoraChatCustomMessageBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCustomMessageBody~1init(event:customExt:)\/title","value":"initWithEvent:customExt:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatCustomMessageBody~1init(event:customExt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvent:customExt:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}