{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/all"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/all","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message is received by the local client."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"title":"AgoraChatMessageStatisticsDirection.all","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMessageStatisticsDirection@AgoraChatMessageStatisticsDirectionAll","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection/all":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"The message is received by the local client."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection\/all"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatisticsDirection":{"role":"symbol","title":"AgoraChatMessageStatisticsDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"abstract":[{"type":"text","text":"The message direction types for querying."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatisticsDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}],"url":"\/documentation\/agorachat\/agorachatmessagestatisticsdirection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageStatisticsDirectionAll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1all\/title","value":"AgoraChatMessageStatisticsDirectionAll"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection~1all\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirectionAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection\/title","value":"AgoraChatMessageStatisticsDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatisticsDirection\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatisticsDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}