{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":"?>?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To insert the message correctly, ensure that the conversation ID of the message is the same as that of the conversation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The message is inserted based on timestamp and the SDK will automatically update attributes of the conversation, including "},{"type":"codeVoice","code":"latestMessage"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatconversation\/insert(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatconversation\/insert(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/insert(_:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inserts a message to a conversation in the local database."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"title":"insert(_:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChatConversation(im)insertMessage:error:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"insertMessage:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation":{"role":"symbol","title":"AgoraChatConversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"abstract":[{"type":"text","text":"The chat conversation class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConversation"}],"url":"\/documentation\/agorachat\/agorachatconversation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/insert(_:error:)":{"role":"symbol","title":"insert(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Inserts a message to a conversation in the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/insert(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"insertMessage:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/insert(_:error:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage":{"role":"symbol","title":"AgoraChatMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"abstract":[{"type":"text","text":"The chat message class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessage"}],"url":"\/documentation\/agorachat\/agorachatmessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"insertMessage:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertMessage:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"insertMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"pError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/title","value":"AgoraChatConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/fragments","value":[{"kind":"identifier","text":"AgoraChatConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1insert(_:error:)\/title","value":"insertMessage:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1insert(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertMessage:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/title","value":"AgoraChatMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}