{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatconversation\/latestmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatconversation\/latestmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/latestMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The latest message in the conversation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"!"}],"title":"latestMessage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatConversation(py)latestMessage","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"latestMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation":{"role":"symbol","title":"AgoraChatConversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"abstract":[{"type":"text","text":"The chat conversation class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConversation"}],"url":"\/documentation\/agorachat\/agorachatconversation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage":{"role":"symbol","title":"AgoraChatMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"abstract":[{"type":"text","text":"The chat message class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessage"}],"url":"\/documentation\/agorachat\/agorachatmessage"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/latestMessage":{"role":"symbol","title":"latestMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"latestMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The latest message in the conversation."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/latestMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"latestMessage"}],"url":"\/documentation\/agorachat\/agorachatconversation\/latestmessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"latestMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"latestMessage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"latestMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/title","value":"AgoraChatConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/fragments","value":[{"kind":"identifier","text":"AgoraChatConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/title","value":"AgoraChatMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1latestMessage\/title","value":"latestMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1latestMessage\/fragments","value":[{"kind":"identifier","text":"latestMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}