{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markMessageAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aMessageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":"?>?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatconversation\/markmessageasread(withid:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatconversation\/markmessageasread(withid:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markMessageAsRead(withId:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Marks a message in the local database as read."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markMessageAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"title":"markMessageAsRead(withId:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChatConversation(im)markMessageAsReadWithId:error:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"markMessageAsReadWithId:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation":{"role":"symbol","title":"AgoraChatConversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"abstract":[{"type":"text","text":"The chat conversation class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConversation"}],"url":"\/documentation\/agorachat\/agorachatconversation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation/markMessageAsRead(withId:error:)":{"role":"symbol","title":"markMessageAsRead(withId:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markMessageAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?>?)"}],"abstract":[{"type":"text","text":"Marks a message in the local database as read."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation\/markMessageAsRead(withId:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"markMessageAsReadWithId:error:"}],"url":"\/documentation\/agorachat\/agorachatconversation\/markmessageasread(withid:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"markMessageAsReadWithId:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markMessageAsReadWithId:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"markMessageAsReadWithId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aMessageId"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"pError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/title","value":"AgoraChatConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/fragments","value":[{"kind":"identifier","text":"AgoraChatConversation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1markMessageAsRead(withId:error:)\/title","value":"markMessageAsReadWithId:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation~1markMessageAsRead(withId:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markMessageAsReadWithId:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}