{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageDirection","preciseIdentifier":"c:@E@AgoraChatMessageDirection","text":"AgoraChatMessageDirection"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Send"},{"type":"text","text":": Messages sent by the current user;"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Receive"},{"type":"text","text":": Messages received by the current user."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagestatistics\/direction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagestatistics\/direction"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics\/direction","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The message direction:"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageDirection","preciseIdentifier":"c:@E@AgoraChatMessageDirection"}],"title":"direction","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatMessageStatistics(py)direction","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"direction"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatistics/direction":{"role":"symbol","title":"direction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageDirection","preciseIdentifier":"c:@E@AgoraChatMessageDirection"}],"abstract":[{"type":"text","text":"The message direction:"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics\/direction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"direction"}],"url":"\/documentation\/agorachat\/agorachatmessagestatistics\/direction"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageDirection":{"role":"symbol","title":"AgoraChatMessageDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageDirection"}],"abstract":[{"type":"text","text":"The message directions."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageDirection"}],"url":"\/documentation\/agorachat\/agorachatmessagedirection"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageStatistics":{"role":"symbol","title":"AgoraChatMessageStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageStatistics"}],"abstract":[{"type":"text","text":"The message traffic statistics."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageStatistics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageStatistics"}],"url":"\/documentation\/agorachat\/agorachatmessagestatistics"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"direction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"direction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageDirection","preciseIdentifier":"c:@E@AgoraChatMessageDirection","text":"AgoraChatMessageDirection"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatistics~1direction\/title","value":"direction"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatistics~1direction\/fragments","value":[{"kind":"identifier","text":"direction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageDirection\/title","value":"AgoraChatMessageDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageDirection\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatistics\/title","value":"AgoraChatMessageStatistics"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageStatistics\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageStatistics"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}