{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aParamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType","text":"AgoraChatSilentModeParamType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparam\/init(paramtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparam\/init(paramtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/init(paramType:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType"},{"kind":"text","text":")"}],"title":"init(paramType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)AgoraChatSilentModeParam(im)initWithParamType:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParamType:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/init(paramType:)":{"role":"symbol","title":"init(paramType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/init(paramType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParamType:"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/init(paramtype:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam":{"role":"symbol","title":"AgoraChatSilentModeParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"abstract":[{"type":"text","text":"The silent message params object"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParamType":{"role":"symbol","title":"AgoraChatSilentModeParamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParamType"}],"abstract":[{"type":"text","text":"Parameter type to no-disturbing mode."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParamType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparamtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithParamType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParamType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParamType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType","text":"AgoraChatSilentModeParamType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aParamType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1init(paramType:)\/title","value":"initWithParamType:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1init(paramType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParamType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam\/title","value":"AgoraChatSilentModeParam"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType\/title","value":"AgoraChatSilentModeParamType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParamType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}