{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType","text":"AgoraChatSilentModeParamType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If parmType is AgoraChatSilentModeParamTypeRemindType，only the remindType parameter is set."},{"type":"text","text":" "},{"type":"text","text":"If parmType is AgoraChatSilentModeParamTypeDuration，only the silentModeDuration parameter is set."},{"type":"text","text":" "},{"type":"text","text":"If parmType is AgoraChatSilentModeParamTypeInterval，only the silentModeStartTime and silentModeEndTime  parameters are set."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparam\/paramtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatsilentmodeparam\/paramtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/paramType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parameter type for silent messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType"}],"title":"paramType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatSilentModeParam(py)paramType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"paramType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam":{"role":"symbol","title":"AgoraChatSilentModeParam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"abstract":[{"type":"text","text":"The silent message params object"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParam/paramType":{"role":"symbol","title":"paramType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType"}],"abstract":[{"type":"text","text":"Parameter type for silent messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParam\/paramType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paramType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparam\/paramtype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeParamType":{"role":"symbol","title":"AgoraChatSilentModeParamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeParamType"}],"abstract":[{"type":"text","text":"Parameter type to no-disturbing mode."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeParamType"}],"url":"\/documentation\/agorachat\/agorachatsilentmodeparamtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"paramType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"paramType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeParamType","preciseIdentifier":"c:@E@AgoraChatSilentModeParamType","text":"AgoraChatSilentModeParamType"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam\/title","value":"AgoraChatSilentModeParam"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParam"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1paramType\/title","value":"paramType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParam~1paramType\/fragments","value":[{"kind":"identifier","text":"paramType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType\/title","value":"AgoraChatSilentModeParamType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeParamType\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeParamType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}