{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatclientdelegate\/useraccountdidremovefromserver()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatclientdelegate\/useraccountdidremovefromserver()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidRemoveFromServer()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the current chat user is removed from the server."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"role":"symbol","title":"userAccountDidRemoveFromServer()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatClientDelegate(im)userAccountDidRemoveFromServer","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate":{"role":"symbol","title":"AgoraChatClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatClientDelegate"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatClientDelegate"}],"url":"\/documentation\/agorachat\/agorachatclientdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatClientDelegate/userAccountDidRemoveFromServer()":{"navigatorTitle":[{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"role":"symbol","title":"userAccountDidRemoveFromServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Occurs when the current chat user is removed from the server."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatClientDelegate\/userAccountDidRemoveFromServer()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatclientdelegate\/useraccountdidremovefromserver()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userAccountDidRemoveFromServer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate\/title","value":"AgoraChatClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidRemoveFromServer()\/title","value":"userAccountDidRemoveFromServer"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatClientDelegate~1userAccountDidRemoveFromServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}