{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverServingForbidden"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/serverservingforbidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachaterrorcode\/serverservingforbidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/serverServingForbidden","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fails to retrieve the DNS configurations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverServingForbidden"}],"title":"AgoraChatErrorCode.serverServingForbidden","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatErrorCode@AgoraChatErrorServerServingForbidden","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorServerServingForbidden"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode/serverServingForbidden":{"role":"symbol","title":"AgoraChatErrorCode.serverServingForbidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverServingForbidden"}],"abstract":[{"type":"text","text":"Fails to retrieve the DNS configurations."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode\/serverServingForbidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorServerServingForbidden"}],"url":"\/documentation\/agorachat\/agorachaterrorcode\/serverservingforbidden"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatErrorCode":{"role":"symbol","title":"AgoraChatErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatErrorCode"}],"url":"\/documentation\/agorachat\/agorachaterrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatErrorServerServingForbidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorServerServingForbidden"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatErrorServerServingForbidden"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1serverServingForbidden\/title","value":"AgoraChatErrorServerServingForbidden"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode~1serverServingForbidden\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorServerServingForbidden"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/title","value":"AgoraChatErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraChatErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}