{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType","preciseIdentifier":"c:@E@AgoraChatPushRemindType","text":"AgoraChatPushRemindType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatsilentmoderesult\/remindtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatsilentmoderesult\/remindtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeResult\/remindType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The remind type for push messages."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushRemindType","preciseIdentifier":"c:@E@AgoraChatPushRemindType"}],"title":"remindType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatSilentModeResult(py)remindType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"remindType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeResult"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeResult":{"role":"symbol","title":"AgoraChatSilentModeResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatSilentModeResult"}],"abstract":[{"type":"text","text":"The silent message result object"}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatSilentModeResult"}],"url":"\/documentation\/agorachat\/agorachatsilentmoderesult"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatPushRemindType":{"role":"symbol","title":"AgoraChatPushRemindType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatPushRemindType"}],"abstract":[{"type":"text","text":"The remind type of push message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatPushRemindType"}],"url":"\/documentation\/agorachat\/agorachatpushremindtype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatSilentModeResult/remindType":{"role":"symbol","title":"remindType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatPushRemindType","preciseIdentifier":"c:@E@AgoraChatPushRemindType"}],"abstract":[{"type":"text","text":"The remind type for push messages."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatSilentModeResult\/remindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remindType"}],"url":"\/documentation\/agorachat\/agorachatsilentmoderesult\/remindtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"remindType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"remindType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatPushRemindType","preciseIdentifier":"c:@E@AgoraChatPushRemindType","text":"AgoraChatPushRemindType"},{"kind":"text","text":" "},{"kind":"identifier","text":"remindType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeResult\/title","value":"AgoraChatSilentModeResult"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeResult\/fragments","value":[{"kind":"identifier","text":"AgoraChatSilentModeResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType\/title","value":"AgoraChatPushRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatPushRemindType\/fragments","value":[{"kind":"identifier","text":"AgoraChatPushRemindType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeResult~1remindType\/title","value":"remindType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatSilentModeResult~1remindType\/fragments","value":[{"kind":"identifier","text":"remindType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}