{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent","text":"AgoraChatThreadEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onchatthreadcreate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onchatthreadcreate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadCreate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when a message thread is created."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadCreate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent"},{"kind":"text","text":")"}],"title":"onChatThreadCreate(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraChatThreadManagerDelegate(im)onChatThreadCreate:","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"onChatThreadCreate:"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate/onChatThreadCreate(_:)":{"role":"symbol","title":"onChatThreadCreate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadCreate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a message thread is created."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate\/onChatThreadCreate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onChatThreadCreate:"}],"url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate\/onchatthreadcreate(_:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadManagerDelegate":{"role":"symbol","title":"AgoraChatThreadManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"abstract":[{"type":"text","text":"The message thread event callback protocol."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatthreadmanagerdelegate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatThreadEvent":{"role":"symbol","title":"AgoraChatThreadEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatThreadEvent"}],"abstract":[{"type":"text","text":"The message thread event class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatThreadEvent"}],"url":"\/documentation\/agorachat\/agorachatthreadevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onChatThreadCreate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadCreate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onChatThreadCreate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatThreadEvent","preciseIdentifier":"c:objc(cs)AgoraChatThreadEvent","text":"AgoraChatThreadEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadCreate(_:)\/title","value":"onChatThreadCreate:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate~1onChatThreadCreate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadCreate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate\/title","value":"AgoraChatThreadManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatThreadManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadEvent\/title","value":"AgoraChatThreadEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatThreadEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChatThreadEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}