{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userLeave"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroupleavereason\/userleave"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroupleavereason\/userleave"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupLeaveReason\/userLeave","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The member is removed by the group owner."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userLeave"}],"title":"AgoraChatGroupLeaveReason.userLeave","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatGroupLeaveReason@AgoraChatGroupLeaveReasonUserLeave","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupLeaveReasonUserLeave"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupLeaveReason"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupLeaveReason/userLeave":{"role":"symbol","title":"AgoraChatGroupLeaveReason.userLeave","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userLeave"}],"abstract":[{"type":"text","text":"The member is removed by the group owner."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupLeaveReason\/userLeave","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupLeaveReasonUserLeave"}],"url":"\/documentation\/agorachat\/agorachatgroupleavereason\/userleave"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupLeaveReason":{"role":"symbol","title":"AgoraChatGroupLeaveReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupLeaveReason"}],"abstract":[{"type":"text","text":"The reasons for a group member leaving the group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupLeaveReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupLeaveReason"}],"url":"\/documentation\/agorachat\/agorachatgroupleavereason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatGroupLeaveReasonUserLeave"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupLeaveReasonUserLeave"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatGroupLeaveReasonUserLeave"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupLeaveReason~1userLeave\/title","value":"AgoraChatGroupLeaveReasonUserLeave"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupLeaveReason~1userLeave\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupLeaveReasonUserLeave"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupLeaveReason\/title","value":"AgoraChatGroupLeaveReason"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupLeaveReason\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupLeaveReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}