{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountValidation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatserverchecktype\/accountvalidation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatserverchecktype\/accountvalidation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/accountValidation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountValidation"}],"title":"AgoraChatServerCheckType.accountValidation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatServerCheckType@AgoraChatServerCheckAccountValidation","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType/accountValidation":{"role":"symbol","title":"AgoraChatServerCheckType.accountValidation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountValidation"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType\/accountValidation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype\/accountvalidation"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatServerCheckType":{"role":"symbol","title":"AgoraChatServerCheckType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatServerCheckType"}],"abstract":[{"type":"text","text":"This enum lists the server diagnostic tests which are run for the current user when you call AgoraChatClient::serviceCheckWithUsername. This is an asynchronous method. If there is an error, check the error code to know the error information."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatServerCheckType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatServerCheckType"}],"url":"\/documentation\/agorachat\/agorachatserverchecktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatServerCheckAccountValidation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1accountValidation\/title","value":"AgoraChatServerCheckAccountValidation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType~1accountValidation\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckAccountValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType\/title","value":"AgoraChatServerCheckType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatServerCheckType\/fragments","value":[{"kind":"identifier","text":"AgoraChatServerCheckType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}