{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"down"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatmessagesearchdirection\/down"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatmessagesearchdirection\/down"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection\/down","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Messages are retrieved in the descending order of the timestamp included in them."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"down"}],"title":"AgoraChatMessageSearchDirection.down","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatMessageSearchDirection@AgoraChatMessageSearchDirectionDown","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageSearchDirectionDown"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageSearchDirection":{"role":"symbol","title":"AgoraChatMessageSearchDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageSearchDirection"}],"abstract":[{"type":"text","text":"The message search directions."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageSearchDirection"}],"url":"\/documentation\/agorachat\/agorachatmessagesearchdirection"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageSearchDirection/down":{"role":"symbol","title":"AgoraChatMessageSearchDirection.down","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"down"}],"abstract":[{"type":"text","text":"Messages are retrieved in the descending order of the timestamp included in them."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection\/down","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageSearchDirectionDown"}],"url":"\/documentation\/agorachat\/agorachatmessagesearchdirection\/down"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatMessageSearchDirectionDown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageSearchDirectionDown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatMessageSearchDirectionDown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageSearchDirection\/title","value":"AgoraChatMessageSearchDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageSearchDirection\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageSearchDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageSearchDirection~1down\/title","value":"AgoraChatMessageSearchDirectionDown"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageSearchDirection~1down\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageSearchDirectionDown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}