{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birth"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatuserinfotype\/birth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatuserinfotype\/birth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType\/birth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user signature."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birth"}],"title":"AgoraChatUserInfoType.birth","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatUserInfoType@AgoraChatUserInfoTypeBirth","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoTypeBirth"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatUserInfoType":{"role":"symbol","title":"AgoraChatUserInfoType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatUserInfoType"}],"abstract":[{"type":"text","text":"The user information type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoType"}],"url":"\/documentation\/agorachat\/agorachatuserinfotype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatUserInfoType/birth":{"role":"symbol","title":"AgoraChatUserInfoType.birth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birth"}],"abstract":[{"type":"text","text":"The user signature."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatUserInfoType\/birth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatUserInfoTypeBirth"}],"url":"\/documentation\/agorachat\/agorachatuserinfotype\/birth"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatUserInfoTypeBirth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoTypeBirth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatUserInfoTypeBirth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType\/title","value":"AgoraChatUserInfoType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType~1birth\/title","value":"AgoraChatUserInfoTypeBirth"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatUserInfoType~1birth\/fragments","value":[{"kind":"identifier","text":"AgoraChatUserInfoTypeBirth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}