{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllConversations"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","preciseIdentifier":"c:objc(cs)AgoraChatConversation","text":"AgoraChatConversation"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatmanager\/getallconversations()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatmanager\/getallconversations()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager\/getAllConversations()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets all conversations in the local database. The SDK loads the conversations from the memory first. If no conversation is in the memory, the SDK loads from the local database."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getAllConversations"}],"role":"symbol","title":"getAllConversations()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllConversations"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraChatConversation","preciseIdentifier":"c:objc(cs)AgoraChatConversation"},{"kind":"text","text":"]?"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatManager(im)getAllConversations","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatManager":{"role":"symbol","title":"IAgoraChatManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatManager"}],"abstract":[{"type":"text","text":"This protocol that defines the operations of chat."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatManager"}],"url":"\/documentation\/agorachat\/iagorachatmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatManager/getAllConversations()":{"navigatorTitle":[{"kind":"identifier","text":"getAllConversations"}],"role":"symbol","title":"getAllConversations()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAllConversations"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraChatConversation","preciseIdentifier":"c:objc(cs)AgoraChatConversation"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Gets all conversations in the local database. The SDK loads the conversations from the memory first. If no conversation is in the memory, the SDK loads from the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager\/getAllConversations()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatmanager\/getallconversations()"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatConversation":{"role":"symbol","title":"AgoraChatConversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatConversation"}],"abstract":[{"type":"text","text":"The chat conversation class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatConversation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatConversation"}],"url":"\/documentation\/agorachat\/agorachatconversation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAllConversations"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllConversations"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatConversation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getAllConversations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager\/title","value":"IAgoraChatManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager~1getAllConversations()\/title","value":"getAllConversations"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager~1getAllConversations()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAllConversations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/title","value":"AgoraChatConversation"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatConversation\/fragments","value":[{"kind":"identifier","text":"AgoraChatConversation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}