{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReactionList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messageIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"chatType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType","preciseIdentifier":"c:@E@AgoraChatType","text":"AgoraChatType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction","text":"AgoraChatMessageReaction"},{"kind":"text","text":"]], "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError","text":"AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatmanager\/getreactionlist(_:groupid:chattype:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatmanager\/getreactionlist(_:groupid:chattype:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager\/getReactionList(_:groupId:chatType:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the Reaction list."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getReactionList:groupId:chatType:completion:"}],"role":"symbol","title":"getReactionList(_:groupId:chatType:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReactionList"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"chatType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatType","preciseIdentifier":"c:@E@AgoraChatType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction"},{"kind":"text","text":"]], "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatManager(im)getReactionList:groupId:chatType:completion:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatManager/getReactionList(_:groupId:chatType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"getReactionList:groupId:chatType:completion:"}],"role":"symbol","title":"getReactionList(_:groupId:chatType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getReactionList"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"chatType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatType","preciseIdentifier":"c:@E@AgoraChatType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","text":"AgoraChatMessageReaction","preciseIdentifier":"c:objc(cs)AgoraChatMessageReaction"},{"kind":"text","text":"]], "},{"kind":"typeIdentifier","text":"AgoraChatError","preciseIdentifier":"c:objc(cs)AgoraChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the Reaction list."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager\/getReactionList(_:groupId:chatType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatmanager\/getreactionlist(_:groupid:chattype:completion:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatType":{"role":"symbol","title":"AgoraChatType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatType"}],"abstract":[{"type":"text","text":"Chat types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatType"}],"url":"\/documentation\/agorachat\/agorachattype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatError":{"role":"symbol","title":"AgoraChatError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatError"}],"abstract":[{"type":"text","text":"The error defined by the SDK."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatError"}],"url":"\/documentation\/agorachat\/agorachaterror"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageReaction":{"role":"symbol","title":"AgoraChatMessageReaction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageReaction"}],"abstract":[{"type":"text","text":"The message reaction object."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageReaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageReaction"}],"url":"\/documentation\/agorachat\/agorachatmessagereaction"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatManager":{"role":"symbol","title":"IAgoraChatManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatManager"}],"abstract":[{"type":"text","text":"This protocol that defines the operations of chat."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatManager"}],"url":"\/documentation\/agorachat\/iagorachatmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getReactionList:groupId:chatType:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReactionList:groupId:chatType:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getReactionList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"groupId"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatType","preciseIdentifier":"c:@E@AgoraChatType","text":"AgoraChatType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"chatType"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSDictionary<NSString *,NSArray<AgoraChatMessageReaction *> *> *, AgoraChatError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSDictionary#*$objc(cs)AgoraChatError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager~1getReactionList(_:groupId:chatType:completion:)\/title","value":"getReactionList:groupId:chatType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager~1getReactionList(_:groupId:chatType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getReactionList:groupId:chatType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType\/title","value":"AgoraChatType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatType\/fragments","value":[{"kind":"identifier","text":"AgoraChatType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/title","value":"AgoraChatError"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatError\/fragments","value":[{"kind":"identifier","text":"AgoraChatError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction\/title","value":"AgoraChatMessageReaction"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageReaction\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageReaction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager\/title","value":"IAgoraChatManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}