{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType","preciseIdentifier":"c:@E@AgoraChatMessageBodyType","text":"AgoraChatMessageBodyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection","text":"AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage","text":"AgoraChatMessage"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method returns messages in chronological order."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is a synchronous method and blocks the current thread."}]},{"type":"codeListing","syntax":null,"code":["                      - `UP`: The SDK retrieves messages in the descending order of the timestamp included in them.","                      - `DOWN`：The SDK retrieves messages in the ascending order of the timestamp included in them. "]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatmanager\/loadmessages(with:timestamp:count:fromuser:searchdirection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatmanager\/loadmessages(with:timestamp:count:fromuser:searchdirection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager\/loadMessages(with:timestamp:count:fromUser:searchDirection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Loads messages with the specified keyword from the local database."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"}],"role":"symbol","title":"loadMessages(with:timestamp:count:fromUser:searchDirection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBodyType","preciseIdentifier":"c:@E@AgoraChatMessageBodyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatManager(im)loadMessagesWithType:timestamp:count:fromUser:searchDirection:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatManager/loadMessages(with:timestamp:count:fromUser:searchDirection:)":{"navigatorTitle":[{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"}],"role":"symbol","title":"loadMessages(with:timestamp:count:fromUser:searchDirection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageBodyType","preciseIdentifier":"c:@E@AgoraChatMessageBodyType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"AgoraChatMessage","preciseIdentifier":"c:objc(cs)AgoraChatMessage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Loads messages with the specified keyword from the local database."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager\/loadMessages(with:timestamp:count:fromUser:searchDirection:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatmanager\/loadmessages(with:timestamp:count:fromuser:searchdirection:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageSearchDirection":{"role":"symbol","title":"AgoraChatMessageSearchDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageSearchDirection"}],"abstract":[{"type":"text","text":"The message search directions."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageSearchDirection"}],"url":"\/documentation\/agorachat\/agorachatmessagesearchdirection"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessage":{"role":"symbol","title":"AgoraChatMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessage"}],"abstract":[{"type":"text","text":"The chat message class."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessage"}],"url":"\/documentation\/agorachat\/agorachatmessage"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatManager":{"role":"symbol","title":"IAgoraChatManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatManager"}],"abstract":[{"type":"text","text":"This protocol that defines the operations of chat."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatManager"}],"url":"\/documentation\/agorachat\/iagorachatmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatMessageBodyType":{"role":"symbol","title":"AgoraChatMessageBodyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatMessageBodyType"}],"abstract":[{"type":"text","text":"The enum of message body types."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}],"url":"\/documentation\/agorachat\/agorachatmessagebodytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loadMessagesWithType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageBodyType","preciseIdentifier":"c:@E@AgoraChatMessageBodyType","text":"AgoraChatMessageBodyType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aType"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"long long","preciseIdentifier":"c:K"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aTimestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"count:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchDirection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatMessageSearchDirection","preciseIdentifier":"c:@E@AgoraChatMessageSearchDirection","text":"AgoraChatMessageSearchDirection"},{"kind":"text","text":")"},{"kind":"internalParam","text":"aDirection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager~1loadMessages(with:timestamp:count:fromUser:searchDirection:)\/title","value":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager~1loadMessages(with:timestamp:count:fromUser:searchDirection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadMessagesWithType:timestamp:count:fromUser:searchDirection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageSearchDirection\/title","value":"AgoraChatMessageSearchDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageSearchDirection\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageSearchDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/title","value":"AgoraChatMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessage\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager\/title","value":"IAgoraChatManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType\/title","value":"AgoraChatMessageBodyType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatMessageBodyType\/fragments","value":[{"kind":"identifier","text":"AgoraChatMessageBodyType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}