{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidAdd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Both user A and B will receive this callback after User B agreed user A’s add-friend invitation."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidadd(byuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidadd(byuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidAdd(byUser:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the user is added as a contact by another user."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"friendshipDidAddByUser:"}],"role":"symbol","title":"friendshipDidAdd(byUser:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidAdd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraChatContactManagerDelegate(im)friendshipDidAddByUser:","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate/friendshipDidAdd(byUser:)":{"navigatorTitle":[{"kind":"identifier","text":"friendshipDidAddByUser:"}],"role":"symbol","title":"friendshipDidAdd(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidAdd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the user is added as a contact by another user."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate\/friendshipDidAdd(byUser:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate\/friendshipdidadd(byuser:)"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatContactManagerDelegate":{"role":"symbol","title":"AgoraChatContactManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"abstract":[{"type":"text","text":"The contact related callbacks."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatContactManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}],"url":"\/documentation\/agorachat\/agorachatcontactmanagerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"friendshipDidAddByUser:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidAddByUser:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"friendshipDidAddByUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidAdd(byUser:)\/title","value":"friendshipDidAddByUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate~1friendshipDidAdd(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidAddByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate\/title","value":"AgoraChatContactManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatContactManagerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraChatContactManagerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}