{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getJoinedGroups"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup","text":"AgoraChatGroup"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/iagorachatgroupmanager\/getjoinedgroups()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/iagorachatgroupmanager\/getjoinedgroups()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager\/getJoinedGroups()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets all groups."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getJoinedGroups"}],"role":"symbol","title":"getJoinedGroups()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getJoinedGroups"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":"]?"}],"symbolKind":"method","externalID":"c:objc(pl)IAgoraChatGroupManager(im)getJoinedGroups","required":true,"modules":[{"name":"AgoraChat"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup":{"role":"symbol","title":"AgoraChatGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"}],"abstract":[{"type":"text","text":"The group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroup"}],"url":"\/documentation\/agorachat\/agorachatgroup"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatGroupManager":{"role":"symbol","title":"IAgoraChatGroupManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAgoraChatGroupManager"}],"abstract":[{"type":"text","text":"The group operations."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IAgoraChatGroupManager"}],"url":"\/documentation\/agorachat\/iagorachatgroupmanager"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/IAgoraChatGroupManager/getJoinedGroups()":{"navigatorTitle":[{"kind":"identifier","text":"getJoinedGroups"}],"role":"symbol","title":"getJoinedGroups()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getJoinedGroups"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraChatGroup","preciseIdentifier":"c:objc(cs)AgoraChatGroup"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Gets all groups."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/IAgoraChatGroupManager\/getJoinedGroups()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorachat\/iagorachatgroupmanager\/getjoinedgroups()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getJoinedGroups"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getJoinedGroups"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatGroup *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getJoinedGroups"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/title","value":"AgoraChatGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager\/title","value":"IAgoraChatGroupManager"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager\/fragments","value":[{"kind":"identifier","text":"IAgoraChatGroupManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager~1getJoinedGroups()\/title","value":"getJoinedGroups"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1IAgoraChatGroupManager~1getJoinedGroups()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getJoinedGroups"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}