{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType","preciseIdentifier":"c:@E@AgoraChatGroupPermissionType","text":"AgoraChatGroupPermissionType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatgroup\/permissiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatgroup\/permissiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/permissionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The group membership type of the current login account."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupPermissionType","preciseIdentifier":"c:@E@AgoraChatGroupPermissionType"}],"title":"permissionType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChatGroup(py)permissionType","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"permissionType"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroupPermissionType":{"role":"symbol","title":"AgoraChatGroupPermissionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroupPermissionType"}],"abstract":[{"type":"text","text":"The group permission type."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}],"url":"\/documentation\/agorachat\/agorachatgrouppermissiontype"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup":{"role":"symbol","title":"AgoraChatGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatGroup"}],"abstract":[{"type":"text","text":"The group."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatGroup"}],"url":"\/documentation\/agorachat\/agorachatgroup"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatGroup/permissionType":{"role":"symbol","title":"permissionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatGroupPermissionType","preciseIdentifier":"c:@E@AgoraChatGroupPermissionType"}],"abstract":[{"type":"text","text":"The group membership type of the current login account."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroup\/permissionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"permissionType"}],"url":"\/documentation\/agorachat\/agorachatgroup\/permissiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"permissionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"permissionType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatGroupPermissionType","preciseIdentifier":"c:@E@AgoraChatGroupPermissionType","text":"AgoraChatGroupPermissionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"permissionType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType\/title","value":"AgoraChatGroupPermissionType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroupPermissionType\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroupPermissionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/title","value":"AgoraChatGroup"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup\/fragments","value":[{"kind":"identifier","text":"AgoraChatGroup"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1permissionType\/title","value":"permissionType"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatGroup~1permissionType\/fragments","value":[{"kind":"identifier","text":"permissionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}