{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus","text":"AgoraChatDownloadStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatdownloadstatus\/successed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatdownloadstatus\/successed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus\/successed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"File message download is pending."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"title":"successed","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@AgoraChatDownloadStatus@AgoraChatDownloadStatusSuccessed","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatusSuccessed"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatDownloadStatus":{"role":"symbol","title":"AgoraChatDownloadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"The status types for downloading the file message."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}],"url":"\/documentation\/agorachat\/agorachatdownloadstatus"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatDownloadStatus/successed":{"role":"symbol","title":"successed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChatDownloadStatus","preciseIdentifier":"c:@E@AgoraChatDownloadStatus"}],"abstract":[{"type":"text","text":"File message download is pending."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatDownloadStatus\/successed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDownloadStatusSuccessed"}],"url":"\/documentation\/agorachat\/agorachatdownloadstatus\/successed"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatDownloadStatusSuccessed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatusSuccessed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatDownloadStatusSuccessed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/title","value":"AgoraChatDownloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus~1successed\/title","value":"AgoraChatDownloadStatusSuccessed"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatDownloadStatus~1successed\/fragments","value":[{"kind":"identifier","text":"AgoraChatDownloadStatusSuccessed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}