{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveNotificationResponse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatnotificationstate\/didreceivenotificationresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatnotificationstate\/didreceivenotificationresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState\/didReceiveNotificationResponse","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveNotificationResponse"}],"title":"AgoraChatNotificationState.didReceiveNotificationResponse","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatNotificationState@AgoraChatDidReceiveNotificationResponse","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatDidReceiveNotificationResponse"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatNotificationState/didReceiveNotificationResponse":{"role":"symbol","title":"AgoraChatNotificationState.didReceiveNotificationResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveNotificationResponse"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState\/didReceiveNotificationResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatDidReceiveNotificationResponse"}],"url":"\/documentation\/agorachat\/agorachatnotificationstate\/didreceivenotificationresponse"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatNotificationState":{"role":"symbol","title":"AgoraChatNotificationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatNotificationState"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatNotificationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatNotificationState"}],"url":"\/documentation\/agorachat\/agorachatnotificationstate"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatDidReceiveNotificationResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatDidReceiveNotificationResponse"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatDidReceiveNotificationResponse"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState~1didReceiveNotificationResponse\/title","value":"AgoraChatDidReceiveNotificationResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState~1didReceiveNotificationResponse\/fragments","value":[{"kind":"identifier","text":"AgoraChatDidReceiveNotificationResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState\/title","value":"AgoraChatNotificationState"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatNotificationState\/fragments","value":[{"kind":"identifier","text":"AgoraChatNotificationState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}