{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorachat\/agorachatroommessagepriority\/low"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorachat\/agorachatroommessagepriority\/low"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/low","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"title":"AgoraChatRoomMessagePriority.low","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChatRoomMessagePriority@AgoraChatRoomMessagePriorityLow","modules":[{"name":"AgoraChat"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}]},"hierarchy":{"paths":[["doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority"]]},"references":{"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority":{"role":"symbol","title":"AgoraChatRoomMessagePriority","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}],"abstract":[{"type":"text","text":"The chat room message priorities."}],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}],"url":"\/documentation\/agorachat\/agorachatroommessagepriority"},"doc://com.easemob.AgoraChat/documentation/AgoraChat/AgoraChatRoomMessagePriority/low":{"role":"symbol","title":"AgoraChatRoomMessagePriority.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat\/AgoraChatRoomMessagePriority\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}],"url":"\/documentation\/agorachat\/agorachatroommessagepriority\/low"},"doc://com.easemob.AgoraChat/documentation/AgoraChat":{"role":"collection","title":"AgoraChat","abstract":[],"identifier":"doc:\/\/com.easemob.AgoraChat\/documentation\/AgoraChat","kind":"symbol","type":"topic","url":"\/documentation\/agorachat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChatRoomMessagePriorityLow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority\/title","value":"AgoraChatRoomMessagePriority"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1low\/title","value":"AgoraChatRoomMessagePriorityLow"},{"op":"replace","path":"\/references\/doc:~1~1com.easemob.AgoraChat~1documentation~1AgoraChat~1AgoraChatRoomMessagePriority~1low\/fragments","value":[{"kind":"identifier","text":"AgoraChatRoomMessagePriorityLow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}